armaduras = [
  {
    "nome": "Acolchoada",
    "preco": "5 po",
    "classe_armadura": "11 + modificador de Des",
    "forca": "–",
    "furtividade": "Desvantagem",
    "peso": "4 kg",
    "categoria": "Armadura Leve",
    "tempo_vestir": "1 minuto",
    "tempo_remover": "1 minuto",
    "descricao": "A armadura acolchoada consiste em camadas de panos acolchoados e batidos. "
  },
  {
    "nome": "Couro",
    "preco": "10 po",
    "classe_armadura": "11 + modificador de Des",
    "forca": "–",
    "furtividade": "–",
    "peso": "5 kg",
    "categoria": "Armadura Leve",
    "tempo_vestir": "1 minuto",
    "tempo_remover": "1 minuto",
    "descricao": "O peitoral e as ombreiras da armadura de couro são feitos de couro que foi endurecido após ser fervido em óleo. O resto da armadura é feita de materiais mais macios e mais flexíveis. "
  },
  {
    "nome": "Couro Batido",
    "preco": "45 po",
    "classe_armadura": "12 + modificador de Des",
    "forca": "–",
    "furtividade": "–",
    "peso": "6,5 kg",
    "categoria": "Armadura Leve",
    "tempo_vestir": "1 minuto",
    "tempo_remover": "1 minuto",
    "descricao": "Feita de couro resistente, mas flexível, a armadura de couro batido é reforçada com rebites ou cravos."
  },
  {
    "nome": "Gibão de Peles",
    "preco": "10 po",
    "classe_armadura": "12 + modificador de Des (máx. +2)",
    "forca": "–",
    "furtividade": "–",
    "peso": "6 kg",
    "categoria": "Armadura Média",
    "tempo_vestir": "5 minutos",
    "tempo_remover": "1 minuto",
    "descricao": "Um gibão de peles é um armadura bruta consistindo de peles grossas. É comumente usada por tribos bárbaras, humanoides malignos e outros povos que não têm acesso às ferramentas e materiais necessários para criar uma armadura melhor."
  },
  {
    "nome": "Camisão de Malha",
    "preco": "30 po",
    "classe_armadura": "13 + modificador de Des (máx. +2)",
    "forca": "–",
    "furtividade": "–",
    "peso": "10 kg",
    "categoria": "Armadura Média",
    "tempo_vestir": "5 minutos",
    "tempo_remover": "1 minuto",
    "descricao": "Feito de anéis de metal intercalados, um camisão de cota de malha é usado entre as camadas de roupa. Essa armadura oferece proteção modesta para a parte superior do corpo de quem a usa e permite que o som dos anéis de metal, friccionados uns contra os outros, sejam amortecidos pelas camadas exteriores. "
  },
  {
    "nome": "Brunea",
    "preco": "50 po",
    "classe_armadura": "14 + modificador de Des (máx. +2)",
    "forca": "–",
    "furtividade": "Desvantagem",
    "peso": "22,5 kg",
    "categoria": "Armadura Média",
    "tempo_vestir": "5 minutos",
    "tempo_remover": "1 minuto",
    "descricao": "Essa armadura consiste em um casaco e calças (e talvez uma saia separada) de couro coberto com peças sobrepostas de metal, assim como as escamas de peixe. O conjunto inclui manoplas. "
  },
  {
    "nome": "Peitoral",
    "preco": "400 po",
    "classe_armadura": "14 + modificador de Des (máx. +2)",
    "forca": "–",
    "furtividade": "–",
    "peso": "10 kg",
    "categoria": "Armadura Média",
    "tempo_vestir": "5 minutos",
    "tempo_remover": "1 minuto",
    "descricao": "A armadura peitoral é constituída por um peitoral de metal usado com couro flexível em seu interior. Embora ele deixe as pernas e braços do usuário relativamente desprotegidos, essa armadura fornece boa proteção para seus órgãos vitais, deixando quem a usa relativamente sem restrições."
  },
  {
    "nome": "Meia-Armadura",
    "preco": "750 po",
    "classe_armadura": "15 + modificador de Des (máx. +2)",
    "forca": "–",
    "furtividade": "Desvantagem",
    "peso": "20 kg",
    "categoria": "Armadura Média",
    "tempo_vestir": "5 minutos",
    "tempo_remover": "1 minuto",
    "descricao": "Essa armadura é composta de placas de metal moldadas que cobrem a maior parte do corpo. Ela não inclui proteção para as pernas além de caneleiras fixadas com tiras de couro."
  },
  {
    "nome": "Cota de Anéis",
    "preco": "30 po",
    "classe_armadura": "14",
    "forca": "–",
    "furtividade": "Desvantagem",
    "peso": "20 kg",
    "categoria": "Armadura Pesada",
    "tempo_vestir": "10 minutos",
    "tempo_remover": "5 minutos",
    "descricao": "Esta armadura é feita de couro com pesados anéis presos a ela. Os anéis ajudam a reforçar a armadura contra golpes de espadas e machados. A cota de anéis é inferior à cota de malha e geralmente é vestida apenas por aqueles que não podem pagar por uma armadura melhor."
  },
  {
    "nome": "Cota de Malha",
    "preco": "75 po",
    "classe_armadura": "16",
    "forca": "13",
    "furtividade": "Desvantagem",
    "peso": "27,5 kg",
    "categoria": "Armadura Pesada",
    "tempo_vestir": "10 minutos",
    "tempo_remover": "5 minutos",
    "descricao": "Feita de anéis de metal entrelaçados, a cota de malha inclui uma camada de tecido acolchoado usada por baixo da malha de metal para evitar atrito e amortecer o impacto dos golpes. O conjunto inclui manoplas."
  },
  {
    "nome": "Cota de Talas",
    "preco": "200 po",
    "classe_armadura": "17",
    "forca": "15",
    "furtividade": "Desvantagem",
    "peso": "30 kg",
    "categoria": "Armadura Pesada",
    "tempo_vestir": "10 minutos",
    "tempo_remover": "5 minutos",
    "descricao": "Essa armadura é feita de tiras verticais de metal, rebitadas a um suporte de couro, usadas sobre um preenchimento de pano. Cotas de malha flexíveis protegem as articulações."
  },
  {
    "nome": "Placas",
    "preco": "1.500 po",
    "classe_armadura": "18",
    "forca": "15",
    "furtividade": "Desvantagem",
    "peso": "32,5 kg",
    "categoria": "Armadura Pesada",
    "tempo_vestir": "10 minutos",
    "tempo_remover": "5 minutos",
    "descricao": "A armadura de placas consiste em placas de metal moldadas para cobrir todo o corpo. Inclui luvas, botas de couro pesadas, um capacete com viseira e espessas camadas de enchimento por baixo da armadura. Fivelas e tiras de couro distribuem o peso ao longo do corpo."
  },
  {
    "nome": "Escudo",
    "preco": "10 po",
    "classe_armadura": "+2",
    "forca": "–",
    "furtividade": "–",
    "peso": "3 kg",
    "categoria": "Escudo",
    "tempo_vestir": "1 ação",
    "tempo_remover": "1 ação",
    "descricao": "Escudo. Um escudo é feito de madeira ou metal e é usado com uma mão. Empunhar um escudo aumenta sua Classe de Armadura em 2. Você só pode se beneficiar de um escudo por vez. "
  }
]