magias_nivel_1 = [
{
    "nome": "Absorver Elementos",
    "nivel": 1,
    "classes": ["Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma reação, que você faz quando sofre dano de ácido, gelo, fogo, elétrico ou trovejante",
    "alcance": "Pessoal",
    "componentes": "S",
    "duracao": "Uma rodada",
    "descricao": "A magia reverte parte da energia recebida, minimizando seu efeito em você e armazenando-a no seu próximo ataque corpo a corpo. Você tem resistência ao tipo de dano pertinente, incluindo do ataque que desencadeou a magia, até o início do seu próximo turno. Além disso, na primeira vez que você atingir um ataque corpo a corpo no seu próximo turno, o alvo sofre 1d6 de dano extra do tipo relacionado e a magia termina.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, o dano extra aumenta em 1d6 para cada nível do espaço acima do 1º."
},
{
    "nome": "Alarme",
    "nivel": 1,
    "classes": ["Artífice", "Patrulheiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma sineta e o pedaço de um fino fio de prata)",
    "duracao": "8 horas",
    "descricao": "Você prepara um alarme contra intrusos indesejados. Escolha uma porta, uma janela ou uma área dentro do alcance que não seja maior que um cubo de 6 metros de lado [20-foot cube]. Enquanto a magia durar, um alarme o alerta quando uma criatura Minúscula ou maior tocar ou entrar na área protegida. Ao conjurar a magia, você pode escolher quais criaturas não dispararão o alarme. Você também pode escolher se o alarme é mental ou audível.\n\nUm alarme mental avisa com um sibilo em sua mente, se você estiver no alcance de 1,5 quilômetro [1 mile] da área protegida. Esse sibilo o desperta caso você esteja dormindo.\n\nUm alarme audível produz o som de uma sineta durante 10 segundos, dentro de um alcance de 18 metros [60 ft.]."
},
{
    "nome": "Amizade Animal",
    "nivel": 1,
    "classes": ["Bardo", "Druida", "Patrulheiro"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um punhado de comida)",
    "duracao": "24 horas",
    "descricao": "Esta magia permite que você convença uma fera de que não pretende causar-lhe mal. Escolha uma fera à sua vista, no alcance da magia. Ela deve ser capaz de vê-lo e ouvi-lo. Se a Inteligência da fera for 4 ou maior, a magia falha. Caso contrário, a fera deve ser bem-sucedida em uma salvaguarda de Sabedoria ou fica enfeitiçada por você enquanto a magia durar. Se você ou qualquer um de seus companheiros causar dano ao alvo, a magia se encerra.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode afetar uma fera adicional para cada círculo do espaço acima do 1º."
},
{
    "nome": "Armadura Arcana",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um pedaço de couro curtido)",
    "duracao": "8 horas",
    "descricao": "Você toca uma criatura voluntária que não esteja usando armadura. Uma força mágica protetora circunda-a enquanto a magia durar. A CA base do alvo se torna 13 + o modificador de Destreza dele. A magia termina se o alvo vestir uma armadura ou se você a dispensar com uma ação."
},
{
    "nome": "Armadura de Agathys",
    "nivel": 1,
    "classes": ["Bruxo"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S M (um copo de água)",
    "duracao": "Uma hora",
    "descricao": "Uma força mágica protetora envolve-o, manifestando-se como um frio espectral que cobre você e o seu equipamento. Você ganha 5 pontos de vida temporários enquanto a magia durar. Se uma criatura atingi-lo com um ataque corpo a corpo enquanto você possuir esses pontos de vida temporários, a criatura sofre 5 pontos de dano gélido.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, tanto os pontos de vida temporários quanto o dano gélido aumentam em 5 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Bênção",
    "nivel": 1,
    "classes": ["Clérigo", "Paladino"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma aspersão de água benta)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você abençoa até três criaturas à sua escolha dentro do alcance da magia. Sempre que um alvo realiza uma jogada de ataque ou uma salvaguarda antes da magia terminar, ele deve jogar 1d4 e adicionar o número obtido à jogada de ataque ou testes de salvaguarda.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode escolher como alvo uma criatura adicional para cada círculo do espaço acima do 1º."
},
{
    "nome": "Bom Fruto",
    "nivel": 1,
    "classes": ["Druida", "Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um ramo de visco)",
    "duracao": "Instantânea",
    "descricao": "Até dez frutos aparecem na sua mão, tornando-se magicamente infundidos. Uma criatura pode usar uma ação para comer um fruto. Comer um fruto restaura 1 ponto de vida, além de fornecer nutrição suficiente para sustentar uma criatura por um dia.\n\nOs frutos perdem sua potência se não tiverem sido consumidos após 24 horas da conjuração desta magia."
},
{
    "nome": "Braços de Hadar",
    "nivel": 1,
    "classes": ["Bruxo"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 3m [10 ft.])",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você invoca o poder de Hadar, a Fome Sombria. Gavinhas de energia negra irrompem de você e golpeiam todas as criaturas a até 3 metros [10 ft.] de distância. Cada criatura na área deve fazer uma salvaguarda de Força. Se falhar, o alvo sofre 2d6 pontos de dano necrótico e não pode ter reações até o próximo turno dele. Em caso de sucesso, a criatura sofre metade do dano e não sofre nenhum outro efeito.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Catapulta",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "S",
    "duracao": "Instantânea",
    "descricao": "Escolha um objeto pesando entre 0,5 e 2,5 quilos [1 to 5 pounds] dentro do alcance que não esteja sendo vestido ou carregado. O objeto voa em linha reta até 27m [90 ft.] na direção que você escolher antes de cair no chão, parando prematuramente se atingir uma superfície sólida. Se o objeto puder atingir uma criatura, a criatura deve realizar salvaguarda de Destreza. Se falhar, o objeto atinge o alvo e para de se mover. Se o objeto atingir alguma coisa, tanto o objeto quanto qualquer coisa que ele acertar sofrem 3d8 de dano contundente.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, o peso máximo do objeto que você pode arremessar com essa magia aumenta em 2,5 quilos [5 pounds], e o dano aumenta em 1d8, para cada nível do espaço acima do 1º."
},
{
    "nome": "Causar Medo",
    "nivel": 1,
    "classes": ["Bruxo", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você desperta o senso de mortalidade em uma criatura que você possa ver dentro do alcance. O alvo precisa ser bem sucedido em salvaguarda de Sabedoria ou se tornará amedrontada por você até que a magia termine. O alvo amedrontado pode repetir o salvaguarda ao fim de cada um de seus turnos, terminando o efeito em si mesmo com um sucesso.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, você pode adicionar uma criatura extra como alvo para cada nível do espaço acima do 1º. As criaturas precisam estar a no máximo 9m [30 ft.] uma da outra quando você as incluir como alvos."
},
{
    "nome": "Cerimônia",
    "nivel": 1,
    "classes": ["Clérigo", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma hora ou Ritual",
    "alcance": "Toque",
    "componentes": "V S M (pó de prata valendo, no mínimo, 25gp que a magia consome)",
    "duracao": "Instantânea",
    "descricao": "Você realiza uma cerimônia religiosa especial infundida com magia. Quando você lança a magia, escolha um dos ritos seguintes, cujo alvo deve estar dentro de 3m [10 ft.] de você durante toda a conjuração.\n\nExpiação. Você toca uma criatura disposta cujo alinhamento mudou e você faz um teste de Sabedoria (Intuição), CD 20. Em um teste bem-sucedido, você restaura o alvo para o alinhamento original.\nAbençoar Água. Você toca um frasco de água e faz com que se torne água benta.\nRito de passagem. Você toca um humanoide que seja um jovem adulto. Pelas próximas 24 horas, sempre que o alvo fizer um teste de habilidade, ele pode rolar um d4 e adicionar o número rolado ao teste de habilidade. A criatura pode se beneficiar deste rito apenas uma vez.\nDedicação. Você toca um humanoide que deseja se dedicar aos serviços do seu deus. Pelas próximas 24 horas, sempre que o alvo faz salvaguarda, ele pode rolar um d4 e adicionar o número rolado ao teste. A criatura pode se beneficiar desse rito apenas uma vez.\nRito fúnebre. Você toca em um cadáver, e nos próximos 7 dias, o alvo não pode se tornar morto-vivo por qualquer meio que não seja uma magia de desejo.\nCasamento. Você toca humanoides adultos dispostos a serem unidos em matrimônio. Pelos próximos 7 dias, cada alvo ganha um bônus de +2 na CA enquanto estiverem a 9m [30 ft.] um do outro. Uma criatura pode se beneficiar desse rito novamente apenas se tornar viúvo."
},
{
    "nome": "Comando",
    "nivel": 1,
    "classes": ["Clérigo", "Paladino"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Uma rodada",
    "descricao": "Você emite uma palavra de comando para uma criatura à sua vista e no alcance da magia. O alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria, ou passa a obedecer o comando no próximo turno dele. A magia não tem nenhum efeito se o alvo for um morto-vivo, se não entender seu idioma ou se o comando for diretamente prejudicial a ele.\n\nA seguir, veja alguns exemplos típicos de comandos e seus efeitos. Você pode emitir um comando diferente dos descritos aqui. Se fizer isso, o DM determina como o alvo se comporta. Se o alvo não puder seguir seu comando, a magia se encerra.\n\nAbaixar. O alvo fica caído e, em seguida, termina o próprio turno.\nAproximar. O alvo se move em sua direção pela rota mais curta e direta, terminando o turno ao se aproximar a até 1,5 metro [5 ft.] de você.\nFugir. O alvo gasta o próprio turno afastando-se de você pelo meio mais rápido disponível.\nLargar. O alvo deixa cair tudo o que está segurando e então termina o próprio turno.\nParar. O alvo não se mexe e não executa nenhuma ação. Uma criatura voadora permanece no ar, desde que seja capaz de fazê-lo. Se precisar se mover para ficar no ar, ela voa a distância mínima necessária para fazê-lo.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode afetar uma criatura adicional para cada círculo do espaço acima do 1º. As criaturas devem estar a até 9 metros [30 ft.] umas das outras quando você as escolhe como alvo."
},
{
    "nome": "Compreender Idiomas",
    "nivel": 1,
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S M (uma pitada de fuligem e sal)",
    "duracao": "Uma hora",
    "descricao": "Enquanto a magia durar, você entende o significado literal de qualquer idioma falado que ouvir. Você também entende qualquer idioma escrito que veja, mas deve tocar a superfície sobre a qual as palavras estão escritas. Demora cerca de 1 minuto para ler uma página de texto.\n\nEsta magia não decodifica mensagens secretas em um texto ou um glifo, como um selo arcano, que não faça parte de um idioma escrito."
},
{
    "nome": "Convocar Familiar",
    "nivel": 1,
    "classes": ["Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma hora ou Ritual",
    "alcance": "3m [10 ft.]",
    "componentes": "V S M (10 PO em carvão, incenso e ervas que devem ser consumidos pelo fogo em um braseiro de latão)",
    "duracao": "Instantânea",
    "descricao": "Você passa a contar com os serviços de um familiar, um espírito que assume a forma de um animal à sua escolha: morcego, gato, caranguejo, sapo (rã), falcão, lagarto, polvo, coruja, cobra venenosa, peixe (piranha), rato, corvo, cavalo marinho, aranha ou furão. Aparecendo em um espaço desocupado dentro do alcance da magia, o familiar tem as estatísticas da forma escolhida, apesar de ser um celestial, feérico ou ínfero (à sua escolha), em vez de uma fera.\n\nSeu familiar age independentemente de você, mas ele sempre obedece aos seus comandos. Em combate, joga a própria iniciativa e age no próprio turno. Um familiar não pode atacar, mas pode realizar outras ações normalmente.\n\nAo ficar com 0 pontos de vida, ele desaparece, não deixando forma física alguma para trás. O familiar reaparece após você conjurar esta magia novamente.\n\nEnquanto seu familiar estiver a até 30 metros [100 ft.] de você, é possível se comunicar telepaticamente com ele. Além disso, com uma ação, você pode ver através dos olhos dele e ouvir o que ele ouve até o começo de seu próximo turno, ganhando os benefícios de quaisquer sentidos especiais que ele tenha. Durante este tempo, você fica surdo e cego no que diz respeito aos seus próprios sentidos.\n\nCom uma ação, você pode dispensar seu familiar temporariamente. Ele desaparece em um bolsão dimensional onde aguarda a sua convocação. Se preferir, você pode dispensá-lo permanentemente. Enquanto o familiar estiver temporariamente dispensado, com uma ação você pode fazer com que ele reapareça em qualquer espaço desocupado a até 9 metros [30 ft.] de você.\n\nVocê não pode ter mais de um familiar por vez. Se conjurar esta magia quando já tiver um familiar, você apenas fará com que o seu familiar adote uma nova forma. Escolha uma das formas da lista acima. O seu familiar se transforma na criatura escolhida.\n\nPor fim, quando conjurar uma magia com alcance de toque, seu familiar pode lançar a magia como se ele mesmo a tivesse conjurado. Ele deve estar a até 30 metros [100 ft.] de você, e você deve usar a reação dele para lançar a magia quando a conjurar. Se a magia pedir uma jogada de ataque, use o seu modificador de ataque."
},
{
    "nome": "Criar ou Destruir Água",
    "nivel": 1,
    "classes": ["Clérigo", "Druida"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma gota de água, se for criá-la, ou alguns grãos de areia, se for destruí-la)",
    "duracao": "Instantânea",
    "descricao": "Você pode criar ou destruir água.\n\nCriar Água. Você cria até 40 litros de água limpa em um recipiente limpo, aberto e no alcance da magia. A água também pode cair como chuva em um cubo de 9 metros [30-foot cube] dentro do alcance da magia, extinguindo chamas expostas dentro dessa área.\n\nDestruir Água. Você destrói até 40 litros de água em um recipiente aberto dentro do alcance da magia. Ou você pode dispersar névoa em um cubo de 9 metros [30-foot cube] dentro do alcance da magia.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode criar ou destruir 40 litros de água adicionais, ou o tamanho do cubo aumenta em 1,5 metro [5 ft.] para cada círculo de magia acima do 1º."
},
{
    "nome": "Curar Ferimentos",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Clérigo", "Druida", "Patrulheiro", "Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Uma criatura tocada por você recupera um número de pontos de vida igual a 1d8 + o modificador do seu atributo de conjuração. Esta magia não tem efeito sobre mortos-vivos ou constructos.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, a cura aumenta em 1d8 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Hex",
    "nivel": 1,
    "classes": ["Bruxo"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "27m [90 ft.]",
    "componentes": "V S M (o olho petrificado de um tritão)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você transmite uma doença virulenta a uma criatura à sua vista e dentro do alcance da magia. Enquanto a magia durar, você causa 1d6 pontos de dano necrótico adicionais ao alvo sempre que atingi-lo com um ataque. Além disso, escolha um atributo ao conjurar esta magia. O alvo passa a ter desvantagem em testes de atributo feitos com o atributo escolhido.\n\nSe os pontos de vida do alvo forem reduzidos a 0 antes do final da magia, você pode usar sua ação bônus, em um turno subsequente seu, para amaldiçoar uma nova criatura.\n\nUma magia *Remover Maldição* conjurada no alvo encerra esta magia mais cedo.\n\nEm Níveis Superiores. Ao conjurar esta magia com um espaço de magia de 3º ou 4º círculo, você pode manter a sua concentração por até 8 horas. Ao usar um espaço de magia de 5º círculo ou maior, você pode manter a sua concentração na magia por até 24 horas."
},
{
    "nome": "Destruição Cauterizante",
    "nivel": 1,
    "classes": ["Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Na próxima vez que você acertar uma criatura com um ataque de arma de combate corpo a corpo durante a duração da magia, sua arma flameja com calor intenso, e o ataque causa 1d6 pontos de dano ígneo adicionais ao alvo, fazendo com que o alvo irrompa em chamas. No começo de cada um dos seus turnos, enquanto a magia durar, o alvo deve fazer uma salvaguarda de Constituição. Se falhar, sofre 1d6 pontos de dano ígneo. Em um sucesso, a magia se encerra. Se o alvo ou uma criatura no alcance de 1,5 metro [5 ft.] dele usar uma ação para apagar as chamas, ou se algum outro efeito extinguir as chamas (como o alvo ser submergido em água), a magia se encerra.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior; o dano aumenta em 1d6 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Destruição Colérica",
    "nivel": 1,
    "classes": ["Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Enquanto a magia durar, seu próximo acerto num ataque com uma arma de combate corpo a corpo, causa 1d6 pontos de dano psíquico adicionais. Além disso, se o alvo for uma criatura, ela deve fazer uma salvaguarda de Sabedoria ou fica amedrontada enquanto a magia durar. Com uma ação, a criatura pode fazer um teste de Sabedoria contra a CD para evitar sua magia, endurecendo a própria determinação e encerrando os efeitos da magia sobre ela."
},
{
    "nome": "Destruição Estrondosa",
    "nivel": 1,
    "classes": ["Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Enquanto a magia durar, na primeira vez que você acertar um ataque com uma arma de combate corpo a corpo, sua arma ressoa com trovões que são audíveis a 90 metros [300 ft.] de você e causam 2d6 pontos de dano trovejante adicionais. Além disso, se o alvo for uma criatura, ela deve ser bem-sucedida em uma salvaguarda de Força ou é empurrada 3 metros [10 ft.] para longe de você e fica caída."
},
{
    "nome": "Detectar Magia",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Clérigo", "Druida", "Feiticeiro", "Patrulheiro", "Mago", "Paladino"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Enquanto a magia durar, você pode sentir a presença de energia mágica a até 9 metros [30 ft.]. Caso seja bem-sucedido ao fazê-lo, você pode usar sua ação para ver uma tênue aura ao redor de qualquer criatura ou objeto que possuam energia mágica e que estejam visíveis na área, distinguindo, inclusive, a escola da magia, caso ela pertença a alguma.\n\nA magia pode atravessar a maioria das barreiras, sendo bloqueada, no entanto, por 30 centímetros [1 foot] de pedra, 2,5 centímetros [1 inch] de metal comum, uma folha fina de chumbo ou 1 metro [3 ft.] de madeira ou terra."
},
{
    "nome": "Detectar o Bem e o Mal",
    "nivel": 1,
    "classes": ["Clérigo", "Paladino"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Enquanto a magia durar, você pode sentir a presença e localização de uma criatura do tipo aberração, celestial, elemental, feérico, ínfero ou morto-vivo que encontre-se a até 9 metros [30 ft.] de distância. Da mesma forma, você sabe se existe um lugar ou objeto a até 9 metros [30 ft.] que tenha sido magicamente consagrado ou profanado.\n\nA magia pode atravessar a maioria das barreiras, sendo bloqueada, no entanto, por 30 centímetros [1 foot] de pedra, 2,5 centímetros [1 inch] de metal comum, uma folha fina de chumbo ou 1 metro [3 ft.] de madeira ou terra."
},
{
    "nome": "Detectar Veneno e Doença",
    "nivel": 1,
    "classes": ["Clérigo", "Druida", "Patrulheiro", "Paladino"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S M (uma folha de teixo)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Enquanto a magia durar, você pode sentir a presença e a localização de venenos, criaturas venenosas e doenças a até 9 metros [30 ft.] de distância. Você também pode identificar o tipo de veneno, criatura venenosa ou doença em cada caso.\n\nA magia pode atravessar a maioria das barreiras, sendo bloqueada, no entanto, por 30 centímetros [1 foot] de pedra, 2,5 centímetros [1 inch] de metal comum, uma folha fina de chumbo ou 1 metro [3 ft.] de madeira ou terra."
},
{
    "nome": "Disco Flutuante de Tenser",
    "nivel": 1,
    "classes": ["Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma gota de mercúrio)",
    "duracao": "Uma hora",
    "descricao": "Esta magia cria um disco circular horizontal feito de energia com 1 metro [3 ft.] de diâmetro e 2,5 centímetros [1 inch] de altura, que flutua a 1 metro [3 ft.] do chão em um espaço desocupado à sua escolha, à sua vista e no alcance da magia. O disco permanece enquanto a magia durar, e pode carregar até 225 quilos [500 pounds]. Se mais peso for colocado sobre ele, a magia se encerra e tudo o que está no disco cai.\n\nO disco é imóvel enquanto você estiver a até 6 metros [20 ft.] dele. Se você se mover para mais de 6 metros [20 ft.] de distância dele, o disco segue você, permanecendo a até 6 metros [20 ft.] de distância de você. Ele pode atravessar terrenos irregulares, subir ou descer escadas, declives e afins, mas não pode atravessar uma mudança de elevação de 3 metros [10 ft.] ou mais. Por exemplo, o disco não pode se mover através de um fosso de 3 metros [10 ft.] de profundidade, nem poderia deixar tal fosso se fosse criado no fundo dele.\n\nSe você se mover a mais de 30 metros [100 ft.] do disco (geralmente por ele não poder se mover através de um obstáculo para seguir você), a magia se encerra."
},
{
    "nome": "Disfarçar-se",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Feiticeiro", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Uma hora",
    "descricao": "Você faz com que você mesmo - incluindo suas roupas, armaduras, armas e outros pertences que esteja carregando - ganhe outra aparência, enquanto a magia durar ou até que você use sua ação para encerrá-la. Você pode parecer 30 centímetros [1 ft.] mais baixo ou mais alto, e parecer magro, gordo ou algo entre os dois. Você não pode alterar o seu tipo de corpo, portanto, deve adotar uma forma que tenha a mesma disposição básica de membros. No mais, a extensão da ilusão cabe a você.\n\nAs alterações feitas por esta magia não se sustentam diante de uma inspeção física. Por exemplo, se você usar esta magia para adicionar um chapéu à sua indumentária, objetos atravessam o chapéu, e quem o tocar não sentirá nada ou sentirá sua cabeça e cabelos. Se você usar esta magia para parecer mais magro do que é, alguém que estenda a mão para tocá-lo pode esbarrar em você enquanto ela ainda estiver, aparentemente, tocando o ar.\n\nPara descobrir que você está disfarçado, uma criatura pode usar a ação dela para inspecionar sua aparência, devendo ser bem-sucedida em um teste de Inteligência (Investigação) contra a CD para evitar sua magia."
},
{
    "nome": "Duelo Compelido",
    "nivel": 1,
    "classes": ["Paladino"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "9m [30 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você tenta compelir uma criatura a um duelo. Uma criatura à sua vista deve fazer uma salvaguarda de Sabedoria. Se falhar, a criatura é atraída até você, compelida por sua demanda divina. Enquanto a magia durar, ela tem desvantagem em jogadas de ataque contra criaturas que não sejam você, e deve fazer uma salvaguarda de Sabedoria sempre que tentar se mover para um espaço que esteja a mais de 9 metros [30 ft.] de distância de você; se for bem-sucedida na salvaguarda, a magia não restringe os movimentos dela nesse turno.\n\nA magia se encerra caso você ataque qualquer outra criatura, conjure uma magia que afete uma criatura hostil diferente do alvo, caso uma criatura amigável a você cause dano ou conjure uma magia ofensiva ao alvo, ou caso você encerre seu turno a mais de 9 metros [30 ft.] do alvo."
},
{
    "nome": "Égide",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma reação, que você executa quando é atingido por um ataque ou é alvo da magia Mísseis Mágicos",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Uma rodada",
    "descricao": "Uma barreira de força mágica invisível surge e protege você. Até o início de seu próximo turno, você terá +5 na CA, incluindo contra o ataque que disparou a reação, e você não sofre dano de Mísseis Mágicos."
},
{
    "nome": "Emaranhar",
    "nivel": 1,
    "classes": ["Druida"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Ervas daninhas e vinhas aderentes brotam do chão em um quadrado de 6 metros de lado [20-foot square] a partir de um ponto no alcance da magia. Enquanto a magia durar, as plantas transformam o solo da área em terreno difícil.\n\nQualquer criatura na área, que não for bem-sucedida em uma salvaguarda de Força, fica contida pelas plantas constritoras enquanto a magia durar. Uma criatura contida pelas plantas pode usar uma ação para fazer um teste de Força contra a CD para evitar sua magia. Em caso de sucesso, ela se liberta.\n\nQuando a magia termina, as plantas invocadas murcham."
},
{
    "nome": "Enfeitiçar Pessoa",
    "nivel": 1,
    "classes": ["Bardo", "Bruxo", "Druida", "Feiticeiro", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S",
    "duracao": "Uma hora",
    "descricao": "Você tenta enfeitiçar um humanoide à sua vista e dentro do alcance da magia. O alvo deve fazer uma salvaguarda de Sabedoria - com vantagem caso você ou seus companheiros estejam lutando contra ele. Se falhar, ele fica enfeitiçado por você enquanto a magia durar ou até que você ou seus companheiros lhe causem dano. A criatura enfeitiçada considera você como um conhecido amigável. Quando a magia termina, a criatura sabe que foi enfeitiçada por você.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode enfeitiçar uma criatura adicional para cada círculo do espaço acima do 1º. As criaturas devem estar a até 9 metros [30 ft.] umas das outras quando você as escolher como alvo."
},
{
    "nome": "Escrita Ilusória",
    "nivel": 1,
    "classes": ["Bardo", "Bruxo", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Toque",
    "componentes": "S M (uma tinta à base de chumbo no valor mínimo de 10 PO, a qual a magia consome)",
    "duracao": "10 dias",
    "descricao": "Você escreve em um pergaminho, papel ou algum material apropriado para escrita, infundindo-o com uma ilusão potente enquanto a magia durar.\n\nPara você e quaisquer criaturas escolhidas quando a magia é conjurada, a escrita parece com sua caligrafia normal e expressa qualquer significado de sua intenção quando o texto foi escrito. Para todos os demais, as palavras aparecem como se fossem escritas em um alfabeto desconhecido ou mágico, tornando-as ininteligíveis.\n\nSe preferir, você pode fazer com que a escrita tenha a aparência de um texto completamente diferente, escrito em outra caligrafia e idioma, apesar de ser necessário que você conheça o idioma.\n\nCaso a magia seja dissipada, tanto o texto original quanto o ilusório desaparecem.\n\nUma criatura com visão verdadeira pode ler a mensagem escondida."
},
{
    "nome": "Escudo da Fé",
    "nivel": 1,
    "classes": ["Clérigo", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um pequeno pergaminho contendo um fragmento de texto sagrado)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Um campo luminoso surge ao redor de uma criatura à sua escolha e no alcance da magia. A criatura ganha um bônus de +2 à CA enquanto esta magia durar."
},
{
    "nome": "Faca de Gelo",
    "nivel": 1,
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "S M (uma gota de água ou pedaço de gelo)",
    "duracao": "Instantânea",
    "descricao": "Você cria um fragmento de gelo e arremessa-o em uma criatura dentro do alcance. Faça um ataque à distância com magia contra o alvo. Se atingir, o alvo sofre 1d10 de dano perfurante. Atingindo ou errando, o fragmento explode. O alvo e cada criatura a até 1,5 metro [5 ft.] do ponto onde o gelo explodiu deve ser bem sucedido em salvaguarda de Destreza ou sofrerá 2d6 de dano de gelo.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, o dano de gelo aumenta em 1d6 para cada nível do espaço acima do 1º."
},
{
    "nome": "Falar com Animais",
    "nivel": 1,
    "classes": ["Bardo", "Druida", "Patrulheiro"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "10 minutos",
    "descricao": "Você adquire a habilidade de compreender e se comunicar verbalmente com feras enquanto a magia durar. O conhecimento e a consciência são limitados pela inteligência delas mas, no mínimo, são capazes de dar informação sobre localidades e monstros próximos, incluindo tudo o que notam ou notaram nas últimas 24 horas. Você pode tentar persuadir uma fera a lhe fazer um pequeno favor, a critério do DM."
},
{
    "nome": "Favor Divino",
    "nivel": 1,
    "classes": ["Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Sua oração o fortalece com o resplendor divino. Enquanto a magia durar, seus ataques com armas causam 1d4 pontos de dano radiante adicional em caso de acerto."
},
{
    "nome": "Fermentação Cáustica de Tasha",
    "nivel": 1,
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (linha de 9m [30 ft.])",
    "componentes": "V S M (um pouco de comida podre)",
    "duracao": "Concentração, Um minuto",
    "descricao": "Um fluxo de ácido emana de você em uma linha de 9 metros [30 ft.] de comprimento e 1,5 metro [5 ft.] de largura na direção que você escolher. Cada criatura na linha deve ter sucesso em uma Salvaguarda de Destreza ou ser coberta com ácido pela duração da magia ou até que uma criatura use sua ação para raspar ou lavar o ácido de si mesma ou de outra criatura. Uma criatura coberta de ácido sofre 2d4 de dano ácido no início de cada um dos turnos dela.\n\nEm Níveis Superiores. Quando você lança esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 2d4 para cada círculo do espaço acima do primeiro."
},
{
    "nome": "Fogo das Fadas",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Druida"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Todos os objetos em um cubo de 6 metros [20-foot cube] no alcance da magia se tornam delineados por uma luz azul, verde ou violeta (à sua escolha). Qualquer criatura que esteja na área quando a magia for conjurada também é delineada pela luz, caso falhe em uma salvaguarda de Destreza. Enquanto a magia durar, objetos e criaturas afetadas por ela emitem uma luz tênue, criando meia-luz em um raio de 3 metros [10-foot radius].\n\nQualquer jogada de ataque contra uma criatura ou objeto afetado tem vantagem, caso o atacante possa vê-los.\n\nObjetos e criaturas afetados não podem se beneficiar por estarem invisíveis."
},
{
    "nome": "Gargalhada Nefasta de Tasha",
    "nivel": 1,
    "classes": ["Bardo", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (tortas minúsculas e uma pena, que é agitada no ar)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você escolhe uma criatura à sua vista e no alcance da magia, que passa a perceber tudo como hilariantemente engraçado, sofrendo ataques de riso, caso seja afetada pela magia. O alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria ou fica caído, incapacitado e incapaz de se levantar enquanto a magia durar. Uma criatura de Inteligência 4 ou menos não pode ser afetada.\n\nAo final de cada turno, e em cada ocasião que sofrer dano, o alvo pode tentar outra salvaguarda de Sabedoria. O alvo tem vantagem se a salvaguarda for disparada por dano sofrido. Em caso de sucesso, a magia se encerra."
},
{
    "nome": "Golpe Constritor",
    "nivel": 1,
    "classes": ["Patrulheiro"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Na próxima vez que você acertar uma criatura com um ataque armado antes do final da magia, uma massa contorcida de vinhas espinhosas aparece no ponto de impacto. O alvo precisa fazer uma salvaguarda de Força. Se falhar, fica contido pelas vinhas mágicas, enquanto a magia durar; se for bem-sucedido, as vinhas murcham. Uma criatura de tamanho Grande ou maior tem vantagem nessa salvaguarda.\n\nEnquanto estiver contido, o alvo sofre 1d6 pontos de dano perfurante no começo de cada turno dele. Uma criatura contida pelas vinhas ou que possa tocá-las pode usar uma das próprias ações para fazer um teste de Força contra a CD para evitar a sua magia. Em caso de sucesso, o alvo fica livre.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Golpe de Zephyr",
    "nivel": 1,
    "classes": ["Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você se move como o vento. Até o fim da magia, seu movimento não provoca ataques de oportunidade. Uma vez até o fim da magia, você pode se dar vantagem em uma rolagem de ataque com arma no seu turno. Esse ataque infringe 1d8 de dano de força extra caso acerte. Não importa se acertar ou errar, sua velocidade de caminhada aumenta em 30 pés até o final desse turno."
},
{
    "nome": "Graxa",
    "nivel": 1,
    "classes": ["Artífice", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um pouco de torresmo ou manteiga)",
    "duracao": "1 minuto",
    "descricao": "Uma graxa escorregadia recobre uma área de 3 metros quadrados [10-foot square] de chão em um ponto dentro do alcance da magia, tornando-a terreno difícil enquanto esta durar.\n\nQuando a graxa aparece, cada criatura parada na área precisa ser bem-sucedida em uma salvaguarda de Destreza ou é considerada caída. Uma criatura que entre ou termine seu próprio turno na área também precisa ser bem-sucedida em uma salvaguarda de Destreza, ou fica caída."
},
{
    "nome": "Heroísmo",
    "nivel": 1,
    "classes": ["Bardo", "Paladino"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você toca uma criatura voluntária que torna-se imbuída de bravura. Enquanto a magia durar, o alvo está imune a ser amedrontado e ganha uma quantidade de pontos de vida temporários igual ao seu modificador do atributo de conjuração, no início de cada um dos turnos dela. Quando a magia terminar, o alvo perde quaisquer pontos de vida temporários remanescentes derivados desta magia."
},
{
    "nome": "Imagem Silenciosa",
    "nivel": 1,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um pouco de lã)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria a imagem de um objeto, criatura ou algum fenômeno visual que não seja maior do que um cubo de 4,5 metros [15-foot cube]. A imagem surge em um lugar no alcance da magia e permanece enquanto esta durar. A imagem é puramente visual; ela não é acompanhada de som, cheiro ou outros efeitos sensoriais.\n\nVocê pode usar sua ação para fazer a imagem se deslocar para qualquer lugar dentro do alcance da magia. À medida que a imagem muda de lugar, você pode alterar a aparência para que movimentos dela pareçam naturais."
},
{
    "nome": "Indentificar",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Mago"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Toque",
    "componentes": "V S M (uma pérola no valor mínimo de 100 PO e uma pena de coruja)",
    "duracao": "Instantânea",
    "descricao": "Escolha um objeto que você deve tocar durante a conjuração da magia. Se for um item mágico ou algum outro tipo de objeto imbuído de magia, você descobre as propriedades dele e como usá-las, se ele exige sintonização para ser usado e quantas cargas tem, caso as tenha. Você também descobre se alguma magia está afetando o objeto e que magia é essa."
},
{
    "nome": "Infligir Ferimentos",
    "nivel": 1,
    "classes": ["Clérigo"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Faça um ataque mágico corpo a corpo contra uma criatura ao seu alcance. Se acertar, o alvo sofre 3d10 pontos de dano necrótico.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d10 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Laço",
    "nivel": 1,
    "classes": ["Druida", "Patrulheiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "1 minuto",
    "alcance": "Toque",
    "componentes": "S M (7,5m [25 ft.] de corda que a magia consome)",
    "duracao": "8 horas",
    "descricao": "Ao conjurar esta magia, você usa a corda para criar um círculo com um raio de 1,5m [5-foot radius circle] no chão. Quando você termina a conjuração, a corda desaparece e o círculo torna-se uma armadilha mágica. Esta armadilha é quase invisível, exigindo uma verificação de Inteligência (Investigação) bem-sucedida contra sua CD de resistência mágica para ser discernida.\n\nA armadilha dispara quando uma criatura pequena, média ou grande se move para o chão no raio da magia. Essa criatura deve ter sucesso em salvaguarda de Destreza ou será magicamente presa no ar, deixando-a pendurada de cabeça para baixo a 0,9m [3 ft.] acima do chão."
},
{
    "nome": "Leque Cromático",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cone de 4,5m [15 ft.])",
    "componentes": "V S M (uma pitada de pó ou de areia colorida nas cores vermelha, amarela e azul)",
    "duracao": "Uma rodada",
    "descricao": "Uma deslumbrante variedade de luzes ofuscantes e coloridas projeta-se da sua mão. Jogue 6d10; o resultado será a quantidade total de pontos de vida das criaturas que esta magia pode afetar. Criaturas em um cone de 4,5 metros [15-foot cone] com origem em você são afetadas em ordem crescente de seus pontos de vida atuais (ignorando criaturas inconscientes e criaturas que não possam enxergar)."
},
{
    "nome": "Mãos Flamejantes",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cone de 4,5m [15 ft.])",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Enquanto você mantiver suas mãos com os polegares tocando um ao outro e os demais dedos abertos, uma fina camada de chamas parte da ponta de seus dedos estendidos. Cada criatura dentro de um cone de 4,5 metros [15-foot cone] deve fazer uma salvaguarda de Destreza. Se falhar, sofre 3d6 pontos de dano, ou metade do dano em caso de sucesso."
},
{
    "nome": "Marca do Caçador",
    "nivel": 1,
    "classes": ["Patrulheiro"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "27m [90 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Escolha uma criatura à sua vista e no alcance da magia, marcando-a misticamente como sua presa. Enquanto a magia durar, você causa 1d6 pontos de dano adicionais no alvo sempre que o atingir com um ataque armado, e tem vantagem em qualquer teste de Sabedoria (Percepção) ou Sabedoria (Sobrevivência) feito para encontrá-lo. Se os pontos de vida do alvo forem reduzidos a 0 antes desta magia se encerrar, você pode usar uma ação bônus em um turno subsequente seu para marcar uma nova criatura."
},
{
    "nome": "Mísseis Mágicos",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você cria três dardos brilhantes feitos de pura energia mágica. Cada dardo acerta uma criatura à sua escolha, à sua vista e no alcance da magia. Um dardo causa 1d4+1 pontos de dano energético no alvo. Os dardos acertam ao mesmo tempo, e você pode direcioná-los para uma mesma criatura ou várias.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você cria um dardo a mais para cada círculo do espaço acima do 1º."
},
{
    "nome": "Névoa Obscurecente",
    "nivel": 1,
    "classes": ["Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você cria uma esfera de nevoeiro com raio de 6 metros [20-foot radius], centrado em um ponto no alcance da magia. A esfera se alastra, contornando os cantos e a área afetada fica totalmente obscurecida. Ela permanece enquanto a magia durar ou até que um vento de velocidade moderada (de pelo menos 15 quilômetros por hora) ou maior a disperse.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o raio da esfera aumenta em 6 metros para cada círculo do espaço acima do 1º."
},
{
    "nome": "Onda Trovejante",
    "nivel": 1,
    "classes": ["Bardo", "Druida", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cubo de 4,5m [15 ft.])",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Uma onda de força trovejante varre tudo a partir de você. Cada criatura em um cubo de 4,5 metros [15-foot cube] originando em você deve fazer uma salvaguarda de Constituição. Se falhar, sofre 2d8 pontos de dano trovejante e é empurrada 3 metros [10 ft.] para longe de você. Em caso de sucesso, a criatura sofre metade do dano e não é empurrada.\n\nAlém disso, objetos soltos que estejam completamente dentro da área de efeito são automaticamente empurrados 3 metros [10 ft.] para longe de você, e a magia emite um estrondo trovejante audível a até 90 metros [300 ft.].\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Orbe Cromática",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S M (um diamante cujo valor mínimo seja de 50 PO)",
    "duracao": "Instantânea",
    "descricao": "Você lança uma esfera de energia de 10 centímetros de diâmetro [4-inch-diameter sphere] em uma criatura à sua vista e que esteja dentro do alcance da magia. Você escolhe o tipo de orbe: ácido, elétrico, ígneo, gélido, venenoso ou trovejante, e então faz um ataque mágico à distância contra o alvo. Se acertar, o alvo sofre 3d8 pontos de dano do tipo que você escolheu.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Palavra Curativa",
    "nivel": 1,
    "classes": ["Bardo", "Clérigo", "Druida"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Escolha uma criatura à sua vista e no alcance da magia. Ela recupera uma quantidade de pontos de vida igual a 1d4 + seu modificador de atributo de conjuração. Esta magia não tem efeito sobre mortos-vivos ou constructos.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, a cura aumenta em 1d4 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Passos Largos",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Druida", "Patrulheiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (uma pitada de poeira)",
    "duracao": "Uma hora",
    "descricao": "Você toca uma criatura. O deslocamento do alvo aumenta em 3 metros [10 ft.] enquanto a magia durar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode enfeitiçar uma criatura adicional para cada círculo do espaço acima do 1º."
},
{
    "nome": "Perdição",
    "nivel": 1,
    "classes": ["Bardo", "Clérigo"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma gota de sangue)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Até três criaturas, à sua escolha, à sua vista e que estejam dentro do alcance da magia, devem realizar salvaguardas de Carisma. Enquanto a magia durar, sempre que um alvo que falhar nessa salvaguarda fizer uma jogada de ataque ou uma salvaguarda, ele deverá jogar 1d4 e subtrair o número obtido do resultado da jogada de ataque ou salvaguarda.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você pode enfeitiçar uma criatura adicional para cada círculo do espaço acima do 1º."
},
{
    "nome": "Proteção Contra o Bem e o Mal",
    "nivel": 1,
    "classes": ["Bruxo", "Clérigo", "Mago", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (água benta ou pó de prata e ferro, que a magia consome)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Enquanto a magia durar, uma criatura voluntária tocada por você passa a ter proteção contra certos tipos de criaturas: aberrações, celestiais, elementais, feéricos, ínferos e mortos-vivos.\n\nA proteção concede vários benefícios. Criaturas destes tipos têm desvantagem nas jogadas de ataque contra o alvo. O alvo não pode ser amedrontado, enfeitiçado ou possuído por elas. Se o alvo já estiver amedrontado, enfeitiçado ou possuído por estas criaturas, ele terá vantagem sobre qualquer nova salvaguarda contra o efeito relevante."
},
{
    "nome": "Purificar Alimentos e Bebidas",
    "nivel": 1,
    "classes": ["Artífice", "Clérigo", "Druida", "Paladino"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "3m [10 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Toda a comida e bebida não-mágica dentro de uma esfera de 1,5 metro de raio [5-foot radius] centrada em um ponto à sua escolha, no alcance da magia, é purificada e tornada livre de venenos e doenças."
},
{
    "nome": "Queda Suave",
    "nivel": 1,
    "classes": ["Artífice", "Bardo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma reação, executada quando você ou uma criatura a 18 metros [60 ft.] do seu alcance cai",
    "alcance": "18m [60 ft.]",
    "componentes": "V M (uma pena pequena ou penugem)",
    "duracao": "1 minuto",
    "descricao": "Escolha até cinco criaturas no alcance da magia e que estejam caindo. A velocidade de queda de uma criatura é reduzida para 18 metros [60 ft.] por rodada enquanto a magia durar. Se a criatura pousar antes do fim da magia, não sofrerá dano por queda, podendo aterrissar em pé, e a magia se encerra para ela."
},
{
    "nome": "Raio de Bruxa",
    "nivel": 1,
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um galho de uma árvore que foi atingido por um raio)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você lança um raio de energia azul crepitante em direção a uma criatura no alcance da magia, formando um arco elétrico contínuo entre você e o alvo. Faça um ataque mágico a distância contra o alvo. Se acertar, o alvo sofre 1d12 pontos de dano elétrico, e em cada um dos seus turnos, enquanto a magia durar, você pode usar uma ação para causar 1d12 pontos de dano elétrico no alvo automaticamente. A magia se encerra se você usar a sua ação para fazer qualquer outra coisa. A magia também se encerra se o alvo sair do alcance da magia ou tiver cobertura total.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d12 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Raio de Caos",
    "nivel": 1,
    "classes": ["Feiticeiro"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você lança uma massa ondulante de energia caótica em uma criatura no alcance. Faça um ataque a distância com magia contra o alvo. Se atingir, o alvo leva 2d8 + 1d6 de dano. Escolha um dos d8s. O número rolado nesse dado determina o tipo de dano do ataque, como mostrado abaixo.\n\nTipo de Dano:\n1 - Ácido\n2 - Gelo\n3 - Fogo\n4 - Energia\n5 - Elétrico\n6 - Veneno\n7 - Psíquico\n8 - Trovejante\n\nSe você rolar o mesmo número em ambos os d8s, a energia caótica salta do alvo para uma criatura diferente a sua escolha dentro de 9m [30 ft.] de distância. Faça uma nova rolagem de ataque contra o novo alvo, e faça uma nova rolagem de danos, o que pode fazer com que a energia caótica salte novamente.\n\nUma criatura pode ser alvo dessa massa de energia caótica somente uma vez.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1º."
},
{
    "nome": "Raio Guia",
    "nivel": 1,
    "classes": ["Clérigo"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Uma rodada",
    "descricao": "Um lampejo de luz dispara em direção a uma criatura à sua escolha e dentro do alcance da magia. Faça um ataque mágico à distância contra o alvo. Se acertar, o alvo sofre 4d6 pontos de dano radiante, e a próxima jogada de ataque feita contra ele, antes do final do seu próximo turno, tem vantagem graças à meia-luz mística brilhando no alvo.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Raio Nauseante",
    "nivel": 1,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Um raio esverdeado de energia enojante irrompe na direção de uma criatura no alcance da magia. Faça um ataque mágico à distância contra o alvo. Se acertar, o alvo sofre 2d8 pontos de dano venenoso e deve fazer uma salvaguarda de Constituição. Se falhar, o alvo também estará envenenado até o final do seu próximo turno.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Repreensão Diabólica",
    "nivel": 1,
    "classes": ["Bruxo"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma reação, que você executa ao sofrer dano de uma criatura à sua vista e que esteja a até 18 metros [60 ft.] de você",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você aponta o seu dedo e a criatura que lhe causou dano é momentaneamente cercada por chamas infernais. Ela deve fazer uma salvaguarda de Destreza. Se falhar, sofre 2d10 pontos de dano ígneo, ou metade do dano em caso de sucesso.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d10 para cada círculo do espaço acima do 1º."
},
{
    "nome": "Retirada Acelerada",
    "nivel": 1,
    "classes": ["Artífice", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Esta magia permite que você se mova em um ritmo incrível.\n\nAo conjurá-la, e depois com uma ação bônus em cada um dos seus turnos até a magia se encerrar, você pode executar a ação Correr."
},
{
    "nome": "Salto",
    "nivel": 1,
    "classes": ["Artífice", "Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (uma perna traseira de um gafanhoto)",
    "duracao": "1 minuto",
    "descricao": "Você toca uma criatura. Enquanto a magia durar, a distância de salto da criatura é triplicada."
},
{
    "nome": "Santuário",
    "nivel": 1,
    "classes": ["Artífice", "Clérigo"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um pequeno espelho de prata)",
    "duracao": "1 minuto",
    "descricao": "Você protege uma criatura que esteja dentro do alcance da magia contra ataques. Enquanto a magia durar, qualquer criatura que tenha a criatura protegida como alvo de um ataque ou de uma magia prejudicial deve antes fazer uma salvaguarda de Sabedoria. Se falhar, o atacante deve escolher outro alvo ou perderá o ataque ou magia. Esta magia não garante ao alvo proteção contra efeitos de área, como a explosão de uma bola de fogo.\n\nSe o alvo protegido fizer um ataque ou conjurar uma magia que afete uma criatura inimiga, a magia se encerra."
},
{
    "nome": "Saraivada de Espinhos",
    "nivel": 1,
    "classes": ["Patrulheiro"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Na próxima vez que você acertar uma criatura com um ataque feito com uma arma de combate à distância antes do fim da magia, esta magia criará uma chuva de espinhos que brota da sua arma ou munição. Além de sofrer os efeitos normais do ataque, tanto o alvo quanto cada criatura a até 1,5 metro [5 ft.] dele deve fazer uma salvaguarda de Destreza. Se falhar, sofre 1d10 pontos de dano perfurante, ou metade do dano, em caso de sucesso.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d10 para cada círculo do espaço acima do 1º (até um máximo de 6d10)."
},
{
    "nome": "Servo Invisível",
    "nivel": 1,
    "classes": ["Bardo", "Bruxo", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um pedaço de barbante e uma lasca de madeira)",
    "duracao": "Uma hora",
    "descricao": "Esta magia cria uma força invisível, irracional e amorfa que cumpre tarefas simples dadas por você. O servo surge em um espaço desocupado sobre o solo no alcance da magia. Ele tem CA 10, 1 ponto de vida, Força 2 e não pode atacar. Se ele cair para 0 ponto de vida, a magia se encerra.\n\nUma vez em cada um dos seus turnos, com uma ação bônus, você pode comandar mentalmente o servo a se mover até 4,5 metros [15 ft.] e interagir com um objeto. O servo pode executar tarefas simples que um servo humano poderia fazer, como buscar coisas, limpar, remendar, dobrar roupas, acender fogo, servir comida e servir vinho. Uma vez dado o comando, o servo faz a tarefa da melhor forma, dentro de suas capacidades, até completá-la e, então, aguarda seu próximo comando.\n\nSe for determinado que o servo faça algo que o moveria além de 18 metros [60 ft.] de distância de você, a magia se encerra."
},
{
    "nome": "Sono",
    "nivel": 1,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S M (uma pitada de areia fina, pétalas de rosa, ou um grilo)",
    "duracao": "1 minuto",
    "descricao": "Esta magia coloca criaturas em um sono mágico. Jogue 5d8; o resultado equivale a quantos pontos de vida de criaturas esta magia pode afetar. As criaturas que estiverem dentro de um raio de 6 metros [20-foot radius] a partir de um ponto à sua escolha, são afetadas em ordem ascendente de pontos de vida atuais (ignorando criaturas inconscientes). Mortos-vivos e criaturas imunes a serem enfeitiçadas não são afetadas por esta magia.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, jogue 2d8 adicionais a cada espaço acima do 1º círculo."
  },
  {
    "nome": "Sussurros Dissonantes",
    "nivel": 1,
    "classes": ["Bardo"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você sussurra uma melodia dissonante que apenas uma criatura à sua escolha e dentro do alcance é capaz de ouvir, afligindo-a com terrível dor. O alvo deve fazer uma salvaguarda de Sabedoria. Se falhar, sofre 3d6 pontos de dano psíquico, devendo usar a própria reação imediatamente, caso esteja disponível, para se distanciar de você tanto quanto o deslocamento dele permita.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 1º."
  },
  {
    "nome": "Tremor de Terra",
    "nivel": 1,
    "classes": ["Bardo", "Druida", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "3m [10 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você provoca um tremor no solo num raio de 3m [10-foot radius]. Cada criatura diferente de você na área deve realizar salvaguarda de Destreza. Se falhar, uma criatura sofre 1d6 de dano contundente e fica caída no chão. Se o solo na área for de terra ou pedra solta, ele se torna terreno difícil até ser limpo.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 2º círculo ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1º."
  },
  {
    "nome": "Vínculo com a Besta",
    "nivel": 1,
    "classes": ["Druida", "Patrulheiro"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um tufo de pelos envolto por um pano)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você estabelece um elo telepático com uma besta que você tocar que seja amigável a você ou que esteja enfeitiçada por você. A magia falha se o valor de Inteligência da besta for 4 ou maior. Através do elo, a besta pode compreender suas mensagens telepáticas para ela e pode comunicar telepaticamente emoções e conceitos simples de volta para você."
  },
  {
    "nome": "Vitalidade Vazia",
    "nivel": 1,
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S M (uma pequena quantidade de álcool ou bebidas alcoólica destilada)",
    "duracao": "Uma hora",
    "descricao": "Você instila em si mesmo um arremedo necromântico de vida, ganhando 1d4+4 pontos de vida temporários enquanto a magia durar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 2º círculo ou superior, você ganha 5 pontos de vida temporários para cada círculo do espaço acima do 1º."
  }
]