magias_nivel_6 = [
    {
    "nome": "Aliado Extraplanar",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você suplica a uma entidade extraplanar por ajuda, invocando um ser de poder cósmico. A entidade envia um celestial, elemental ou ínfero leal a ela, que aparece em um espaço desocupado. O serviço que a criatura oferece pode ser variado e sujeito a pagamento. Tarefas simples podem exigir 100 PO por minuto, enquanto tarefas mais complexas exigem pagamento em ouro ou tesouros. Após a tarefa, a criatura retorna ao plano de origem. A criatura conta como um membro do grupo e recebe experiência."
  },
  {
    "nome": "Banquete de Heróis",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Clérigo", "Druida"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma tigela com gema de 1.000 PO, consumida)",
    "duracao": "Instantânea",
    "descricao": "Você cria um banquete magnífico que leva 1 hora para ser consumido, proporcionando curas e benefícios a até doze criaturas. As criaturas ficam imunes a veneno e medo, fazem todas as salvaguardas de Sabedoria com vantagem, e ganham 2d10 pontos de vida máximos, durando 24 horas. Efeitos benéficos aparecem após a hora."
  },
  {
    "nome": "Barreira de Lâminas",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você cria uma barreira de lâminas afiadas feitas de energia mágica. A barreira pode ser reta ou circular e oferece 3/4 de cobertura para criaturas atrás dela. As criaturas que entrarem ou começarem seu turno na barreira devem fazer uma salvaguarda de Destreza, sofrendo 6d10 de dano cortante em caso de falha."
  },
  {
    "nome": "Bosque de Druida",
    "nivel": 6,
    "escola": "Abjuração",
    "classes": ["Druida"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Toque",
    "componentes": "V S M (visco colhido com foice dourada sob a lua cheia)",
    "duracao": "24 horas",
    "descricao": "Você invoca os espíritos da natureza para proteger uma área ao ar livre. A área pode ser pequena ou grande e contém névoa espessa, matagal que prende criaturas e patrulheiros animados que defendem a área contra intrusos. O efeito pode incluir vento constante ou espinhos mágicos. Criaturas imunes aos efeitos veem a área de forma diferente."
  },
  {
    "nome": "Caminhar no Vento",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Druida"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (fogo e água benta)",
    "duracao": "8 horas",
    "descricao": "Você e até dez criaturas voluntárias assumem a forma de nuvem, com voo de 90 metros [300 ft.] e resistência a dano por armas não mágicas. As únicas ações possíveis são correr ou reverter para a forma normal, o que demora 1 minuto. Se uma criatura voando cair, ela desce 18 metros por rodada até aterrissar."
  },
  {
    "nome": "Círculo da Morte",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (pó de pérola negra, mínimo 500 PO)",
    "duracao": "Instantânea",
    "descricao": "Uma esfera de energia negativa emite ondulações de necróticos em um raio de 18 metros. As criaturas na área devem fazer uma salvaguarda de Constituição. Se falharem, sofrem 8d6 de dano necrótico, ou metade em caso de sucesso. O dano aumenta em 2d6 para cada nível acima do 6º."
  },
  {
    "nome": "Contingência",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Pessoal",
    "componentes": "V S M (estatueta de marfim com pedras preciosas de 1.500 PO)",
    "duracao": "10 dias",
    "descricao": "Escolha uma magia de 5º círculo ou inferior para ser acionada quando uma condição específica ocorrer. A magia é conjurada durante a Contingência, mas não é ativada até que a condição especificada aconteça. A magia contingente afeta apenas você e entra em ação automaticamente."
  },
  {
    "nome": "Convocação Instantânea de Drawmij",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Toque",
    "componentes": "V S M (safira de 1.000 PO)",
    "duracao": "Até ser dissipada",
    "descricao": "Você marca um objeto e pode trazê-lo até você a qualquer momento, dizendo seu nome e esmagando a safira. Se o objeto for detido por outra criatura, você descobre sua identidade e localização aproximada."
  },
  {
    "nome": "Corrente de Relâmpagos",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (pelo, âmbar, cristal e três alfinetes de prata)",
    "duracao": "Instantânea",
    "descricao": "Você cria um raio de eletricidade que salta para um alvo e depois para até três outros alvos. Cada alvo deve fazer uma salvaguarda de Constituição. Se falhar, sofre 10d8 de dano elétrico. O dano aumenta em 2d6 para cada círculo acima do 6º."
  },
  {
    "nome": "Criar Homúnculo",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma hora",
    "alcance": "Toque",
    "componentes": "V S M (argila, cinzas e raiz de mandrágora com adaga de 1.000 PO)",
    "duracao": "Instantânea",
    "descricao": "Você cria um homúnculo que se torna seu fiel companheiro. A criação exige sacrifício, com você recebendo 2d4 de dano. O homúnculo recebe benefícios de cura através de seu sangue e morre se você morrer. Você pode ter apenas um homúnculo por vez."
  },
  {
    "nome": "Criar Mortos-Vivos",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Clérigo", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "3m [10 ft.]",
    "componentes": "V S M (pote com terra de cova e ônix de 150 PO por cadáver)",
    "duracao": "Instantânea",
    "descricao": "Você anima até três cadáveres de humanoides como carniçais sob seu controle. As criaturas obedece seus comandos e podem ser controladas mentalmente enquanto estiverem a 36 metros de você. A animação dura 24 horas e deve ser renovada para manter o controle."
  },
  {
    "nome": "Cura Completa",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Clérigo", "Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Uma onda de energia positiva preenche uma criatura, curando 70 pontos de vida. A magia também remove cegueira, surdez e doenças. Não afeta constructos ou mortos-vivos. O dano aumenta com o uso de espaços de magia superiores."
  },
  {
    "nome": "Dança Irresistível de Otto",
    "nivel": 6,
    "escola": "Encantamento",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "O alvo começa a dançar comicamente, balançando-se e se contorcendo enquanto durar a magia. Criaturas que não podem ser enfeitiçadas são imunes. A criatura deve usar todo o movimento para dançar sem sair do espaço, além de ter desvantagem em salvaguardas de Destreza e jogadas de ataque. Outras criaturas têm vantagem nas jogadas de ataque contra ela. Usando uma ação, a criatura pode fazer uma salvaguarda de Sabedoria para recuperar o controle. Caso contrário, ela continua dançando até o fim da magia."
  },
  {
    "nome": "De Carne Para Pedra",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (uma pitada de limo, água e terra)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você tenta transformar a carne de uma criatura em pedra. A criatura deve fazer uma salvaguarda de Constituição. Se falhar, a carne começa a endurecer. Após três falhas, a criatura é petrificada. Se a criatura for quebrada enquanto petrificada, sofrerá deformações. Para reverter, é necessária a magia de Ressurreição Verdadeira ou Desejo."
  },
  {
    "nome": "Desintegrar",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (uma magnetita e uma pitada de pó)",
    "duracao": "Instantânea",
    "descricao": "Um raio verde atinge uma criatura ou objeto, que deve fazer uma salvaguarda de Destreza. Se falhar, sofre 10d6+40 pontos de dano energético e é desintegrada se seus pontos de vida chegarem a 0. Criaturas desintegradas e tudo o que carregam, exceto itens mágicos, são reduzidos a poeira. Esta magia também afeta objetos não mágicos de tamanho Grande ou menor."
  },
  {
    "nome": "Disfarce Sobrenatural de Tasha",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V S M (um objeto entalhado com o símbolo dos Planos Exteriores)",
    "duracao": "Concentração, 1 minuto",
    "descricao": "Você se transforma, adquirindo imunidade a certos tipos de dano e condições, dependendo do plano que escolheu. Você ganha voo de 12m, +2 na CA, seus ataques com armas se tornam mágicos e você pode atacar duas vezes ao fazer a ação de Ataque. Se já tiver Ataque Extra, esse benefício não se aplica."
  },
  {
    "nome": "Dispersão",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "30 segundos",
    "alcance": "9m (30 ft.)",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você teletransporta até cinco criaturas que pode ver dentro do alcance para um espaço desocupado de até 36m (120 ft.) de você. As criaturas devem fazer uma salvaguarda de Sabedoria para resistir. A magia afeta apenas criaturas que falharem na resistência."
  },
  {
    "nome": "Encontrar o Caminho",
    "nivel": 6,
    "escola": "Adivinhação",
    "classes": ["Bardo", "Clérigo", "Druida"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Pessoal",
    "componentes": "V S M (um conjunto de ferramentas divinatórias e um objeto da localidade)",
    "duracao": "Concentração, Até 1 dia",
    "descricao": "Você encontra o caminho mais curto e direto até uma localidade específica que lhe seja familiar no mesmo plano. A magia informa a distância e direção até o destino e garante que, ao enfrentar escolhas de caminho, você sabe qual é o mais direto e rápido."
  },
  {
    "nome": "Esfera Congelante de Otiluke",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "90m (300 ft.)",
    "componentes": "V S M (uma pequena esfera de cristal)",
    "duracao": "Instantânea",
    "descricao": "Você dispara uma esfera de gelo que explode em uma área de 18m de raio, causando 10d6 de dano gélido a criaturas que falharem na salvaguarda de Constituição. Se atingir água ou líquido, ele congela por 1 minuto. Você também pode arremessar a esfera manualmente, causando o mesmo efeito."
  },
  {
    "nome": "Gaiola da Alma",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Reação (quando um humanoide morre dentro de 18m)",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (uma pequena jaula de prata)",
    "duracao": "8 horas",
    "descricao": "Você aprisiona a alma de um humanoide que morre perto de você em uma gaiola. Enquanto a alma estiver presa, você pode usá-la para drenar vida, fazer perguntas telepáticas, emprestar perícia ou criar um sensor invisível. A alma é libertada após seis usos ou ao término da magia."
  },
  {
    "nome": "Globo de Invulnerabilidade",
    "nivel": 6,
    "escola": "Abjuração",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 3m)",
    "componentes": "V S M (uma conta de cristal ou vidro)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Uma barreira de 3m de raio surge ao seu redor, bloqueando magias de 5º círculo ou inferior de afetar você. Magias de 6º ou superior podem passar pela barreira, mas não terão efeito sobre você."
  },
  {
    "nome": "Ilusão Programada",
    "nivel": 6,
    "escola": "Ilusão",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (um pouco de lã e pó de jade)",
    "duracao": "Até ser dissipada",
    "descricao": "Você cria uma ilusão de um objeto, criatura ou fenômeno que será ativada quando uma condição específica ocorrer. A ilusão é invisível até ser acionada e pode durar até 5 minutos. Ao ser ativada, ela age conforme a descrição fornecida. Pode ser reativada após 10 minutos."
  },
  {
    "nome": "Invocar Corruptor",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m (90 ft.)",
    "componentes": "V S M (sangue humanóide em frasco de rubi)",
    "duracao": "Concentração, Uma hora",
    "descricao": "Você convoca um espírito corruptivo, escolhendo entre Diabo, Demônio ou Yugoloth. A criatura obedece a seus comandos, compartilhando sua iniciativa e realizando a ação de Esquiva caso não seja comandada. A criatura desaparece ao atingir 0 pontos de vida ou ao fim da magia."
  },
  {
    "nome": "Invocar Feérico",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Bruxo", "Druida"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "27m (90 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 hora",
    "descricao": "Você invoca uma criatura feérica para lutar por você. Ela tem forma líquida, controle mental e capacidade de transformação. O feérico pode ser qualquer espírito ou criatura feérica, com habilidades especiais de combate e proteção."
  },
  {
    "nome": "Manto de Chamas",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Chamas envolvem seu corpo, emitindo luz em um raio de 9m e penumbra em 9m adicionais. As chamas não causam dano a você. Você ganha imunidade a dano de fogo e resistência a dano de gelo. Qualquer criatura que se mover a até 1,5m de você pela primeira vez em um turno ou terminar o turno ali, sofre 1d10 de dano de fogo. Você pode usar uma ação para criar uma linha de fogo de 4,5m que causa 4d8 de dano de fogo (salvaguarda de Destreza para metade)."
  },
  {
    "nome": "Manto de Gelo",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Gelo cobre seu corpo, tornando você imune a dano de gelo e resistente a dano de fogo. O solo em um raio de 3m ao seu redor torna-se terreno difícil. Você pode criar um cone de 4,5m de vento gélido que causa 4d6 de dano de gelo (salvaguarda de Constituição para metade). Se a criatura falhar, seu deslocamento é reduzido à metade até o próximo turno."
  },
  {
    "nome": "Manto de Pedra",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Pedaços de pedra cobrem seu corpo. Você ganha resistência a dano contundente, cortante e perfurante de armas não-mágicas. Você pode criar um terremoto em um raio de 4,5m, fazendo as criaturas falharem em uma salvaguarda de Destreza ou caírem no chão. Você pode mover-se através de terreno difícil de terra ou rocha sem custo adicional e atravessar terra sólida ou rocha, mas não pode terminar o movimento nela."
  },
  {
    "nome": "Manto de Vento",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Ventos giram ao seu redor, dando desvantagem em ataques à distância contra você. Você ganha voo com deslocamento de 18m. Você pode criar um cubo de ventos rodopiantes que causa 2d10 de dano contundente (salvaguarda de Força para metade). Criaturas Grandes ou menores falham na resistência e são empurradas até 3m para longe do centro do cubo."
  },
  {
    "nome": "Mau Olhado",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Seus olhos se tornam vazios, imbuídos com poder aterrorizante. Escolha uma criatura à vista a até 18m que deve fazer uma salvaguarda de Sabedoria. Se falhar, ela sofre um dos efeitos: Adormecer (fica inconsciente), Apavorar (afasta-se de você), ou Adoecer (desvantagem nas jogadas de ataque e testes). Você pode afetar uma nova criatura a cada turno, sem repetir a mesma que tenha passado na salvaguarda."
  },
  {
    "nome": "Moléstia",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você transmite uma doença virulenta a uma criatura à vista. O alvo deve fazer uma salvaguarda de Constituição. Se falhar, sofre 14d6 de dano necrótico (metade se bem-sucedido). Os pontos de vida máximos do alvo são reduzidos em uma quantidade equivalente ao dano sofrido. Esse efeito dura 1 hora, a menos que removido por um efeito que cure doenças."
  },
  {
    "nome": "Mover Terra",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m",
    "componentes": "V S M (uma lâmina de ferro e uma pequena sacola contendo uma mistura de solos - argila, terra e areia)",
    "duracao": "Concentração, Até 2 horas",
    "descricao": "Escolha uma área de terreno de até 12m de lado. Você pode remodelar terra, areia ou argila, aumentando ou diminuindo elevações, criando fossos, ou erguendo pilares. A transformação leva 10 minutos para ser concluída. Criaturas não ficam presas durante o processo, mas o terreno pode se tornar instável, afetando estruturas e plantas."
  },
  {
    "nome": "Muralha de Espinhos",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m",
    "componentes": "V S M (um punhado de espinhos)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria uma muralha de arbustos com espinhos resistentes e flexíveis. A muralha pode ter até 18m de comprimento, 3m de altura e 1,5m de espessura. Criaturas dentro da muralha ao aparecerem devem fazer uma salvaguarda de Destreza (7d8 de dano cortante). Criaturas podem atravessar a muralha com maior custo de movimento e dano adicional."
  },
  {
    "nome": "Muralha de Gelo",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m",
    "componentes": "V S M (um pequeno pedaço de quartzo)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria uma muralha de gelo com até 3m de raio ou 10m de comprimento. A muralha tem 30cm de espessura e pode ser moldada em um domo ou superfície plana. Quando surge, a muralha causa 10d6 de dano gélido (salvaguarda de Destreza para metade). A muralha pode ser danificada e quebrada, com criaturas sendo empurradas ou sofrendo dano se passarem pela camada de ar gélido."
  },
  {
    "nome": "Ossos da Terra",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você faz até seis pilares de pedra emergirem do solo. Cada pilar tem 1,5m de diâmetro e até 9m de altura. Os pilares causam 6d6 de dano contundente se uma criatura estiver sob eles e falhar na salvaguarda de Destreza. Se o pilar for destruído, cria uma área de terreno difícil de 3m de raio."
  },
  {
    "nome": "Palavra de Regresso",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "1,5m",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você e até 5 criaturas voluntárias a até 1,5m de você são teleportadas para um santuário previamente designado. O santuário deve ser um local dedicado à sua divindade, e a magia falha se não houver um santuário preparado."
  },
  {
    "nome": "Portais Arcanos",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "150m",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria dois portais interligados, que permanecem abertos enquanto a magia durar. Escolha dois pontos à sua vista, um a até 3m de você e outro a até 150m. Criaturas podem atravessar os portais, que são opacos e bloqueiam a visão através deles."
  },
  {
    "nome": "Prisão Mental",
    "nivel": 6,
    "escola": "Ilusão",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m",
    "componentes": "S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você tenta prender uma criatura dentro de uma célula ilusória que só ela percebe. Uma criatura que você pode ver dentro do alcance deve fazer uma salvaguarda de Inteligência. Se falhar, a criatura sofre 5d10 de dano psíquico e fica presa dentro da ilusão. Se for bem-sucedida, a criatura sofre 5d10 de dano psíquico, mas a magia termina. O alvo não pode ver ou ouvir qualquer coisa para além da ilusão e fica impedido de se mover para fora dela. Se o alvo interagir fisicamente com a ilusão, recebe 10d10 de dano psíquico e a magia termina."
  },
  {
    "nome": "Proibição",
    "nivel": 6,
    "escola": "Abjuração",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "10 minutos ou Ritual",
    "alcance": "Toque",
    "componentes": "V S M (uma aspersão de água benta, um incenso raro e rubi em pó no valor mínimo de 1.000 PO)",
    "duracao": "1 dia",
    "descricao": "Você cria uma defesa contra viagem mágica que protege uma área de até 3.500 metros quadrados e até 9 metros de altura. Nenhuma criatura pode se teleportar para dentro dessa área ou usar portais mágicos. Além disso, você pode escolher um ou mais tipos de criaturas que sofrerão 5d10 pontos de dano radiante ou necrótico quando entrarem na área. Uma senha dita em voz alta impede o dano contra quem a proferir."
  },
  {
    "nome": "Proteção Primordial",
    "nivel": 6,
    "escola": "Abjuração",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você ganha resistência a dano de ácido, frio, fogo, elétrico e trovejante. Quando você sofre dano de um desses tipos, pode usar sua reação para se tornar imune ao dano por um turno. Depois disso, a resistência termina."
  },
  {
    "nome": "Proteger Fortaleza",
    "nivel": 6,
    "escola": "Abjuração",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Toque",
    "componentes": "V S M (incenso queimando, enxofre e óleo, um cordão com nós atados, sangue de tríbulo e uma haste de prata no valor de 10 PO)",
    "duracao": "24 horas",
    "descricao": "Você cria uma defesa em uma área de até 225 metros quadrados, protegendo-a com diversos efeitos mágicos, como nevoeiro obscurecendo corredores, portas bloqueadas magicamente, escadas cobertas com teias, e diversos efeitos mágicos como Luzes Dançantes, Boca Encantada, Nuvem Fétida, entre outros. Você pode especificar quem não será afetado e pode estabelecer uma senha para que aqueles que a disserem não sofram os efeitos."
  },
  {
    "nome": "Raio Solar",
    "nivel": 6,
    "escola": "Evocação",
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (linha de 18m)",
    "componentes": "V S M (uma lupa)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você dispara um feixe de luz brilhante em uma linha de 18 metros de comprimento. Cada criatura na linha deve fazer uma salvaguarda de Constituição. Se falhar, sofre 6d8 de dano radiante e fica cega até o próximo turno. Mortos-vivos e gosmas têm desvantagem na salvaguarda. Enquanto a magia durar, sua mão emite luz solar, iluminando o ambiente."
  },
  {
    "nome": "Receptáculo Arcano",
    "nivel": 6,
    "escola": "Necromancia",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Pessoal",
    "componentes": "V S M (uma gema, cristal, relicário ou outro recipiente ornamental no valor mínimo de 500 PO)",
    "duracao": "Até ser dissipada",
    "descricao": "Sua alma deixa seu corpo e entra em um receptáculo mágico. Você pode projetar sua alma para tentar possuir um corpo humanoide. O alvo deve fazer uma salvaguarda de Carisma. Se falhar, sua alma ocupa o corpo do alvo, enquanto a alma do hospedeiro fica aprisionada no receptáculo. Você pode usar o corpo possuído como seu próprio, mas manterá suas características de Inteligência, Sabedoria e Carisma. Se o corpo morrer ou o receptáculo for destruído, sua alma retorna ao corpo original, se possível."
  },
  {
    "nome": "Sugestão em Massa",
    "nivel": 6,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m",
    "componentes": "V M (uma língua de uma cobra e um pouco de favo de mel ou uma gota de óleo adocicado)",
    "duracao": "24 horas",
    "descricao": "Você sugere um curso de ação (limitado a uma sentença ou duas) e magicamente influencia até doze criaturas à sua escolha, à sua vista e no alcance da magia, que possam ouvi-lo e compreendê-lo. Criaturas que não podem ser enfeitiçadas são imunes a este efeito. A sugestão precisa ser dita de uma forma que faça o curso de ação parecer razoável. Pedir à criatura que se esfaqueie, jogue-se contra uma lança, imole-se ou faça algum outro ato evidentemente danoso, automaticamente cancela o efeito da magia. Cada alvo deve fazer uma salvaguarda de Sabedoria. Se falhar, ele seguirá os atos sugeridos da melhor forma, dentro das suas próprias habilidades. O curso de ação sugerido é seguido enquanto a magia durar. Se ele puder ser completado em um período menor, a magia se encerra assim que isso ocorrer. Se você ou algum de seus companheiros causar dano a uma criatura afetada por esta magia, a magia se encerra. Em Níveis Superiores: Ao conjurar esta magia com um espaço de magia de 7º círculo, a duração será 10 dias. Usando um espaço de magia de 8º círculo, a duração será 30 dias. Ao usar um espaço de magia de 9º círculo, a duração será um ano e um dia."
  },
  {
    "nome": "Teleporte via Plantas",
    "nivel": 6,
    "escola": "Invocação",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "3m",
    "componentes": "V S",
    "duracao": "Uma rodada",
    "descricao": "Esta magia cria um vínculo mágico entre uma planta inanimada Grande ou maior no alcance da magia e outra planta, a qualquer distância, no mesmo plano de existência. Você deve ter visto ou tocado a planta de destino pelo menos uma vez antes. Enquanto a magia durar, qualquer criatura pode entrar pela planta alvo e sair na planta de destino usando 1,5 metro [5 ft.] de deslocamento."
  },
  {
    "nome": "Transformação de Tenser",
    "nivel": 6,
    "escola": "Transmutação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S M (alguns pêlos de um touro)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você se dota de resistência e proeza marcial alimentada por magia. Até que a magia termine, você não pode conjurar magias e você ganha os seguintes benefícios: Você ganha 50 pontos de vida temporários. Se algum destes permanecer quando a magia terminar, eles são perdidos. Você tem vantagem em rolagens de ataque que você faz com armas simples e marciais. Quando você atinge um alvo com um ataque de armas, esse alvo recebe um dano de energia adicional de 2d12. Você tem proficiência com todas as armaduras, escudos, armas simples e armas marciais. Você possui proficiência em testes de resistência de Força e Constituição. Você pode atacar duas vezes, ao invés de uma vez, quando você toma a ação de Ataque em seu turno. Você ignora esse benefício se você já possui um recurso, como Ataque Extra, que lhe dá ataques extras. Imediatamente após o término da magia, você deve ter sucesso em uma salvaguarda de Constituição CD 15 ou sofre um nível de exaustão."
  },
  {
    "nome": "Visão da Verdade",
    "nivel": 6,
    "escola": "Adivinhação",
    "classes": ["Bardo", "Bruxo", "Clérigo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (unguento para os olhos, custando 25 PO, feito a partir de cogumelo em pó, açafrão e gordura, que é consumido pela magia)",
    "duracao": "Uma hora",
    "descricao": "Você toca uma criatura voluntária. O alvo ganha a capacidade de ver as coisas como elas são verdadeiramente. Enquanto a magia durar, a criatura terá visão verdadeira, notará portas secretas escondidas por magia e poderá ver no Plano Etéreo em um alcance de 36 metros [120 ft.]."
  }
]