magias_nivel_5 = [
{
  "nome": "Aljava Veloz",
  "nivel": 5,
  "escola": "Transmutação",
  "classes": ["Patrulheiro"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Toque",
  "componentes": "V S M (uma aljava contendo ao menos uma munição)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Você transmuta sua aljava para que ela produza munição não-mágica de forma ilimitada, materializando-se na sua mão ao tocá-la. Enquanto a magia durar, você pode usar uma ação bônus, em cada um dos seus turnos, para fazer dois ataques com qualquer arma que utilize munição desta aljava. A aljava repõe automaticamente a munição utilizada. Qualquer munição criada se desintegra ao término da magia. Se a aljava sair de sua posse, a magia termina."
},
{
  "nome": "Âncora Planar",
  "nivel": 5,
  "escola": "Abjuração",
  "classes": ["Bardo", "Clérigo", "Druida", "Mago"],
  "tempo_conjuracao": "Uma hora",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (uma joia valendo pelo menos 1.000 PO, que é consumida pela magia)",
  "duracao": "24 horas",
  "descricao": "Você tenta forçar um celestial, elemental, feérico ou ínfero a servi-lo. A criatura deve fazer uma salvaguarda de Carisma. Se falhar, fica obrigada a obedecer às suas ordens enquanto durar a magia. Caso a criatura seja convocada por outra magia, sua duração é estendida para coincidir com a desta magia. Você pode ordenar a criatura a acompanhar você, vigiar um local ou entregar uma mensagem. A criatura obedece à risca, mas se hostil, tentará distorcer suas ordens."
},
{
  "nome": "Animar Objetos",
  "nivel": 5,
  "escola": "Transmutação",
  "classes": ["Artífice", "Bardo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m (120 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Escolha até dez objetos não-mágicos no alcance. Objetos de tamanho Médio contam como dois, Grandes como quatro, e Enormes como oito. Cada um se anima, tornando-se uma criatura sob seu controle. Com uma ação bônus, você pode comandar até 150m de distância. A criatura obedece às suas ordens, atacando ou se movendo como desejado. Se um objeto ficar com 0 pontos de vida, ele volta a sua forma original. A magia dura até os objetos atingirem 0 PV. [Consultar nas tabelas as estatisicas por tamanho de objeto]"
},
{
  "nome": "Arma Sagrada",
  "nivel": 5,
  "escola": "Evocação",
  "classes": ["Clérigo", "Paladino"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "Concentração, até 1 hora",
  "descricao": "Imbui uma arma tocada com poder sagrado. Enquanto a magia durar, a arma emite luz brilhante e causa 2d8 de dano radiante adicional em ataques. Como ação bônus, você pode fazer a arma emitir um brilho, fazendo com que criaturas a sua escolha dentro de 9m façam um teste de Constituição. Em falha, sofrem 4d8 de dano radiante e ficam cegas por 1 minuto. Em sucesso, sofrem metade do dano e não ficam cegas."
},
{
  "nome": "Ataque do Vento de Aço",
  "nivel": 5,
  "escola": "Invocação",
  "classes": ["Patrulheiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "9m (30 ft.)",
  "componentes": "S M (uma arma de combate corpo a corpo valendo, no mínimo, 1sp)",
  "duracao": "Instantânea",
  "descricao": "Você agita sua arma e se teletransporta para atacar como o vento. Escolha até cinco criaturas no alcance e faça um ataque mágico corpo a corpo contra cada uma. Em acerto, cada alvo sofre 6d10 de dano energético. Após os ataques, você pode se teletransportar para um espaço vazio até 1,5m de um alvo atingido ou falhado."
},
{
  "nome": "Aurora",
  "nivel": 5,
  "escola": "Evocação",
  "classes": ["Clérigo", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um pingente de raio solar valendo pelo menos 100 gp)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Você cria um cilindro de luz solar com 9m de raio e 12m de altura. Criaturas dentro do cilindro devem fazer uma salvaguarda de Constituição, sofrendo 4d10 de dano radiante em falha, ou metade do dano em sucesso. O cilindro pode ser movido até 18m como uma ação bônus sua. A magia dura até 1 minuto."
},
{
    "nome": "Chamado Infernal",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "27m (90 ft.)",
    "componentes": "V S M (um rubi valendo, no mínimo, 999 PO)",
    "duracao": "Concentração, até 1 hora",
    "descricao": "Você convoca um demônio dos Nove Infernos, escolhendo um com classificação de desafio 6 ou inferior. O demônio aparece em um espaço desocupado dentro do alcance. Ele não é amigável a você e pode agir de maneira hostil. Você pode tentar comandá-lo usando um teste de Carisma (Enganação, Intimidação ou Persuasão) contestado pelo teste de Sabedoria (Insight) do demônio. Se falhar, o demônio se torna imune a comandos verbais. Se tiver um talismã de demônio, você pode invocar esse demônio sem testes. Em Níveis Superiores, a classificação de desafio aumenta em 1 para cada nível de espaço acima do 5º."
  },
  {
    "nome": "Círculo de Poder",
    "nivel": 5,
    "escola": "Abjuração",
    "classes": ["Paladino"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 9m [30 ft.])",
    "componentes": "V",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Uma esfera de energia divina irradia de você, oferecendo vantagem nas salvaguardas contra magias e efeitos mágicos para todas as criaturas amigas na área de 9 metros ao seu redor. Além disso, criaturas que consigam salvar contra magia ou efeito mágico que cause metade de dano não sofrem dano algum."
  },
  {
    "nome": "Círculo de Teleporte",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "3m (10 ft.)",
    "componentes": "V M (gizes raros e tintas infundidas com gemas valendo 50 PO)",
    "duracao": "Uma rodada",
    "descricao": "Você cria um portal de teleporte conectando sua localização a um círculo de teleporte permanente que você conheça. O portal dura até o final do próximo turno e qualquer criatura que entre nele se teleporta instantaneamente para o local de destino."
  },
  {
    "nome": "Coluna de Chamas",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (uma pitada de enxofre)",
    "duracao": "Instantânea",
    "descricao": "Uma coluna de fogo divino cai sobre uma área, atingindo todas as criaturas em um cilindro de 3 metros de raio e 12 metros de altura. As criaturas devem fazer uma salvaguarda de Destreza. Se falharem, sofrem 4d6 de dano ígneo e 4d6 de dano radiante, ou metade do dano se acertarem."
  },
  {
    "nome": "Comunhão",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S M (incenso e um frasco de água benta ou profana)",
    "duracao": "1 minuto",
    "descricao": "Você entra em contato com sua divindade ou um representante dela para fazer até três perguntas que podem ser respondidas com sim ou não. As respostas são corretas, mas podem ser limitadas pelo conhecimento da divindade. Se você conjurar a magia mais de uma vez antes do descanso longo, há uma chance de não receber respostas nas conjurações subsequentes."
  },
  {
    "nome": "Comunhão com a Natureza",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Druida", "Patrulheiro"],
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você se conecta à natureza ao seu redor, obtendo informações sobre o terreno, corpos d'água, plantas, animais, e mais, em um raio de 5 km (3 milhas) ao ar livre ou 90 metros (300 ft.) em cavernas. A magia também revela a presença de seres poderosos como mortos-vivos ou elementais na área."
  },
  {
    "nome": "Cone de Frio",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cone de 18m [60 ft.])",
    "componentes": "V S M (um pequeno cristal ou cone de vidro)",
    "duracao": "Instantânea",
    "descricao": "Uma explosão de ar frio irrompe de suas mãos, causando 8d8 de dano gélido (metade em caso de sucesso na salvaguarda de Constituição). Criaturas mortas se transformam em estátuas de gelo que derretem."
  },
  {
    "nome": "Conjurar Saraivada",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Patrulheiro"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V S M (uma peça de munição ou uma arma de arremesso)",
    "duracao": "Instantânea",
    "descricao": "Você lança uma arma ou munição no ar, criando centenas de duplicatas que caem sobre a área. Cada criatura em um cilindro de 12 metros de raio e 6 metros de altura deve fazer uma salvaguarda de Destreza. Se falharem, sofrem 8d8 de dano, metade em caso de sucesso. O tipo de dano depende da munição ou arma utilizada."
  },
  {
    "nome": "Consagrar",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "24 horas",
    "alcance": "Toque",
    "componentes": "V S M (ervas, óleo e incenso no valor mínimo de 1.000 PO, que a magia consome)",
    "duracao": "Até ser dissipada",
    "descricao": "Você toca um ponto e infunde uma área em torno dele com poder sagrado (ou profano). A área pode ter um raio de até 18 metros e a magia falha se o raio incluir uma área já sob o efeito de uma magia consagrar. Criaturas celestiais, elementais, feéricas, ínferas e mortos-vivos não podem entrar na área e não podem enfeitiçar, amedrontar ou possuir outras criaturas ali. Você pode adicionar efeitos, como Coragem (não amedrontar), Descanso Eterno (evitar mortos-vivos), Escuridão (sem luz), Luz do Dia (luz plena), etc. Efeito adicional se aplica com teste de Carisma da criatura quando entra ou começa o turno na área."
  },
  {
    "nome": "Contágio",
    "nivel": 5,
    "escola": "Necromancia",
    "classes": ["Clérigo", "Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "7 dias",
    "descricao": "Seu toque inflige uma das doenças listadas a uma criatura. A criatura faz uma salvaguarda de Constituição a cada fim de turno, e após três falhas, a doença continua. Se for bem-sucedida três vezes, a criatura se recupera. Doenças incluem Ardência Mental (desvantagem em Inteligência e Confusão), Doença da Cegueira (cegueira e desvantagem em Sabedoria), Febre Perniciosa (desvantagem em Força), Necrose da Carne (desvantagem em Carisma e vulnerabilidade a dano), Ruína Pegajosa (desvantagem em Constituição), e Tremedeira (desvantagem em Destreza)."
  },
  {
    "nome": "Contato Extraplanar",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "1 minuto",
    "descricao": "Você entra em contato com uma entidade extraplanar e pode fazer até 5 perguntas. Faça uma salvaguarda de Inteligência (CD 15), ou sofra 6d6 de dano psíquico e fique insano até um descanso longo. Em caso de sucesso, o DM responde cada pergunta com palavras como ‘sim’, ‘não’, ‘talvez’, ‘irrelevante’ ou ‘indeterminado’."
  },
  {
    "nome": "Controlar os Ventos",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "90m",
    "componentes": "V S",
    "duracao": "Concentração, até 1 hora",
    "descricao": "Você controla o ar em um cubo de 30 metros. Escolha entre três efeitos: Lufadas (vento forte, moderado ou calmo), Ventos Ascendentes (acelera quedas e saltos), ou Ventos Descendentes (diminui ataques à distância e força salvaguardas contra voo). O efeito pode ser alterado ou parado com ações subsequentes."
  },
  {
    "nome": "Criação",
    "nivel": 5,
    "escola": "Ilusão",
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "9m",
    "componentes": "V S M (um pequeno pedaço do material do item a ser criado)",
    "duracao": "Especial",
    "descricao": "Você cria objetos inanimados a partir de matéria do Sombral. O item pode ser vegetal, rocha, metal ou cristal, e seu tamanho não pode exceder um cubo de 1,5m. A duração depende do material: vegetal (1 dia), rocha/cristal (12h), metais preciosos (1h), pedras preciosas (10min), e adamantina ou mithral (1min)."
  },
  {
    "nome": "Criar Passagem",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S M (uma pitada de sementes de gergelim)",
    "duracao": "Uma hora",
    "descricao": "Uma passagem surge numa superfície de madeira, argamassa ou pedra (como uma parede, teto ou chão) dentro do alcance da magia. Você escolhe a dimensão da abertura (até 1,5m de largura, 2,5m de altura e 6m de profundidade) e ela permanece por uma hora. Não há risco de instabilidade estrutural. Caso alguém ou algo esteja dentro da passagem quando ela desaparecer, será expulso para um espaço desocupado ao redor."
  },
  {
    "nome": "Cúpula Antivida",
    "nivel": 5,
    "escola": "Abjuração",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 3m)",
    "componentes": "V S",
    "duracao": "Concentração, até uma hora",
    "descricao": "Você cria uma barreira cintilante ao seu redor com raio de 3 metros, impedindo que criaturas que não sejam mortos-vivos ou constructos passem por ela. A barreira permite ataques à distância ou com armas de combate corpo a corpo com a propriedade extensão. Se você mover-se para que alguém atravesse, a magia se desfaz."
  },
  {
    "nome": "Curar Ferimentos em Massa",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Bardo", "Clérigo", "Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Uma onda de cura afeta até seis criaturas em um raio de 9 metros a partir de um ponto à sua escolha. Cada alvo recupera 3d8 + modificador de conjuração de pontos de vida. Mortos-vivos e constructos não são afetados."
  },
  {
    "nome": "Dança Macabra",
    "nivel": 5,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até uma hora",
    "descricao": "Fios de poder sombrio perfuram até cinco cadáveres pequenos ou médios dentro do alcance, fazendo-os se erguer como mortos-vivos (esqueletos ou zumbis). Eles ganham bônus em ataque e dano igual ao modificador de conjuração. Você pode usar uma ação bônus para controlar mentalmente as criaturas, emitindo o mesmo comando para todas. Elas permanecem sob seu controle até a magia terminar."
  },
  {
    "nome": "Despertar",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Bardo", "Druida"],
    "tempo_conjuracao": "8 horas",
    "alcance": "Toque",
    "componentes": "V S M (uma ágata no valor mínimo de 1.000 PO, consumida pela magia)",
    "duracao": "Instantânea",
    "descricao": "Você desperta uma fera ou planta de tamanho Enorme ou menor, que deve ter Inteligência 3 ou menor. O alvo ganha Inteligência 10, a capacidade de falar um idioma que você conhece e, no caso das plantas, ganha movimento e sentidos humanos. A criatura fica enfeitiçada por você por 30 dias, após os quais ela decide se permanece amiga ou não."
  },
  {
    "nome": "Despistar",
    "nivel": 5,
    "escola": "Ilusão",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "S",
    "duracao": "Concentração, até uma hora",
    "descricao": "Você se torna invisível e cria uma duplicata ilusória sua, que pode se mover e se comportar como você desejar. Você pode ver através dos olhos da duplicata e se comunicar com ela, podendo alternar entre seus sentidos e os dela. A invisibilidade se encerra se você atacar ou conjurar uma magia."
  },
  {
    "nome": "Destruição Banidora",
    "nivel": 5,
    "escola": "Abjuração",
    "classes": ["Paladino"],
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "No próximo ataque armado, sua arma causa 5d10 pontos de dano adicionais. Se o ataque reduzir os pontos de vida do alvo a 50 ou menos, ele é banido. Criaturas de planos diferentes desaparecem, retornando ao seu plano de origem, enquanto criaturas do mesmo plano são transportadas para um semiplano inofensivo, onde ficam incapacitados até o fim da magia."
  },
  {
    "nome": "Dissipar o Bem e o Mal",
    "nivel": 5,
    "escola": "Abjuração",
    "classes": ["Clérigo", "Paladino"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S M (água benta ou pó de prata e de ferro)",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você é protegido contra celestiais, elementais, feéricos, ínferos e mortos-vivos. Criaturas dessas categorias têm desvantagem nas jogadas de ataque contra você. Você pode usar a magia para quebrar encantamentos, amedrontamentos ou possessões, ou executar um ataque mágico contra uma criatura dessas categorias, forçando-a a retornar ao seu plano de origem."
  },
  {
    "nome": "Dominar Pessoa",
    "nivel": 5,
    "escola": "Encantamento",
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você tenta enfeitiçar um humanoide dentro do alcance. Se falhar, ele faz uma salvaguarda de Sabedoria. Enquanto enfeitiçado, você pode enviar comandos telepáticos à criatura. Pode assumir controle total da criatura por um turno, forçando-a a realizar ações específicas. O alvo faz uma nova salvaguarda sempre que sofre dano, encerrando a magia em caso de sucesso."
  },
  {
    "nome": "Enervação",
    "nivel": 5,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Uma gavinha de escuridão se projeta de você, tocando uma criatura que você pode ver dentro do alcance para drenar sua vida. O alvo deve fazer salvaguarda de Destreza. Em um sucesso, o alvo recebe 2d8 de dano necrótico e a magia termina. Em uma falha, o alvo sofre 4d8 de dano necrótico e, até a magia terminar, você pode usar sua ação em cada um dos seus turnos para causar automaticamente 4d8 de dano necrótico ao alvo. A magia termina se você usa sua ação para fazer qualquer outra coisa, se o alvo estiver fora do alcance da magia ou se o alvo tiver cobertura total contra você. Sempre que a magia causar dano a um alvo, você recupera pontos de vida iguais à metade da quantidade de dano necrótico que o alvo sofre.",
    "em_niveis_superiores": "Quando você conjura essa magia usando um espaço de magia de 6º círculo ou superior, o dano aumenta em 1d8 para cada nível do espaço de magia acima do 5º."
  },
  {
    "nome": "Estática sináptica",
    "nivel": 5,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você escolhe um ponto dentro do alcance e faz com que a energia psíquica exploda lá. Cada criatura em uma esfera de 6m de raio (20-foot-radius sphere) centrada nesse ponto deve fazer salvaguarda de Inteligência. Uma criatura com uma pontuação de Inteligência de 2 ou inferior não pode ser afetada por esta magia. Um alvo leva 8d6 de dano psíquico em salvaguarda falho, ou metade de dano em um bem sucedido. Após salvaguarda falho, um alvo tem pensamentos confusos por 1 minuto. Durante esse período, ele rola um d6 e subtrai o número rolado de todas as suas rolagens de ataque e verificações de habilidade, bem como seus salvaguarda de Constituição para manter a concentração. O alvo pode fazer salvaguarda de Inteligência no final de cada um de seus turnos, terminando o efeito sobre si mesmo em um sucesso."
  },
  {
    "nome": "Fortalecimento de Perícia",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Sua magia aprofunda a compreensão de uma criatura de seu próprio talento. Você toca uma criatura disposta e dá-lhe especialização em uma perícia de sua escolha; até que a magia termine, a criatura dobra seu bônus de proficiência para verificações de habilidade que usem a perícia escolhida. Você deve escolher uma perícia em que o alvo seja proficiente e que ainda não esteja se beneficiando de um efeito, como a Expertise, que dobre seu bônus de proficiência."
  },
  {
    "nome": "Imobilizar Monstro",
    "nivel": 5,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m (90 ft.)",
    "componentes": "V S M (um pedaço pequeno e reto de ferro)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Escolha uma criatura à sua vista e no alcance da magia. O alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria ou fica paralisado enquanto a magia durar. Esta magia não tem efeito sobre mortos-vivos. No final de cada um dos turnos dele, o alvo pode fazer uma nova salvaguarda de Sabedoria. Em caso de sucesso, a magia se encerra sobre o alvo.",
    "em_niveis_superiores": "Ao conjurar esta magia usando um espaço de magia de 6º círculo ou superior, você pode atingir uma criatura adicional para cada círculo do espaço acima do 5º. As criaturas devem estar a até 9 metros umas das outras quando você as atingir."
  },
  {
    "nome": "Imolação",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m (90 ft.)",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Chamas rodeiam uma criatura que você possa ver, dentro do alcance. O alvo deve realizar salvaguarda de Destreza. Ele sofre 7d6 de dano de fogo se falhar, ou metade desse dano se obtiver sucesso. Se falhar, o alvo também se incendeia pela duração da magia. O alvo em chamas emite luz plena num raio de 9m (30-foot radius) e penumbra por 9m (30 ft.) adicionais. No final de cada um dos turnos dele, o alvo repete o salvaguarda. Ele sofre 3d6 de dano de fogo se falhar na resistência e a magia termina com um sucesso. Essas chamas mágicas não podem ser extintas através de meios não-mágicos. Se o dano dessa magia reduzir um alvo a 0 pontos de vida, ele é transformado em cinzas."
  },
  {
    "nome": "Inundação de Energia Negativa",
    "nivel": 5,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V M (um osso quebrado e um quadrado de seda negra)",
    "duracao": "Instantânea",
    "descricao": "Você envia fitas de energia negativa a uma criatura que você pode ver dentro do alcance. A menos que o alvo seja um morto-vivo, ele deve fazer um lance de salvação da Constituição, levando 5d12 dano necrótico em uma falha, ou metade de dano em um sucesso. Um alvo morto por este dano levanta como um zumbi no início do seu próximo turno. O zumbi persegue qualquer criatura que possa ver que esteja mais próxima dele. As estatísticas do zumbi estão no Manual dos Monstros. Se o alvo dessa magia for um morto vivo, o alvo não faz salvaguarda. Em vez disso, role 5d12. O alvo recebe metade do total como pontos de vida temporários."
  },
  {
    "nome": "Invocar Celestial",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Clérigo", "Paladino"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m (90 ft.)",
    "componentes": "V S M (um relicário de ouro no valor mínimo de 500 PO)",
    "duracao": "Concentração, Uma hora",
    "descricao": "Você convoca um espírito celestial. Ele se manifesta em um espaço desocupado a sua vista dentro do alcance. Essa forma corpórea utiliza o bloco de estatísticas do Espírito Celestial. Quando você conjura a magia, escolha entre Vingador ou Defensor. Sua escolha determina o ataque da criatura em seu bloco de estatísticas. A criatura desaparece se chegar a 0 pontos de vida ou quando a magia se encerra. A criatura é uma aliada para você e seus companheiros. Em combate, a criatura compartilha sua contagem de iniciativa, mas realiza o turno dela imediatamente após o seu. Ela obedece a seus comandos verbais (nenhuma ação é exigida de você). Se não indicar nenhuma ação, ela realiza a ação de Esquiva e usa seu deslocamento para evitar o perigo."
  },
  {
    "nome": "Invocar Elemental",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Druida", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "27m (90 ft.)",
    "componentes": "V S M (incenso aceso para ar, argila mole para terra, enxofre e fósforo para fogo ou água e areia para água)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você invoca um servo elemental. Escolha uma área de ar, terra, fogo ou água, no alcance da magia, que preencha um cubo de 3 metros (10 ft.). Um elemental de nível de desafio 5 ou menor, apropriado à área escolhida, aparece em um espaço desocupado a até 3 metros (10 ft.) da área escolhida. O elemental desaparece ao ficar com 0 pontos de vida ou ao término da magia. Ele é amistoso com você e seus companheiros enquanto a magia durar. Jogue a iniciativa para o elemental, que tem seus próprios turnos. Ele obedece a qualquer comando verbal que você lhe dê (não requer ação sua), desde que isso não viole o alinhamento dele. Caso não seja dado comando algum, ele se defende de seres hostis, não executando nenhuma outra ação."
  },
  {
    "nome": "Ira da Natureza",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Druida", "Patrulheiro"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você convoca os espíritos da natureza os instiga contra seus inimigos. Escolha um ponto que você pode ver dentro do alcance. Os espíritos causam árvores, pedras e vegetação rasteira em um cubo de 18m (60-foot cube) a partir desse ponto a se tornarem animados até o término da magia. Grama e Vegetação Rasteira. Qualquer área de terra no cubo que é coberta por grama ou raízes é considerada terreno difícil para seus inimigos. Árvores. No início de cada um de seus turnos, cada um de seus inimigos a até 3m (10 ft.) de distância de qualquer árvore deve ter sucesso em salvaguarda de Destreza ou sofre 4d6 de dano de corte. Raízes e vinhas. No final de cada uma dos seus turnos, uma criatura a sua escolha que está no chão na área de cobertura deve ter sucesso em salvaguarda de Força ou ficará impedida até o fim da magia. Rochas. Como uma ação bônus no seu turno, você pode causar uma rocha solta na área de cobertura a se lançar contra uma criatura que você pode ver na área de cobertura."
  },
  {
    "nome": "Lendas e Histórias",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Bardo", "Clérigo", "Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Pessoal",
    "componentes": "V S M (um incenso no valor mínimo de 250 PO, que a magia consome, e quatro tiras de marfim no valor mínimo de 50 PO cada)",
    "duracao": "Instantânea",
    "descricao": "Nomeie ou descreva uma pessoa, local ou objeto. A magia traz à sua mente um breve resumo de conhecimento significativo sobre aquilo que você nomeou. O conhecimento pode consistir de contos atuais, histórias esquecidas ou até mesmo conhecimento secreto que nunca foi amplamente sabido."
  },
  {
    "nome": "Ligação Telepática de Rary",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "9m (30 ft.)",
    "componentes": "V S M (pedaços de cascas de ovos de dois tipos diferentes de criatura)",
    "duracao": "1 hora",
    "descricao": "Você cria uma ligação telepática com até oito criaturas voluntárias no alcance da magia. As criaturas podem se comunicar telepaticamente entre si, independentemente de idioma, enquanto a magia durar. Não afeta criaturas com Inteligência 2 ou menos. A comunicação é possível a qualquer distância, mas não se estende para outros planos de existência."
  },
  {
    "nome": "Mão de Bigby",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (uma casca de ovo e uma luva feita de pele de cobra)",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você cria uma mão de tamanho Grande feita de energia translúcida. A mão pode ser movida até 18 metros por sua ação bônus. Ela pode atacar, empurrar, esmagar ou interpor-se entre você e uma criatura, com vários efeitos dependendo da ação escolhida. A mão possui CA 20, 26 de Força e 10 de Destreza, e pode ser destruída se atingir 0 pontos de vida."
  },
  {
    "nome": "Missão",
    "nivel": 5,
    "escola": "Encantamento",
    "classes": ["Bardo", "Clérigo", "Druida", "Mago", "Paladino"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "18m (60 ft.)",
    "componentes": "V",
    "duracao": "30 dias",
    "descricao": "Você emite um comando mágico a uma criatura à sua vista. Se não obedecer, sofre 5d10 pontos de dano psíquico. A criatura deve ser bem-sucedida em uma salvaguarda de Sabedoria ou ficará enfeitiçada. O comando pode ser qualquer ação, exceto suicídio. A magia pode ser encerrada por Dissipar Magia, Restauração Maior ou Desejo."
  },
  {
    "nome": "Modificar Memória",
    "nivel": 5,
    "escola": "Encantamento",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você tenta alterar as memórias de uma criatura, afetando um evento que ela vivenciou nas últimas 24 horas. A criatura faz uma salvaguarda de Sabedoria para resistir. Se falhar, ela se torna enfeitiçada e você pode modificar ou eliminar a memória. Se a magia se encerrar antes de concluir, a memória não é alterada."
  },
  {
    "nome": "Muralha de Energia",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (uma pitada de pó de pedra preciosa clara esmagada)",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Uma muralha invisível de força surge no ponto escolhido. Ela pode ser moldada em várias formas e não pode ser atravessada por nada físico. A muralha é imune a dano e não pode ser dissipado, mas é destruída por Desintegrar. Ela bloqueia também viagens etéreas."
  },
  {
    "nome": "Muralha de Pedra",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Artífice", "Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (um pequeno bloco de granito)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Uma muralha não-mágica de pedra maciça surge em um ponto à sua vista. Com 15 cm de espessura e composta por 10 painéis de 3 metros cada, ela pode ser moldada de diversas formas, como uma ponte ou rampa. A muralha pode ser danificada, com 30 pontos de vida por 2,5 cm de espessura. Se você mantiver sua concentração, a muralha se torna permanente. Caso contrário, ela desaparece ao fim da magia."
  },
  {
    "nome": "Névoa Mortal",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria uma esfera de névoa venenosa com raio de 6 metros, que obscurece a área e causa dano a qualquer criatura que entre nela ou inicie seu turno lá. As criaturas devem fazer uma salvaguarda de Constituição ou sofrer 5d8 de dano venenoso. A névoa se desloca 3 metros a cada um dos seus turnos. A magia termina quando a névoa é dissipada por vento forte."
  },
  {
    "nome": "Onda Destrutiva",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Paladino"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 9m)",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você cria uma explosão de energia divina no chão ao seu redor, causando 5d6 pontos de dano trovejante e 5d6 pontos de dano radiante ou necrótico (à sua escolha) em criaturas no alcance. Aqueles que falharem na salvaguarda de Constituição também ficam caídos. Criaturas bem-sucedidas sofrem metade do dano e não ficam caídas."
  },
  {
    "nome": "Parede de Luz",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (um espelho de mão)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria uma parede cintilante de luz radiante, com até 18m de comprimento e 3m de altura. Quando surge, causa 4d8 pontos de dano radiante e cega as criaturas em sua área. Você pode disparar raios de radiação de 4d8 de dano em criaturas a até 18m de distância. A parede emite luz brilhante e pode ser destruída à medida que sua extensão diminui."
  },
  {
    "nome": "Passo Arbóreo",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Druida", "Patrulheiro"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você pode entrar em uma árvore e se teletransportar instantaneamente para outra árvore do mesmo tipo dentro de 150 metros. Você conhece a localização de todas as árvores do tipo escolhido dentro desse alcance. A cada turno, pode usar essa habilidade para se teletransportar, mas deve terminar cada turno fora de uma árvore."
  },
  {
    "nome": "Passo Distante",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você se teletransporta instantaneamente até 18 metros para um espaço desocupado que possa ver. Em cada um dos seus turnos, antes de a magia terminar, você pode usar uma ação bônus para se teletransportar novamente."
  },
  {
    "nome": "Praga de Insetos",
    "nivel": 5,
    "escola": "Invocação",
    "classes": ["Clérigo", "Druida", "Feiticeiro"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "90m (300 ft.)",
    "componentes": "V S M (alguns grãos de açúcar, cereais e uma mancha de gordura)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria um enxame de gafanhotos venenosos que se espalha em uma área de 6 metros de raio, causando dano de 4d10 a todas as criaturas no local. A área se torna terreno difícil e qualquer criatura que termine o turno nela deve fazer uma salvaguarda de Constituição. A magia pode ser ampliada em Níveis Superiores, com o aumento de dano."
  },
  {
    "nome": "Redemoinho",
    "nivel": 5,
    "escola": "Evocação",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (papel ou folhas no formato de um funil)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Uma massa de água cria um redemoinho de 9 metros de raio, causando dano contundente de 6d6 em criaturas que começam seu turno na área. As criaturas devem passar em uma salvaguarda de Força ou serão puxadas 3 metros em direção ao centro da área."
  },
  {
  "nome": "Reencarnar",
  "nivel": 5,
  "escola": "Transmutação",
  "classes": ["Druida"],
  "tempo_conjuracao": "Uma hora",
  "alcance": "Toque",
  "componentes": "V S M (óleos raros e unguentos no valor mínimo de 1.000 PO, que a magia consome)",
  "duracao": "Instantânea",
  "descricao": "Você toca um humanoide morto ou um pedaço de um humanoide morto. Se a criatura não estiver morta há mais de 10 dias, a magia cria um novo corpo adulto para ela e convoca sua alma a entrar no corpo. Caso a alma da criatura não esteja livre ou disposta, a magia falha. O DM rola um d100 para determinar a nova raça da criatura reencarnada: 01-04 Draconato, 05-13 Anão da Colina, 14-21 Anão da Montanha, 22-25 Elfo Obscuro, 26-34 Elfo Alto, 35-42 Elfo Silvestre, 43-46 Gnomo dos Bosques, 47-52 Gnomo das Rochas, 53-56 Meio-elfo, 57-60 Meio-orc, 61-68 Pequenino Pé-Ligeiro, 69-76 Pequenino Robusto, 77-96 Humano, 97-00 Tiferino. A criatura mantém suas memórias e habilidades da forma original, exceto pelas mudanças de raça e traços raciais."
},
{
    "nome": "Restauração Maior",
    "nivel": 5,
    "escola": "Abjuração",
    "classes": ["Artífice", "Bardo", "Clérigo", "Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (pó de diamante no valor mínimo de 100 PO, que a magia consome)",
    "duracao": "Instantânea",
    "descricao": "Você toca uma criatura, imbuindo-a com energia positiva que desfaz efeitos debilitantes. Pode reduzir o nível de exaustão em 1 ou cancelar efeitos como feitiçarias, petrificação, maldições, redução de atributos ou redução de pontos de vida máximos."
  },
  {
    "nome": "Reviver os Mortos",
    "nivel": 5,
    "escola": "Necromancia",
    "classes": ["Bardo", "Clérigo", "Paladino"],
    "tempo_conjuracao": "Uma hora",
    "alcance": "Toque",
    "componentes": "V S M (um diamante no valor mínimo de 500 PO, que a magia consome)",
    "duracao": "Instantânea",
    "descricao": "Uma criatura retorna à vida, com 1 ponto de vida, desde que tenha falecido há menos de 10 dias. Ela também é curada de venenos e doenças não-mágicas. O alvo sofre -4 em jogadas de ataque, testes de atributo e salvaguardas, até que a penalidade desapareça após descanso."
  },
  {
    "nome": "Similaridade",
    "nivel": 5,
    "escola": "Ilusão",
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S",
    "duracao": "8 horas",
    "descricao": "Você altera a aparência de criaturas à sua vista. O alvo pode tentar resistir com uma salvaguarda de Carisma. A magia não altera a estrutura do corpo, mas pode mudar tamanho, forma e roupas. Caso o alvo inspecione, ele pode perceber a ilusão com um teste de Inteligência."
  },
  {
    "nome": "Sonho",
    "nivel": 5,
    "escola": "Ilusão",
    "classes": ["Bardo", "Bruxo", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Especial",
    "componentes": "V S M (areia, tinta e uma pena de pássaro adormecido)",
    "duracao": "8 horas",
    "descricao": "Molda os sonhos de uma criatura no mesmo plano. Se o alvo estiver dormindo, você pode interagir com ele em seus sonhos. Você pode usar a magia para passar mensagens ou causar pesadelos, causando dano psíquico se o alvo falhar na salvaguarda."
  },
  {
    "nome": "Telecinese",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você manipula objetos e criaturas com a mente. Pode mover criaturas de tamanho Enorme ou menor e objetos de até 450 kg. A magia permite controle fino, como abrir portas ou derramar líquidos."
  },
  {
    "nome": "Transmutar Pedra",
    "nivel": 5,
    "escola": "Transmutação",
    "classes": ["Druida", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S M (barro e água)",
    "duracao": "Instantânea",
    "descricao": "Você escolhe uma área de pedra ou lama que caiba em um cubo de 12m (40 ft.) dentro do alcance e pode escolher um dos efeitos a seguir. Transmutar Pedra em Lama: A pedra se transforma em lama espessa, tornando o terreno lamacento e difícil de atravessar. Criaturas que se movem através da lama devem fazer uma salvaguarda de Força para evitar afundar na lama, ficando impedidas até conseguirem se libertar. Transmutar Lama em Pedra: A lama ou areia movediça se transforma em pedra sólida, dificultando a movimentação das criaturas dentro da área. Elas devem fazer uma salvaguarda de Destreza ou ficarão presas na pedra, podendo se libertar com um teste de Força ou causando dano à pedra. Se você conjurar sobre o teto, a lama ou a pedra pode cair sobre as criaturas abaixo, causando dano de 4d8 em caso de falha na salvaguarda de Destreza."
  },
  {
    "nome": "Vidência",
    "nivel": 5,
    "escola": "Adivinhação",
    "classes": ["Bardo", "Bruxo", "Clérigo", "Druida", "Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Pessoal",
    "componentes": "V S M (foco no valor mínimo de 1.000 PO, como bola de cristal, espelho de prata ou recipiente com água benta)",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você cria um sensor invisível que lhe permite ver e ouvir uma criatura à sua escolha que esteja no mesmo plano de existência. O alvo tenta resistir com uma salvaguarda de Sabedoria, com modificadores baseados em sua relação com você e o tipo de conexão física (ex: se você tem um pedaço do corpo do alvo ou um objeto que ele usou). Se o alvo falhar, um sensor invisível se forma a 3 metros (10 ft.) dele e se move com ele enquanto a magia durar. Você também pode escolher um local que tenha visto antes, e o sensor aparecerá nesse local em vez de seguir uma criatura. Criaturas que possam ver objetos invisíveis podem perceber o sensor como um orbe luminoso. Se o alvo souber que está sendo observado, pode optar por abrir mão da salvaguarda e ser observado voluntariamente.[Checar tabelas]"
  }
]