magias_nivel_8 = [
    {
    "nome": "Antipatia/Simpatia",
    "nivel": 8,
    "escola": "Encantamento",
    "classes": ["Druida", "Mago"],
    "tempo_conjuracao": "1 hora",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (um pedaço de alume embebido ou em vinagre para antipatia ou em uma gota de mel para simpatia)",
    "duracao": "10 dias",
    "descricao": "Esta magia atrai ou repele criaturas especificadas. Você escolhe um alvo (criatura ou objeto Enorme ou menor) e uma criatura inteligente como alvo (ex. dragões vermelhos, goblins).\n\n**Antipatia**: As criaturas do tipo escolhido devem fazer uma salvaguarda de Sabedoria ao se aproximarem a até 18 metros do alvo ou ficam amedrontadas, movendo-se para longe. **Simpatia**: As criaturas devem fazer uma salvaguarda de Sabedoria ou se aproximar do alvo, não podendo afastar-se voluntariamente.\n\nSe o alvo causar dano ou ferir a criatura afetada, ela pode fazer uma salvaguarda de Sabedoria para encerrar o efeito."
  },
  {
    "nome": "Aura Sagrada",
    "nivel": 8,
    "escola": "Abjuração",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "1 ação",
    "alcance": "Pessoal",
    "componentes": "V S M (um relicário no valor de 1.000 PO contendo uma relíquia sagrada)",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Uma luz divina emana de você, criando uma aura de 9 metros (30 ft.) ao redor de você. Criaturas dentro dessa aura têm vantagem em todas as salvaguardas e inimigos têm desvantagem em jogadas de ataque contra elas.\n\nQuando um ínfero ou morto-vivo atinge uma criatura afetada, o atacante deve fazer uma salvaguarda de Constituição ou ficar cego até o final da magia."
  },
  {
    "nome": "Campo Antimagia",
    "nivel": 8,
    "escola": "Abjuração",
    "classes": ["Clérigo", "Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "Pessoal (esfera de 3m de raio)",
    "componentes": "V S M (uma pitada de pó de ferro ou raspas de ferro)",
    "duracao": "Concentração, até 1 hora",
    "descricao": "Você é cercado por uma esfera de 3 metros de raio que anula toda magia dentro dela. Criaturas e objetos mágicos são suprimidos dentro da esfera e magias não podem ser conjuradas.\n\nMagias, convocação de criaturas, e itens mágicos perdem seus efeitos enquanto estiverem dentro da esfera. A esfera move-se com você e suprime áreas de magia sobrepostas. Efeitos mágicos ativos também são suprimidos."
  },
  {
    "nome": "Clone",
    "nivel": 8,
    "escola": "Necromancia",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 hora",
    "alcance": "Toque",
    "componentes": "V S M (um diamante com valor mínimo de 1.000 PO, 2,5 cm³ de carne da criatura clonada, e um receptáculo de 2.000 PO)",
    "duracao": "Instantânea",
    "descricao": "Esta magia cria uma duplicata inerte de uma criatura viva como uma garantia contra a morte. O clone amadurece após 120 dias e pode ser a versão mais jovem da criatura. Quando a criatura original morre, sua alma é transferida para o clone, que se torna fisicamente idêntico e retém suas memórias e habilidades. O clone não possui os equipamentos originais. O receptáculo deve permanecer intacto para garantir a sobrevivência do clone."
  },
  {
  "nome": "Controlar o Clima",
  "nivel": 8,
  "escola": "Transmutação",
  "classes": ["Clérigo", "Druida", "Mago"],
  "tempo_conjuracao": "10 minutos",
  "alcance": "Pessoal (raio de 8km [5 miles])",
  "componentes": "V S M (um incenso queimando e pedaços de terra e madeira misturados a água)",
  "duracao": "Concentração, até 8 horas",
  "descricao": "Você assume o controle do clima em uma área de 8 km de raio. As condições climáticas podem ser alteradas em três aspectos principais: precipitação, temperatura e vento. O DM determinará as condições atuais com base na estação do ano, e você pode mudar cada uma delas dentro dos estágios permitidos. Mudanças começam a surtir efeito após 1d4 x 10 minutos. Quando a magia terminar, o clima retornará gradualmente ao normal. As mudanças incluem:\n\n**Precipitação:**\n1. Claro\n2. Nuvens leves\n3. Nublado ou com neblina\n4. Chuva, granizo leve ou neve\n5. Chuva torrencial, tempestade de granizo ou nevasca\n\n**Temperatura:**\n1. Calor insuportável\n2. Quente\n3. Ameno\n4. Fresco\n5. Frio\n6. Frio ártico\n\n**Vento:**\n1. Calmo\n2. Moderado\n3. Vento Forte\n4. Ventania\n5. Tempestade\n\nVocê pode alterar cada uma dessas condições em um estágio, para cima ou para baixo. Ao mudar o vento, também pode escolher sua direção."
  },
  {
    "nome": "Dominar Monstro",
    "nivel": 8,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 hora",
    "descricao": "Você tenta cativar uma criatura à sua vista. Ela deve fazer uma salvaguarda de Sabedoria ou ficará enfeitiçada enquanto a magia durar. Você tem um elo telepático com a criatura e pode emitir comandos, que ela tentará obedecer. Caso a criatura seja danificada, ela faz uma nova salvaguarda para tentar resistir. Se conjurado com um espaço de 9º círculo, a duração é de até 8 horas."
  },
  {
    "nome": "Dragão Ilusório",
    "nivel": 8,
    "escola": "Ilusão",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "36m (120 ft.)",
    "componentes": "S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você cria um dragão ilusório em um espaço que você possa ver. Os inimigos que o veem devem fazer uma salvaguarda de Sabedoria ou ficarão amedrontados. Você pode mover a ilusão até 18 metros por turno e fazê-la exalar uma explosão de energia em um cone de 18 metros, causando 7d6 de dano (tipo escolhido: ácido, frio, fogo, elétrico, necrótico ou veneno) em uma falha ou metade em um sucesso. Criaturas que examinam a ilusão podem determinar que é uma ilusão com um teste de Inteligência (Investigação)."
  },
   {
    "nome": "Enfraquecer Intelecto",
    "nivel": 8,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Druida", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V S M (um punhado de argila, cristal, vidro ou esferas minerais)",
    "duracao": "Instantânea",
    "descricao": "Você assola a mente de uma criatura à sua vista, tentando despedaçar seu intelecto e personalidade. O alvo sofre 4d6 de dano psíquico e deve fazer uma salvaguarda de Inteligência. Se falhar, o valor de Inteligência e Carisma da criatura vai para 1, impossibilitando-a de conjurar magias, ativar itens mágicos, compreender idiomas ou se comunicar. Ela pode identificar amigos e até protegê-los. Após 30 dias, a criatura pode refazer a salvaguarda; em caso de sucesso, a magia se encerra. Pode ser anulada por Restauração Maior, Cura Completa ou Desejo."
  },
  {
    "nome": "Escuridão Elouquecedora",
    "nivel": 8,
    "escola": "Evocação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V M (uma gota de piche misturada com uma gota de mercúrio)",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você cria uma esfera de escuridão de 60 pés de raio que se espalha em torno dos cantos. Criaturas com visão no escuro não podem ver através dessa escuridão. Toda vez que uma criatura começa seu turno na esfera, ela deve fazer uma salvaguarda de Sabedoria, sofrendo 8d8 de dano psíquico em caso de falha, ou metade do dano em sucesso. A esfera também emite grunhidos, risos e balbucios perturbadores."
  },
  {
    "nome": "Explosão Solar",
    "nivel": 8,
    "escola": "Evocação",
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V S M (fogo e um pedaço de pedra-do-sol)",
    "duracao": "Instantânea",
    "descricao": "Você cria uma explosão de luz solar radiante em um raio de 18 metros (60 ft.). Criaturas na área devem fazer uma salvaguarda de Constituição. Se falharem, sofrem 12d6 de dano radiante e ficam cegas por 1 minuto. Criaturas bem-sucedidas recebem metade do dano e não ficam cegas. Mortos-vivos e gosmas têm desvantagem nesta salvaguarda."
  },
  {
    "nome": "Formas Animais",
    "nivel": 8,
    "escola": "Transmutação",
    "classes": ["Druida"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 24 horas",
    "descricao": "Você transforma outras criaturas em feras. Escolha qualquer número de criaturas voluntárias à sua vista. Cada alvo se torna uma fera Grande ou menor, com nível de desafio 4 ou menor. A transformação dura até 24 horas ou até que o alvo perca todos os pontos de vida. Os alvos podem usar ações para mudar de forma durante a duração da magia."
  },
  {
    "nome": "Fortaleza Poderosa",
    "nivel": 8,
    "escola": "Invocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "1 milha",
    "componentes": "V S M (um diamante de 500gp que é consumido)",
    "duracao": "Instantânea",
    "descricao": "Você cria uma fortaleza de pedra com 36m de lado. A fortaleza tem 4 torres de 9m de altura, conectadas por paredes de pedra de 24m de comprimento. Dentro da fortaleza, há um forte com 3 andares, mobiliado, com comida para até 100 pessoas por dia. Cem servos invisíveis são criados para ajudar nas tarefas. A fortaleza tem AC 15 e 30 pontos de vida por 3m de área, e é imune a veneno e dano psíquico. Ela desintegra após 7 dias ou ao conjurar a magia em outro local."
  },
  {
    "nome": "Labirinto",
    "nivel": 8,
    "escola": "Invocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você envia uma criatura para um semiplano labiríntico. O alvo deve fazer um teste de Inteligência com CD 20 para escapar. Criaturas como minotauros ou demônios goristros têm sucesso automático. Quando a magia termina, o alvo reaparece no espaço em que estava ou no mais próximo desocupado."
  },
  {
    "nome": "Limpar a Mente",
    "nivel": 8,
    "escola": "Abjuração",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "24 horas",
    "descricao": "Ao tocar uma criatura, você a torna imune a dano psíquico, a efeitos que leem ou influenciam seus pensamentos ou emoções, a magias de adivinhação e à condição de enfeitiçado. A magia também pode evitar efeitos de poder semelhante, incluindo Desejo."
  },
  {
    "nome": "Loquacidade",
    "nivel": 8,
    "escola": "Transmutação",
    "classes": ["Bardo", "Bruxo"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "1 hora",
    "descricao": "Enquanto a magia durar, quando você realizar um teste de Carisma, pode substituir o número tirado por 15. Além disso, qualquer magia que determine se você está dizendo a verdade indica que você está sendo honesto."
  },
  {
    "nome": "Murchamento Horrível de Abi-Dalzim",
    "nivel": 8,
    "escola": "Necromancia",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V S M (um pedaço de esponja)",
    "duracao": "Instantânea",
    "descricao": "Você suga a umidade de todas as criaturas em um cubo de 9m (30 ft.) centrado em um ponto à sua escolha. Cada criatura na área faz uma salvaguarda de Constituição. Se falhar, sofre 12d8 de dano necrótico, ou metade do dano em caso de sucesso. Plantas não mágicas na área morrem instantaneamente."
  },
  {
    "nome": "Nuvem Incendiária",
    "nivel": 8,
    "escola": "Invocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m (150 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Uma nuvem de fumaça que solta brasas quentes aparece em uma esfera de 6m (20 ft.). Cada criatura dentro deve fazer uma salvaguarda de Destreza. Se falhar, sofre 10d8 de dano ígneo, ou metade em caso de sucesso. A nuvem se move 3m (10 ft.) a cada turno."
  },
  {
    "nome": "Palavra de Poder: Atordoar",
    "nivel": 8,
    "escola": "Encantamento",
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você fala uma palavra de poder que atordoa uma criatura à sua vista com 150 pontos de vida ou menos. A criatura fica atordoada e deve fazer uma salvaguarda de Constituição no final de cada um de seus turnos para se libertar."
  },
  {
    "nome": "Semiplano",
    "nivel": 8,
    "escola": "Invocação",
    "classes": ["Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m (60 ft.)",
    "componentes": "S",
    "duracao": "1 hora",
    "descricao": "Você cria uma porta de sombras em uma superfície sólida que leva a um semiplano. O semiplano é um quarto vazio de 9m (30 ft.) de cada lado. A porta desaparece quando a magia termina, deixando qualquer criatura ou objeto dentro do semiplano preso."
  },
  {
    "nome": "Telepatia",
    "nivel": 8,
    "escola": "Evocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Ilimitado",
    "componentes": "V S M (um par de anéis de prata ligados)",
    "duracao": "24 horas",
    "descricao": "Você cria uma ligação telepática com uma criatura voluntária com quem esteja familiarizado. A comunicação é possível enquanto a magia durar e a criatura estiver no mesmo plano de existência."
  },
  {
    "nome": "Terremoto",
    "nivel": 8,
    "escola": "Evocação",
    "classes": ["Clérigo", "Druida", "Feiticeiro"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "150m (500 ft.)",
    "componentes": "V S M (uma pitada de sujeira, um pedaço de rocha e um pedaço de argila)",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você cria um tremor sísmico que afeta um raio de 30m (100 ft.). Criaturas que estejam concentrando devem fazer uma salvaguarda de Constituição. Além disso, fissuras se abrem e estruturas na área podem sofrer dano e colapsar."
  },
  {
    "nome": "Tsunami",
    "nivel": 8,
    "escola": "Invocação",
    "classes": ["Druida"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Visual",
    "componentes": "V S",
    "duracao": "Concentração, até 6 rodadas",
    "descricao": "Uma muralha de água surge em um ponto à sua escolha, com até 90m (300 ft.) de comprimento e 15m (50 ft.) de espessura. Criaturas na área devem fazer uma salvaguarda de Força. Elas sofrem 6d10 de dano contundente se falharem. A muralha se move 15m (50 ft.) a cada turno."
  }
]