magias_nivel_7 = [
  {
    "nome": "Bola de Fogo Adiável",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m",
    "componentes": "V S M (uma pequena bola de guano de morcego e enxofre)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Um facho de luz amarela dispara do seu dedo em riste, condensando-se na forma de uma conta brilhante num ponto escolhido dentro do alcance da magia por toda a duração. Quando a magia se encerra, seja porque sua concentração foi quebrada ou por decisão sua, a conta desabrocha, com um rugido baixo, em uma explosão de chamas que se alastram pelos cantos. Cada criatura em uma esfera com raio de 6 metros [20-foot-radius sphere] centrada na conta deve fazer uma salvaguarda de Destreza. Se falhar, sofre dano ígneo equivalente ao total acumulado de dano, ou metade do dano, em caso de sucesso. O dano base da magia é 12d6. Se ao final do seu turno a conta ainda não tiver sido detonada, o dano aumenta em 1d6. Se a conta brilhante for tocada antes que o intervalo expire, a criatura que a tocar precisa fazer uma salvaguarda de Destreza. Se falhar, a magia encerra imediatamente e a conta explode em chamas; se for bem-sucedida, a criatura pode arremessar a conta a até 12 metros [40 ft.] de distância. Se a conta atingir uma criatura ou objeto sólido, a magia se encerra e ela explode. O fogo danifica objetos na área e incendeia objetos inflamáveis que não estejam sendo usados ou carregados. Em Níveis Superiores: Ao conjurar esta magia usando um espaço de magia de 8º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 7º."
  },
  {
    "nome": "Cárcere de Energia",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Bardo", "Bruxo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "30m",
    "componentes": "V S M (pó de rubi, cujo valor mínimo seja de 1.500 PO)",
    "duracao": "Uma hora",
    "descricao": "Uma prisão com a forma de um cubo invisível e imóvel, composta de força mágica, surge ao redor de uma área à sua escolha e no alcance da magia. Ela pode ser uma jaula ou uma caixa sólida, à sua escolha. A jaula pode ter até 6 metros [20 ft.] de lado, sendo feita de barras de 1,5 centímetros [1/2 inch] de espessura com espaços de 1,5 centímetros [1/2 inch] entre elas. A caixa pode ter 3 metros [10 ft.] de lado e cria uma barreira sólida que impede qualquer matéria de passar através dela, bloqueando quaisquer magias conjuradas dentro ou fora da área. Quando a magia é conjurada, qualquer criatura que estiver completamente dentro da área afetada fica aprisionada. Criaturas que estejam apenas parcialmente na área, ou que sejam grandes demais para caber dentro da área, são empurradas para longe do centro da área, até ficarem completamente fora dela. Uma criatura dentro da prisão não pode deixá-la por meios não-mágicos. Se a criatura tenta usar alguma forma de teleporte ou viagem extraplanar para sair da prisão, precisa primeiro fazer uma salvaguarda de Carisma. Se falhar, ela não pode sair e desperdiça o uso da magia ou efeito; se for bem-sucedida, ela pode usar a magia para deixar a prisão. A prisão também se estende ao Plano Etéreo, bloqueando viagens etéreas. Esta magia não pode ser dissipada por Dissipar Magia."
  },
  {
    "nome": "Cerveja Cáustica de Tasha",
    "nivel": 7,
    "escola": "Invocação",
    "classes": ["Bruxo", "Bardo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "6m",
    "componentes": "V S M (um item mágico ou criatura voluntária no mundo de destino)",
    "duracao": "6 horas",
    "descricao": "Você e até oito criaturas voluntárias dentro do alcance caem inconsciente pela duração da magia, e vivenciam visões de outro mundo no Plano Material, como Oerth, Toril, Krynn, ou Eberron. Se a magia alcançar sua duração completa, as visões se encerram com cada um dos afetados encontrando e abrindo uma misteriosa cortina azul. A magia então acaba com todos sendo física e mentalmente teletransportados para o mundo que testemunharam nas visões. Para conjurar essa magia, você deve ter um item mágico originário do mundo que deseja alcançar, e deve estar consciente da existência desse mundo, mesmo que não saiba o nome dele. Seu destino no outro mundo é um local seguro a até 1,5km [1 mile] de distância de onde o item foi criado. Alternativamente, você pode conjurar a magia se uma das criaturas afetadas nasceu em outro mundo, o que faz seu destino ser um local seguro a até 1,5km de onde a criatura nasceu. A magia termina antecipadamente para uma criatura se ele receber qualquer dano, e então ela não é teletransportada. Se você receber dano, a magia se encerra para você e para todos os outros, com nenhum de vocês sendo teletransportado."
  },
  {
    "nome": "Coroa de Estrelas",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Uma hora",
    "descricao": "Sete partículas aparentadas a estrelas aparecem e orbitam sua cabeça até a magia terminar. Você pode usar uma ação bônus para disparar uma das partículas contra uma criatura ou objeto a menos de 36m [120 ft.] de você. Quando fizer isso, faça um ataque a distância com magia. Em um sucesso, o alvo leva 4d12 de dano radiante. Indiferentemente de se você acertar ou errar, a partícula é gasta. A magia termina mais cedo se você gastar a última partícula. Se você tiver quatro ou mais partículas restando, elas emanam luz brilhante em um raio de 9m [30-foot radius] e de luz fraca mais 9m [30 ft.]. Se você tiver de uma a três partículas restantes, elas emanam luz fraca em um raio de 9m [30-foot radius]. Em Níveis Superiores: Quando você conjura essa magia usando um espaço de magia de 8º círculo ou superior, o número de partículas criadas aumenta em 2 para cada nível do espaço de magia acima do 4º."
  },
  {
    "nome": "Dedo da Morte",
    "nivel": 7,
    "escola": "Necromancia",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você descarrega energia negativa em uma criatura à sua vista e no alcance da magia, causando-lhe fortes dores. O alvo deve fazer uma salvaguarda de Constituição. Se falhar, sofre 7d8+30 pontos de dano necrótico, ou metade do dano em caso de sucesso. Um humanoide morto por esta magia levanta-se, no início do seu próximo turno, como um zumbi que está permanentemente sob o seu comando, seguindo suas ordens verbais da melhor forma possível."
  },
  {
    "nome": "Espada de Mordenkainen",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m",
    "componentes": "V S M (uma miniatura em platina de uma espada, com o pomo e o cabo de cobre e zinco, no valor de 250 PO)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você cria energia moldada na forma de uma espada, que paira dentro do alcance da magia. Ela fica ativa enquanto a magia durar. Quando a espada aparece, você faz um ataque mágico corpo a corpo contra um alvo à sua escolha no alcance de 1,5 metro [5 ft.] da espada. Ao desferir um ataque bem-sucedido, o alvo sofre 3d10 pontos de dano energético. Enquanto a magia durar, você pode usar uma ação bônus em cada um de seus turnos para movê-la até 6 metros [20 ft.] para um local à sua vista, repetindo esse ataque contra o mesmo alvo ou outro."
  },
  {
    "nome": "Forma Etérea",
    "nivel": 7,
    "escola": "Transmutação",
    "classes": ["Bardo", "Bruxo", "Clérigo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "8 horas",
    "descricao": "Você adentra as regiões fronteiriças de Plano Etéreo, na área onde ele se sobrepõe ao seu plano atual. Você permanece na Fronteira Etérea enquanto a magia durar ou até que você use sua ação para dispensar a magia. Durante esse tempo, você pode se mover em qualquer direção. Se você se mover para cima ou para baixo, cada 0,3 metro [1 foot] de deslocamento custa 0,6 metro [2 ft.]. Você pode ver e ouvir o plano do qual é originário, mas tudo parece cinza e nada pode ser visto a mais de 18 metros [60 ft.] de distância. Enquanto estiver no Plano Etéreo, você só pode afetar e ser afetado por outras criaturas nesse plano. Criaturas que não estejam no Plano Etéreo não podem percebê-lo e nem interagir com você, a menos que uma habilidade especial ou mágica lhes dê essa capacidade. Você ignora todos os objetos e efeitos que não estejam no Plano Etéreo, o que lhe permite mover-se através de objetos que você perceba no plano do qual é originário. Ao término da magia, você retorna imediatamente ao seu plano de origem, no lugar que está ocupando no momento. Se ocupar o mesmo lugar de um objeto ou criatura quando isso acontecer, você é imediatamente desviado para o espaço desocupado mais próximo que puder ocupar, sofrendo 10 pontos de dano energético a cada 1,5 metro [5 ft.] percorrido. Esta magia não tem nenhum efeito se você conjurá-la enquanto estiver no Plano Etéreo ou em um plano que não faça fronteira com ele, como um dos Planos Externos. Em Níveis Superiores: Ao conjurar esta magia usando um espaço de magia de 8º círculo ou superior, você pode atingir até três criaturas (incluindo você mesmo) para cada círculo do espaço acima do 7º. As criaturas devem estar a até 3 metros [10 ft.] de você quando esta magia for conjurada."
  },
  {
    "nome": "Inverter a Gravidade",
    "nivel": 7,
    "escola": "Transmutação",
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "30m",
    "componentes": "V S M (um magnetita e limalhas de ferro)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Esta magia inverte a gravidade numa área de 15 metros de raio e 30 metros de altura, formando um cilindro [50-foot-radius, 100-foot high cylinder] centrado em um ponto no alcance da magia. Todas as criaturas e objetos que não estão, de alguma forma, ancorados ao solo nessa área, 'caem' para cima e alcançam o topo da área quando a magia é conjurada. Uma criatura pode fazer uma salvaguarda de Destreza para se agarrar a um objeto fixo que possa alcançar, evitando a queda. Se algum objeto sólido (como um teto) for encontrado durante esta queda, criaturas e objetos caindo se chocam contra ele, como fariam durante uma queda normal para baixo. Se um objeto ou criatura atingir o topo da área sem bater em nada, ele permanece lá, oscilando ligeiramente, enquanto a magia durar. Ao final da duração, objetos e criaturas afetados caem de volta para baixo."
  },
  {
    "nome": "Invocar Celestial",
    "nivel": 7,
    "escola": "Invocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "27m [90 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você invoca um celestial com nível de desafio 4 ou menor, que surge em um espaço desocupado à sua vista e no alcance da magia. O celestial desaparece ao atingir 0 pontos de vida ou ao término da magia. O celestial é amistoso com você e seus companheiros enquanto durar a magia. Jogue a iniciativa para o celestial, que tem seus próprios turnos. O celestial obedece a qualquer comando verbal que você lhe direcione (não requer ação sua), desde que isso não viole o alinhamento dele. Caso não seja dado comando algum, ele se defende de seres hostis, não executando nenhuma outra ação. O DM fornece as estatísticas do celestial."
  },
  {
    "nome": "Mansão Magnífica de Mordenkainen",
    "nivel": 7,
    "escola": "Invocação",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "90m [300 ft.]",
    "componentes": "V S M (um portal em miniatura esculpido em marfim, um pedaço pequeno de mármore polido e uma diminuta colher de prata, cada item com valor mínimo de 5 PO)",
    "duracao": "24 horas",
    "descricao": "Você conjura uma habitação extradimensional, no alcance da magia e que permanece enquanto esta durar. A entrada brilha fracamente e possui 1,5 metro [5 ft.] de largura e 3 metros [10 ft.] de altura. Você e qualquer criatura que designar ao conjurar a magia podem entrar na habitação extradimensional enquanto o portal permanecer aberto. O ambiente é limpo, fresco e aquecido, e você pode criar qualquer projeto desejado. A habitação contém comida suficiente para servir um banquete de nove pratos para até 100 pessoas e uma equipe de 100 servos semi-transparentes."
  },
  {
    "nome": "Miragem Arcana",
    "nivel": 7,
    "escola": "Ilusão",
    "classes": ["Bardo", "Druida", "Mago"],
    "tempo_conjuracao": "10 minutos",
    "alcance": "Linha de visão",
    "componentes": "V S",
    "duracao": "10 dias",
    "descricao": "Você faz o terreno em uma área de até 1,5 quilômetro quadrado parecer, soar, cheirar e até passar a sensação de que é outro tipo de terreno. A ilusão inclui elementos audíveis, visuais, táteis e olfativos, e pode alterar a aparência de estruturas ou adicionar novas. Criaturas com visão verdadeira podem ver através da ilusão, mas os outros efeitos continuam a funcionar. Qualquer pedaço do terreno ilusório que seja removido desaparece imediatamente."
  },
  {
    "nome": "Palavra de Poder Dor",
    "nivel": 7,
    "escola": "Encantamento",
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você fala uma palavra de poder que causa ondas de dor intensa em uma criatura com 100 pontos de vida ou menos, causando dor incapacitante. A dor paralisa o alvo, diminuindo sua velocidade e impondo desvantagem em rolagens de ataque e testes de habilidade, exceto em salvaguardas de Constituição. O alvo pode tentar se livrar da dor com uma salvaguarda de Constituição no final de cada um de seus turnos."
  },
  {
    "nome": "Palavra Sagrada",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Clérigo"],
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "9m [30 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você profere uma palavra sagrada que causa efeitos devastadores em criaturas com baixa quantidade de pontos de vida. Dependendo dos pontos de vida da criatura, ela pode ficar surda, cega, atordoada ou até morta instantaneamente. Além disso, qualquer celestial, elemental, feérico ou ínfero que falhe na salvaguarda é forçado a voltar para seu plano de origem por 24 horas."
  },
  {
    "nome": "Projetar Imagem",
    "nivel": 7,
    "escola": "Ilusão",
    "classes": ["Bardo", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "800km [500 miles]",
    "componentes": "V S M (uma pequena réplica de você feita com materiais no valor mínimo de 5 PO)",
    "duracao": "Concentração, Até 1 dia",
    "descricao": "Você cria uma cópia ilusória de si mesmo que pode ser projetada em qualquer local que você já tenha visto dentro do alcance da magia. A cópia é intangível e se comporta como você, mas se for danificada, desaparece. Você pode usar os sentidos da cópia como se estivesse em seu espaço, mas interagir fisicamente com a cópia revela que ela é uma ilusão."
  },
  {
    "nome": "Rajada Prismática",
    "nivel": 7,
    "escola": "Evocação",
    "classes": ["Feiticeiro", "Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cone de 18m [60 ft.])",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Oito raios de luz multicoloridos saem da sua mão, afetando as criaturas no cone. Cada raio causa um tipo diferente de dano (ígneo, ácido, elétrico, venenoso, gélido, etc.) ou impõe um efeito como contensão, cegueira, ou transporte para outro plano de existência, dependendo do tipo do raio que atingir o alvo."
  },
  {
    "nome": "Refugiar",
    "nivel": 7,
    "escola": "Transmutação",
    "classes": ["Mago"],
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um pó composto de poeira de diamante, esmeralda, rubi e safira no valor mínimo de 5.000 PO, que a magia consome)",
    "duracao": "Até ser dissipada",
    "descricao": "Você esconde uma criatura ou objeto, tornando-o invisível e livre de detecção. A criatura cai em animação suspensa, e o tempo para ela não passa, ficando imune aos efeitos do envelhecimento. A magia pode ser encerrada sob uma condição definida, ou se o alvo sofrer dano."
  },
   {
    "nome": "Regeneração",
    "nivel": 7,
    "escola": "Transmutação",
    "classes": ["Bardo", "Clérigo", "Druida"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Toque",
    "componentes": "V S M (uma roda de oração e água benta)",
    "duracao": "1 hora",
    "descricao": "Você toca uma criatura e estimula sua capacidade natural de cura. O alvo recupera 4d8 + 15 pontos de vida. Durante a duração, o alvo recupera 1 ponto de vida por turno. Membros amputados são restaurados após 2 minutos. Se o membro for recolocado, a magia instantaneamente reconecta-o."
  },
  {
    "nome": "Ressurreição",
    "nivel": 7,
    "escola": "Necromancia",
    "classes": ["Bardo", "Clérigo"],
    "tempo_conjuracao": "1 hora",
    "alcance": "Toque",
    "componentes": "V S M (um diamante de valor mínimo de 1.000 PO)",
    "duracao": "Instantânea",
    "descricao": "Você toca uma criatura morta há menos de um século, que não morreu de causas naturais e não é um morto-vivo. A alma deve estar livre e disposta. A criatura retorna à vida com todos os pontos de vida. Veneno e doenças normais são curados, mas maldições ou doenças mágicas não. A criatura sofre -4 em todas as jogadas de ataque, salvaguardas e testes de atributo até completar um descanso longo, quando a penalidade diminui em 1. Se a morte foi há mais de um ano, o conjurador não pode usar magias até completar um descanso longo."
  },
  {
    "nome": "Símbolo",
    "nivel": 7,
    "escola": "Abjuração",
    "classes": ["Bardo", "Clérigo", "Mago"],
    "tempo_conjuracao": "1 minuto",
    "alcance": "Toque",
    "componentes": "V S M (mercúrio, fósforo, pó de diamante e opala de valor mínimo de 1.000 PO)",
    "duracao": "Até ser dissipada ou disparada",
    "descricao": "Você traça um glifo mágico em uma superfície ou objeto. O símbolo pode ser ativado por um gatilho que você define. Quando ativado, uma esfera de 18 metros (60 ft.) de raio emana uma luz fraca, afetando qualquer criatura dentro dela ou que entre nela. Efeitos possíveis: Atordoamento (salv. de Sabedoria), Desesperança (salv. de Carisma), Discórdia (salv. de Constituição), Dor (salv. de Constituição), Insanidade (salv. de Inteligência), Medo (salv. de Sabedoria), Morte (salv. de Constituição) e Sono (salv. de Sabedoria)."
  },
{
  "nome": "Teleporte",
  "nivel": 7,
  "escola": "Invocação",
  "classes": ["Bardo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "3m (10 ft.)",
  "componentes": "V",
  "duracao": "Instantânea",
  "descricao": "Você transporta você e até oito criaturas voluntárias ou um objeto, até um destino conhecido no mesmo plano. O DM joga um d100 para determinar o sucesso com base na familiaridade com o destino: 'Círculo Permanente' (sucesso garantido), 'Objeto Associado', 'Muito Familiar', 'Visto Casualmente', 'Visto uma vez', 'Descrição', ou 'Destino Falso'. Dependendo da familiaridade, os resultados podem ser: 'No Alvo' (chegada correta), 'Fora do Alvo' (deslocamento aleatório de 1d10 x 1d10 % da distância), 'Área Similar' (local similar ao destino) e 'Azar' (dano de 3d10 e nova falha)."
},
{
  "nome": "Simulacro",
  "nivel": 7,
  "escola": "Ilusão",
  "classes": ["Mago"],
  "tempo_conjuracao": "12 horas",
  "alcance": "Toque",
  "componentes": "V S M (neve ou gelo suficientes para criar uma cópia de tamanho idêntico ao da criatura duplicada; algum cabelo, lascas de unhas e outra parte do corpo da criatura, que são colocados dentro da neve ou gelo, e rubi em pó no valor mínimo de 1.500 PO salpicado sobre a duplicata, que a magia consome)",
  "duracao": "Até ser dissipada",
  "descricao": "Você cria uma duplicata ilusória de uma criatura que esteja no alcance durante a conjuração. A duplicata tem metade dos pontos de vida da original e sem equipamentos. Ela age como a original, mas é um constructo e não pode aprender ou evoluir. O simulacro é amigável e obedece suas ordens, mas não pode recuperar pontos de vida naturalmente. Pode ser reparado com ervas e minerais no valor de 100 PO por ponto de vida restaurado. Se a magia for repetida, qualquer duplicata ativa é destruída."
},
{
  "nome": "Tempestade de Fogo",
  "nivel": 7,
  "escola": "Evocação",
  "classes": ["Clérigo", "Druida", "Feiticeiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "45m (150 ft.)",
  "componentes": "V S",
  "duracao": "Instantânea",
  "descricao": "Você cria uma tempestade de chamas em uma área de até 10 cubos de 3 metros [10-foot cubes], que pode ser disposta como desejar. Cada cubo deve ter pelo menos uma face adjacente a outro. Cada criatura na área deve fazer uma salvaguarda de Destreza. Se falhar, sofre 7d10 de dano ígneo, ou metade desse dano em caso de sucesso. A tempestade também incendeia objetos inflamáveis e danifica objetos na área, podendo excluir vegetação do efeito da magia."
},
{
  "nome": "Templo dos Deuses",
  "nivel": 7,
  "escola": "Invocação",
  "classes": ["Clérigo"],
  "tempo_conjuracao": "Uma hora",
  "alcance": "36m [120 ft.]",
  "componentes": "V S M (um símbolo sagrado valendo, no mínimo, 5gp)",
  "duracao": "24 horas",
  "descricao": "Você faz com que um templo apareça em uma área que você possa ver dentro do alcance. O templo é dedicado a um deus, panteão ou filosofia e pode ter a aparência que você desejar. O interior inclui um ídolo ou altar e você decide a iluminação e temperatura. O templo protege contra certos tipos de criaturas (como celestiais, demônios, mortos-vivos, etc.), impedindo sua entrada ou dificultando suas ações dentro do templo. Criaturas dentro do templo que recebem cura mágica também ganham pontos de vida extras. O templo é resistente a ataques mágicos e não pode ser dissipado por magias comuns. Pode ser permanecido se a magia for repetida no mesmo local por um ano."
},
{
  "nome": "Transição Planar",
  "nivel": 7,
  "escola": "Invocação",
  "classes": ["Bruxo", "Clérigo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (um bastão de metal bifurcado no valor mínimo de 250 PO, sintonizado com um determinado plano de existência)",
  "duracao": "Instantânea",
  "descricao": "Você e até oito criaturas voluntárias podem ser transportadas para um plano de existência diferente. Você pode escolher um destino geral ou usar a sequência de símbolos de um círculo de teleporte para um plano específico. Se você usar a magia para banir uma criatura involuntária, ela deve fazer uma salvaguarda de Carisma. Se falhar, é transportada para um plano aleatório. Uma criatura transportada de forma involuntária terá que encontrar o caminho de volta ao seu plano original."
},
{
  "nome": "Vendaval",
  "nivel": 7,
  "escola": "Evocação",
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "90m [300 ft.]",
  "componentes": "V M (um chumaço de palha)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Você cria um vendaval em um ponto do solo, com um raio de 3m [10 ft.] e altura de 9m [30 ft.]. O vendaval pode ser movido até 9m [30 ft.] em qualquer direção. Criaturas que entram no vendaval ou nele começam seu turno devem realizar uma salvaguarda de Destreza, sofrendo 10d6 de dano contundente em caso de falha. Criaturas grandes ou menores que falharem também devem realizar uma salvaguarda de Força ou serão impedidas de se mover. Criaturas impedidas podem ser puxadas para dentro do vendaval e caem quando a magia terminar, a menos que consigam manter-se no ar."
},
]
