magias_nivel_4 = [
  {
    "nome": "Arca Secreta de Leomund",
    "nivel": 4,
    "escola": "Invocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "Toque",
    "componentes": "V S M (baú requintado de 5.000 PO e réplica de 50 PO)",
    "duracao": "Instantânea",
    "descricao": "Você esconde uma arca e seu conteúdo no Plano Etéreo. Pode evocá-la ou devolvê-la tocando a réplica. Após 60 dias, há 5% de chance cumulativa por dia da magia acabar. Se a arca estiver no Plano Etéreo quando isso acontecer, ela é perdida para sempre."
  },
  {
    "nome": "Assassino Fantasmagórico",
    "nivel": 4,
    "escola": "Ilusão",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "36m (120 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você invoca os pesadelos de uma criatura. Se ela falhar na salvaguarda de Sabedoria, fica amedrontada. No fim de cada turno, faz nova salvaguarda: se falhar, sofre 4d10 de dano psíquico; se passar, a magia termina. Em níveis superiores: +1d10 por círculo acima do 4º."
  },
  {
    "nome": "Aura de Devoção",
    "nivel": 4,
    "escola": "Abjuração",
    "classes": ["Paladino"],
    "tempo_conjuracao": "1 ação",
    "alcance": "Pessoal (raio de 9m)",
    "componentes": "V",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Você irradia uma aura de energia vital. Criaturas não hostis na área têm resistência a dano necrótico, não têm seus PVs máximos reduzidos e recuperam 1 PV ao começar o turno com 0 PV dentro da aura."
  },
  {
    "nome": "Aura de Pureza",
    "nivel": 4,
    "escola": "Abjuração",
    "classes": ["Paladino"],
    "tempo_conjuracao": "1 ação",
    "alcance": "Pessoal (raio de 9m)",
    "componentes": "V",
    "duracao": "Concentração, até 10 minutos",
    "descricao": "Uma aura purificante se irradia de você. Criaturas não hostis na área não ficam doentes, têm resistência a dano venenoso e vantagem em salvaguardas contra várias condições como medo, envenenamento, paralisia e cegueira."
  },
  {
    "nome": "Banimento",
    "nivel": 4,
    "escola": "Abjuração",
    "classes": ["Bruxo", "Clérigo", "Feiticeiro", "Mago", "Paladino"],
    "tempo_conjuracao": "1 ação",
    "alcance": "18m (60 ft.)",
    "componentes": "V S M (item desagradável)",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Você tenta banir uma criatura. Se falhar na salvaguarda de Carisma, é enviada para um plano diferente. Se for nativa do plano atual, vai a um semiplano e retorna ao fim. Se for de outro plano, é enviada de volta e só retorna se a magia acabar antes de 1 minuto. Em níveis superiores: +1 criatura por círculo acima do 4º."
  },
  {
    "nome": "Cão Fiel de Mordenkainen",
    "nivel": 4,
    "escola": "Invocação",
    "classes": ["Mago"],
    "tempo_conjuracao": "1 ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S M (apito de prata, osso e fio)",
    "duracao": "8 horas",
    "descricao": "Você invoca um cão invisível e invulnerável que late quando uma criatura se aproxima sem dizer a senha. Ele enxerga invisíveis e o Plano Etéreo. No início do turno, morde inimigos a até 1,5m, causando 4d8 de dano perfurante com seu modificador de conjuração e proficiência."
  },
  {
    "nome": "Compulsão",
    "nivel": 4,
    "escola": "Encantamento",
    "classes": ["Bardo"],
    "tempo_conjuracao": "1 ação",
    "alcance": "9m (30 ft.)",
    "componentes": "V S",
    "duracao": "Concentração, até 1 minuto",
    "descricao": "Criaturas à sua escolha que possam ouvi-lo fazem salvaguarda de Sabedoria. Se falharem, você pode usar uma ação bônus para forçá-las a se moverem em uma direção horizontal no turno seguinte, usando o máximo de deslocamento. Elas podem agir antes de se mover. Podem repetir a salvaguarda após o movimento para encerrar o efeito. O movimento provoca ataques de oportunidade, mas não as força a entrar em perigos óbvios."
  },
{
  "nome": "Confusão",
  "nivel": 4,
  "escola": "Encantamento",
  "classes": ["Bardo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "27m (90 ft.)",
  "componentes": "V S M (três cascas de noz)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Esta magia distorce a mente das criaturas em uma esfera de 3m de raio centrada em um ponto à sua escolha. Cada criatura na área faz uma salvaguarda de Sabedoria ou será afetada. Alvos afetados não podem usar reações e, no início de cada turno, rolam 1d10 para determinar seu comportamento:\n\n1: Move-se totalmente em direção aleatória, sem ação.\n2–6: Não realiza ação nem se move.\n7–8: Usa ação para atacar corpo a corpo uma criatura aleatória próxima (ou não faz nada se não houver nenhuma).\n9–10: Age e se move normalmente.\n\nAo final de cada turno, o alvo faz uma nova salvaguarda de Sabedoria para encerrar o efeito.\n\nEm Níveis Superiores: Ao conjurar com espaço de 5º círculo ou superior, o raio aumenta em 1,5m para cada círculo acima do 4º."
},
{
  "nome": "Controlar Água",
  "nivel": 4,
  "escola": "Transmutação",
  "classes": ["Clérigo", "Druida", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "90m (300 ft.)",
  "componentes": "V S M (uma gota de água e uma pitada de poeira)",
  "duracao": "Concentração, até 10 minutos",
  "descricao": "Você controla um corpo de água parada dentro de um cubo de 30m. Você escolhe um dos efeitos: Inundação: a água sobe até 6m ou forma uma onda de 6m que empurra veículos (25% de chance de emborcar). A onda reaparece a cada turno enquanto durar o efeito. Dividir a Água: a água se separa formando uma trincheira, que dura até o efeito mudar; depois se fecha. Redirecionar Fluxo: muda a direção do fluxo da água, que volta ao normal ao sair da área. Redemoinho: cria um vórtice (1,5m base, 15m topo, 7,5m altura). Criaturas a até 7,5m são puxadas 3m. Salvaguarda de Força: falha = 2d8 de dano e ficam presas; sucesso = metade do dano. Presos podem tentar sair com ação (Atletismo, desvantagem). Objetos sofrem 2d8 por rodada enquanto estiverem no vórtice."
},
{
  "nome": "Defensor da Fé",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Clérigo"],
  "tempo_conjuracao": "1 ação",
  "alcance": "9m (30 ft.)",
  "componentes": "V",
  "duracao": "8 horas",
  "descricao": "Uma sentinela espectral aparece num espaço desocupado à vista, dentro do alcance. Qualquer criatura hostil que entre a até 3m dela pela 1ª vez num turno deve fazer salvaguarda de Destreza. Se falhar, sofre 20 de dano radiante, ou metade em sucesso. A sentinela desaparece após causar 60 de dano."
},
{
  "nome": "Destruição Atordoante",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Paladino"],
  "tempo_conjuracao": "1 ação bônus",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Ao acertar um ataque corpo a corpo, você causa 4d6 de dano psíquico extra. O alvo faz salvaguarda de Sabedoria. Se falhar, tem desvantagem em ataques e testes de atributo, e não pode usar reações até o fim do próximo turno dele."
},
{
  "nome": "Destruição Elemental",
  "nivel": 4,
  "escola": "Transmutação",
  "classes": ["Bruxo", "Druida", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "27m (90 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Escolha uma criatura e um tipo de dano: ácido, frio, fogo, elétrico ou trovejante. Se falhar na salvaguarda de Constituição, sofre 2d6 extras ao receber dano do tipo escolhido e perde resistências contra ele. Em níveis superiores, afeta mais criaturas."
},
{
  "nome": "Dominar Fera",
  "nivel": 4,
  "escola": "Encantamento",
  "classes": ["Druida", "Feiticeiro"],
  "tempo_conjuracao": "1 ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Tente enfeitiçar uma fera à vista. Se falhar na salvaguarda de Sabedoria, você controla suas ações telepaticamente. Você pode tomar controle total como ação. Ao sofrer dano, faz nova salvaguarda para encerrar o efeito. Em níveis superiores, aumenta a duração."
},
{
  "nome": "Encontrar Montaria Maior",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Paladino"],
  "tempo_conjuracao": "10 minutos",
  "alcance": "9m (30 ft.)",
  "componentes": "V S",
  "duracao": "Instantânea",
  "descricao": "Você convoca um espírito como grifo, pegasus, rinoceronte ou similar. A criatura é leal, inteligente (mínimo 6), entende um idioma seu e é celestial, fada ou demônio. Pode se comunicar telepaticamente com você a até 1,6km. Desaparece ao cair a 0 PV e pode ser reconjurada."
},
{
  "nome": "Enfeitiçar Monstro",
  "nivel": 4,
  "escola": "Encantamento",
  "classes": ["Bardo", "Bruxo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "9m (30 ft.)",
  "componentes": "V S",
  "duracao": "1 hora",
  "descricao": "Encanta uma criatura à vista. Ela faz salvaguarda de Sabedoria com vantagem se estiver em combate com você. Se falhar, fica amigável enquanto a magia durar. Quando a magia acaba, a criatura sabe que foi enfeitiçada. Em níveis superiores, afeta alvos adicionais."
},
{
  "nome": "Escudo Ardente",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "Pessoal",
  "componentes": "V S M (fósforo ou vaga-lume)",
  "duracao": "10 minutos",
  "descricao": "Você se cerca de chamas que brilham por 3m. Escolha escudo ígneo (resistência a frio) ou escudo gélido (resistência a fogo). Se for acertado por ataque corpo a corpo a 1,5m, o atacante sofre 2d8 de dano do tipo do escudo."
},
{
  "nome": "Esfera Aquosa",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "27m (90 ft.)",
  "componentes": "V S M (gota de água)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Cria uma esfera de água flutuante de 3m de raio. Criaturas na área fazem salvaguarda de Força ou ficam presas. A esfera pode mover até 9m por ação e transportar criaturas presas. Pode conter até 4 criaturas Médias. Ao acabar, extingue chamas a até 9m."
},
{
  "nome": "Esfera Cáustica",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "45m (150 ft.)",
  "componentes": "V S M (bile de lesma gigante)",
  "duracao": "Instantânea",
  "descricao": "Você lança uma esfera de ácido que explode em um raio de 6m. Criaturas na área fazem salvaguarda de Destreza. Falha causa 10d4 de dano de ácido e mais 5d4 no fim do próximo turno. Sucesso reduz à metade e ignora o dano posterior. Em níveis superiores, aumenta o dano inicial."
},
{
  "nome": "Esfera Resiliente de Otiluke",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "9m (30 ft.)",
  "componentes": "V S M (cristal e goma arábica)",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Uma esfera impenetrável envolve uma criatura ou objeto. Nada entra ou sai da esfera, mas quem está dentro pode respirar. A esfera é imune a danos e pode ser movida. Uma criatura presa pode rolar a esfera. Desintegrar a destrói sem afetar o conteúdo."
},
{
  "nome": "Esfera Tempestuosa",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "45m (150 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, até 1 minuto",
  "descricao": "Cria uma esfera de 6m de raio de vento forte. Criaturas dentro dela sofrem 2d6 de dano contundente se falharem na salvaguarda. Você pode usar uma ação bônus para lançar relâmpago (4d6 elétrico) em alvos a até 18m do centro. Cria desvantagem em Percepção auditiva."
},
{
"nome": "Fabricar",
"nivel": 4,
"escola": "Evocação",
"classes": ["Artífice", "Mago"],
"tempo_conjuracao": "10 minutos",
"alcance": "36m (120 ft.)",
"componentes": "V S",
"duracao": "Instantânea",
"descricao": "Transforma matérias-primas em produtos do mesmo material, como madeira em ponte, cânhamo em corda, etc. Pode criar objetos Grandes (ou Médios se forem de pedra ou metal) visíveis e dentro do alcance, contanto que tenha matéria-prima suficiente. A qualidade do objeto depende do material usado. Não cria criaturas, itens mágicos ou itens complexos sem a proficiência adequada."
},
{
"nome": "Guardião da Natureza",
"nivel": 4,
"escola": "Transmutação",
"classes": ["Druida", "Patrulheiro"],
"tempo_conjuracao": "Uma ação bônus",
"alcance": "Pessoal",
"componentes": "V",
"duracao": "Concentração, até 1 minuto",
"descricao": "Você assume a forma de Fera Primitiva ou Grande Árvore. Fera: +3m de deslocamento, visão no escuro (36m), ataques com Força com vantagem, dano extra 1d6. Árvore: +10 PV temporários, testes de Constituição com vantagem, ataques com Destreza/Sabedoria com vantagem, terreno difícil a 4,5m para inimigos."
},
{
"nome": "Inseto Gigante",
"nivel": 4,
"escola": "Transmutação",
"classes": ["Druida"],
"tempo_conjuracao": "Uma ação",
"alcance": "9m (30 ft.)",
"componentes": "V S",
"duracao": "Concentração, até 10 minutos",
"descricao": "Transforma até 10 insetos (ex: centopeias, vespas, aranhas ou escorpiões) em suas versões gigantes. Eles obedecem seus comandos e agem no mesmo turno que você. Mantêm-se transformados até o fim da magia, serem reduzidos a 0 PV ou serem dispensados. O DM fornece as estatísticas e pode permitir variantes semelhantes."
},
{
"nome": "Invisibilidade Maior",
"nivel": 4,
"escola": "Ilusão",
"classes": ["Bardo", "Feiticeiro", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "Toque",
"componentes": "V S",
"duracao": "Concentração, até 1 minuto",
"descricao": "Você ou uma criatura tocada torna-se invisível enquanto a magia durar. Qualquer item carregado ou vestido pelo alvo também se torna invisível, desde que esteja em contato com ele."
},
{
"nome": "Invocação Aberração",
"nivel": 4,
"escola": "Invocação",
"classes": ["Artífice", "Feiticeiro", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "27m (90 ft.)",
"componentes": "V S M (tentáculo e globo ocular em frasco de platina, 400 PO)",
"duracao": "Concentração, 1 hora",
"descricao": "Invoca um Espírito Aberrante (tipo: Observador, Slaad ou Prole Estelar). A criatura é aliada e age logo após você na iniciativa. Obedece comandos verbais; se não receber, se esquiva. Some ao chegar a 0 PV ou ao fim da magia. Em níveis superiores, usa o nível do espaço no bloco de estatísticas."
},
{
"nome": "Invocar Constructo",
"nivel": 4,
"escola": "Invocação",
"classes": ["Artífice", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "27m (90 ft.)",
"componentes": "V S M (pedra ornamentada e cofre, 400 PO)",
"duracao": "Concentração, 1 hora",
"descricao": "Invoca um Espírito Mecânico (argila, metal ou pedra). A criatura é aliada e age logo após você. Obedece comandos verbais, ou se esquiva. Some ao chegar a 0 PV ou ao fim da magia. Em níveis superiores, usa o nível do espaço no bloco de estatísticas."
},
{
"nome": "Invocar Demônio Maior",
"nivel": 4,
"escola": "Invocação",
"classes": ["Bruxo", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "18m (60 ft.)",
"componentes": "V S M (frasco com sangue de humanoide morto há menos de 24h)",
"duracao": "Concentração, até 1 hora",
"descricao": "Convoca um demônio (CD 5 ou menor). Você o comanda verbalmente, mas ele pode se rebelar com salvaguardas de Carisma ao fim de cada turno. Pode traçar círculo de proteção com o sangue. Em níveis superiores, a CD do demônio aumenta em 1 por nível acima do 4º."
},
{
"nome": "Invocar Elementais Menores",
"nivel": 4,
"escola": "Invocação",
"classes": ["Druida", "Mago"],
"tempo_conjuracao": "1 minuto",
"alcance": "27m (90 ft.)",
"componentes": "V S",
"duracao": "Concentração, até 1 hora",
"descricao": "Invoca até 8 elementais de CD 1/4 ou menor (ou 4 CD 1/2, 2 CD 1 ou 1 CD 2). Eles são aliados, agem juntos e obedecem comandos verbais. Se não comandados, se defendem. Em níveis superiores: 2x criaturas (6º círculo) ou 3x (8º)."
},
{
"nome": "Invocar Elemental",
"nivel": 4,
"escola": "Invocação",
"classes": ["Druida", "Patrulheiro", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "27m (90 ft.)",
"componentes": "V S M (ar, um cascalho, cinzas, e água dentro de um frasco banhado a ouro no valor de 400 po)",
"duracao": "Concentração, Uma hora",
"descricao": "Você convoca um espírito elemental que se manifesta em um espaço desocupado à sua vista dentro do alcance da magia. Escolha um elemento: Ar, Água, Terra ou Fogo. A criatura assume uma forma bípede e tem estatísticas baseadas no elemento escolhido. Ela é uma aliada e compartilha sua contagem de iniciativa, realizando seu turno logo após o seu. Em combate, ela obedece seus comandos verbais e, se não houver comando, realiza a ação de Esquiva. A criatura desaparece ao atingir 0 pontos de vida ou quando a magia termina. Em Níveis Superiores, ao usar um espaço de magia de 5º círculo ou mais, você aumenta o poder do elemental."
},
{
"nome": "Invocar Seres da Floresta",
"nivel": 4,
"escola": "Invocação",
"classes": ["Druida", "Patrulheiro"],
"tempo_conjuracao": "Uma ação",
"alcance": "18m (60 ft.)",
"componentes": "V S M (uma baga de azevinho para cada criatura invocada)",
"duracao": "Concentração, Até uma hora",
"descricao": "Você invoca feéricos que surgem em espaços desocupados à sua vista dentro do alcance da magia. Escolha a quantidade e o nível de desafio das criaturas: uma com nível de desafio 2 ou menor, duas com nível de desafio 1 ou menor, quatro com nível de desafio 1/2 ou menor, ou oito com nível de desafio 1/4 ou menor. As criaturas desaparecem ao cair a 0 pontos de vida ou quando a magia termina. Elas são amigas de você e seus companheiros, e obedecem a comandos verbais sem exigir ações adicionais de sua parte. Em Níveis Superiores, ao usar um espaço de magia de 6º círculo ou mais, o número de criaturas invocadas dobra."
},
{
"nome": "Localizar Criatura",
"nivel": 4,
"escola": "Adivinhação",
"classes": ["Bardo", "Clérigo", "Druida", "Patrulheiro", "Mago", "Paladino"],
"tempo_conjuracao": "Uma ação",
"alcance": "Pessoal",
"componentes": "V S M (um pouco de pelo de um cão de caça)",
"duracao": "Concentração, Até uma hora",
"descricao": "Você sente a direção de uma criatura específica que nomeou ou descreveu, dentro de 300 metros (1000 ft.). Se a criatura se mover, você sabe a direção. A magia só localiza criaturas que você já tenha visto de perto. Se a criatura estiver sob Polimorfia ou efeito similar, a magia não a localiza. A magia também é bloqueada por água corrente com pelo menos 3 metros de largura entre você e o alvo."
},
{
"nome": "Malogro",
"nivel": 4,
"escola": "Necromancia",
"classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "9m (30 ft.)",
"componentes": "V S",
"duracao": "Instantânea",
"descricao": "Você drena a umidade e vitalidade de uma criatura à sua vista e no alcance da magia. O alvo faz uma salvaguarda de Constituição. Se falhar, sofre 8d8 de dano necrótico; metade em caso de sucesso. Não afeta mortos-vivos ou constructos. Se o alvo for uma planta ou planta mágica, ele faz a salvaguarda com desvantagem e sofre dano máximo. Plantas não-mágicas morrem instantaneamente. Em Níveis Superiores, o dano aumenta em 1d8 por círculo acima do 4º."
},
{
"nome": "Moldar Rochas",
"nivel": 4,
"escola": "Transmutação",
"classes": ["Artífice", "Clérigo", "Druida", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "Toque",
"componentes": "V S M (argila mole, que deve ser moldada para se assemelhar ao formato do objeto de pedra desejado)",
"duracao": "Instantânea",
"descricao": "Você toca um objeto de pedra ou uma seção de rocha de até 1,5 metro (5 ft.) e a molda em qualquer forma desejada, como uma arma, ídolo ou baú, ou cria uma pequena passagem através de uma parede. A pedra pode ter até duas dobradiças e uma fechadura, mas detalhes mecânicos mais complexos não são possíveis."
},
{
"nome": "Movimentação Livre",
"nivel": 4,
"escola": "Abjuração",
"classes": ["Artífice", "Bardo", "Clérigo", "Druida", "Patrulheiro"],
"tempo_conjuracao": "Uma ação",
"alcance": "Toque",
"componentes": "V S M (uma cinta de couro amarrada ao redor do braço ou apêndice similar)",
"duracao": "Uma hora",
"descricao": "Você toca uma criatura voluntária. Enquanto a magia durar, o movimento do alvo não será afetado por terreno difícil, e magias ou efeitos mágicos não podem reduzir seu deslocamento, paralisar ou conter a criatura. O alvo também pode usar 1,5 metro (5 ft.) de movimento para escapar de impedimentos não-mágicos como algemas ou agarramentos."
},
{
"nome": "Muralha de Fogo",
"nivel": 4,
"escola": "Evocação",
"classes": ["Druida", "Feiticeiro", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "36m (120 ft.)",
"componentes": "V S M (um pequeno pedaço de fósforo)",
"duracao": "Concentração, Até 1 minuto",
"descricao": "Você cria uma muralha de fogo sobre uma superfície sólida. Ela pode ter até 18 metros (60 ft.) de comprimento, 6 metros (20 ft.) de altura e 30 cm (1 ft.) de espessura, ou ser uma parede circular de até 6 metros de diâmetro. A muralha causa 5d8 de dano ígneo a criaturas que entrarem ou terminarem seu turno a menos de 3 metros de uma face. A outra face não causa dano. Em Níveis Superiores, o dano aumenta em 1d8 por círculo acima do 4º."
},
{
"nome": "Olho Arcano",
"nivel": 4,
"escola": "Adivinhação",
"classes": ["Artífice", "Mago"],
"tempo_conjuracao": "Uma ação",
"alcance": "9m (30 ft.)",
"componentes": "V S M (um pouco de pelo de morcego)",
"duracao": "Concentração, Até uma hora",
"descricao": "Você cria um olho mágico invisível que paira no ar. O olho tem visão normal e no escuro até 9 metros (30 ft.). Você pode mover o olho até 9 metros em qualquer direção a cada ação, e ele pode passar por pequenas aberturas. O olho transmite imagens mentais para você, mas não pode entrar em outro plano de existência."
},
{
  "nome": "Pele-rocha",
  "nivel": 4,
  "escola": "Abjuração",
  "classes": ["Artífice", "Druida", "Feiticeiro", "Patrulheiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "Toque",
  "componentes": "V S M (pó de diamante no valor mínimo de 100 PO, que a magia consome)",
  "duracao": "Concentração, Até 1 hora",
  "descricao": "Você toca uma criatura voluntária, tornando sua pele tão dura quanto pedra. Enquanto a magia durar, o alvo tem resistência contra dano não-mágico contundente, cortante e perfurante."
},
{
  "nome": "Polimorfia",
  "nivel": 4,
  "escola": "Transmutação",
  "classes": ["Bardo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um casulo de lagarta)",
  "duracao": "Concentração, Até 1 hora",
  "descricao": "A magia transforma uma criatura à sua vista em uma nova forma. A transformação dura até o alvo cair a 0 pontos de vida ou morrer. O alvo assume as estatísticas de uma fera com nível de desafio igual ou inferior ao seu."
},
{
  "nome": "Porta Dimensional",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "150m (500 ft.)",
  "componentes": "V",
  "duracao": "Instantânea",
  "descricao": "Você teleporta-se para um local à sua vista dentro do alcance. Pode levar objetos ou uma criatura voluntária com você, desde que o peso não exceda sua capacidade de carga. Se o local estiver ocupado, o teletransporte falha e causa dano."
},
{
  "nome": "Presságio",
  "nivel": 4,
  "escola": "Adivinhação",
  "classes": ["Clérigo"],
  "tempo_conjuracao": "1 ação ou Ritual",
  "alcance": "Pessoal",
  "componentes": "V S M (incenso e uma oferenda sacrificial adequada à sua religião, no valor de 25 PO)",
  "duracao": "Instantânea",
  "descricao": "Você faz uma única pergunta a um deus ou servo dele sobre um evento futuro. O DM oferece uma resposta verdadeira. Se você conjurar a magia mais de uma vez entre descansos longos, há chance de obter uma resposta aleatória."
},
{
  "nome": "Proteção Contra Morte",
  "nivel": 4,
  "escola": "Abjuração",
  "classes": ["Clérigo", "Paladino"],
  "tempo_conjuracao": "1 ação",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "8 horas",
  "descricao": "Ao tocar uma criatura, você lhe concede proteção contra a morte. Caso o alvo sofra dano que o reduza a 0 pontos de vida, ele retorna com 1 ponto de vida. Também anula efeitos que o matariam instantaneamente."
},
{
  "nome": "Resplendor Enjoativo",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "36m (120 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Uma esfera de luz esverdeada se espalha em uma área de 9m de raio. Criaturas que entram ou começam seu turno na área devem fazer uma salvaguarda de Constituição ou sofrer dano radiante e um nível de exaustão."
},
{
  "nome": "Santuário Particular de Mordenkainen",
  "nivel": 4,
  "escola": "Abjuração",
  "classes": ["Mago"],
  "tempo_conjuracao": "10 minutos",
  "alcance": "36m (120 ft.)",
  "componentes": "V S M (uma folha fina de chumbo, vidro opaco, algodão ou pano, e crisólita em pó)",
  "duracao": "24 horas",
  "descricao": "Você cria uma área mágica protegida de até 30m. Pode impedir sons, visão, sensores de adivinhação, teleportação e viagem planar dentro da área. Se conjurada diariamente por um ano, a proteção se torna permanente."
},
{
  "nome": "Sombra de Transtorno",
  "nivel": 4,
  "escola": "Necromancia",
  "classes": ["Bruxo"],
  "tempo_conjuracao": "1 ação",
  "alcance": "Pessoal",
  "componentes": "V S M (um globo ocular de morto-vivo encoberto por uma gema no valor de 150 PO)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Sombras rodeiam seu corpo, conferindo resistência a dano radiante e causando dano necrótico de 2d8 a criaturas que o atacam a até 3m. A luz ao redor de você muda para escuridão e luz fraca."
},
{
  "nome": "Tempestade Glacial",
  "nivel": 4,
  "escola": "Evocação",
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "90m (300 ft.)",
  "componentes": "V S M (uma pitada de pó e algumas gotas de água)",
  "duracao": "Instantânea",
  "descricao": "Uma saraivada de pedras de gelo cai em um cilindro de 6 metros de raio por 12 metros de altura. Cada criatura na área afetada deve fazer uma salvaguarda de Destreza. Se falhar, sofre 2d8 de dano contundente e 4d6 de dano gélido, ou metade do dano em caso de sucesso. A área se torna terreno difícil até o final do próximo turno."
},
{
  "nome": "Tentáculos Negros de Evard",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Mago"],
  "tempo_conjuracao": "1 ação",
  "alcance": "27m (90 ft.)",
  "componentes": "V S M (um pedaço do tentáculo de um polvo ou lula gigante)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Tentáculos negros surgem e preenchem uma área de 6 metros quadrados. Criaturas que entram ou começam seu turno na área devem fazer uma salvaguarda de Destreza. Se falharem, sofrem 3d6 de dano contundente e ficam contidas pelos tentáculos até o fim da magia. Criaturas contidas podem tentar se libertar com um teste de Força ou Destreza."
},
{
  "nome": "Terreno Alucinatório",
  "nivel": 4,
  "escola": "Ilusão",
  "classes": ["Bardo", "Bruxo", "Druida", "Mago"],
  "tempo_conjuracao": "10 minutos",
  "alcance": "90m (300 ft.)",
  "componentes": "V S M (uma pedra, um graveto e um pedaço de uma planta verde)",
  "duracao": "24 horas",
  "descricao": "Você altera a aparência de um terreno natural em um cubo de 45 metros, fazendo com que pareça outro tipo de terreno. Criaturas que tocarem a área podem perceber a ilusão com um teste de Inteligência (Investigação). A ilusão não altera as características táteis do terreno."
},
{
  "nome": "Vinha Agarradora",
  "nivel": 4,
  "escola": "Invocação",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "9m (30 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você faz uma vinha brotar do chão, podendo direcioná-la para atacar uma criatura à sua vista a até 9 metros de distância. O alvo deve fazer uma salvaguarda de Destreza ou ser puxado 6 metros na direção da vinha. Você pode atacar a mesma ou outra criatura com a vinha em cada um dos seus turnos usando uma ação bônus."
}
]