magias_nivel_3 = [
{
  "nome": "Animar Mortos",
  "nivel": 3,
  "escola": "Necromancia",
  "classes": ["Clérigo", "Mago"],
  "tempo_conjuracao": "1 minuto",
  "alcance": "3m (10 ft.)",
  "componentes": "V S M (uma gota de sangue, um pedaço de carne e uma pitada de pó de osso)",
  "duracao": "Instantânea",
  "descricao": "Esta magia cria um servo morto-vivo. Escolha uma pilha de ossos ou o cadáver de um humanoide Médio ou Pequeno, dentro do alcance da magia. Você infunde o alvo com uma perversa imitação de vida, fazendo-o se erguer como uma criatura morta-viva. O alvo se torna um esqueleto, se você escolheu ossos, ou um zumbi, se você escolheu um cadáver (o DM fornece as estatísticas da criatura).\n\nEm cada um de seus turnos, você pode usar uma ação bônus para comandar mentalmente qualquer criatura que tenha criado com esta magia, e que esteja a até 18 metros (60 ft.) de você (se controlar múltiplas criaturas, você pode comandar uma ou todas simultaneamente, emitindo o mesmo comando para todas). Você decide qual ação a criatura tomará e para onde ela se moverá durante o próximo turno dela, ou você pode emitir um comando mais genérico, como manter a guarda de uma câmara ou corredor. Se você não emitir nenhum comando, a criatura apenas se defende de criaturas hostis. Uma vez dada a ordem, a criatura continuará seguindo-a até que a tarefa esteja completa.\n\nA criatura fica sob seu controle por 24 horas, período após o qual ela para de obedecer aos seus comandos. Para manter o controle por mais 24 horas, é necessário conjurar novamente esta magia na criatura antes que o período de controle atual de 24 horas acabe. Isso restabelece o seu controle sobre até quatro criaturas que você tenha animado com esta magia em vez de animar uma nova.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou maior, você pode animar ou restabelecer o controle sobre mais dois mortos-vivos para cada círculo do espaço acima do 3º. Cada uma das criaturas precisa ter vindo de uma pilha de ossos ou cadáver único."
},
{
  "nome": "Arma Elemental",
  "nivel": 3,
  "escola": "Transmutação",
  "classes": ["Artífice", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Uma arma não-mágica tocada por você transforma-se numa arma mágica. Escolha um dos seguintes tipos de dano: ácido, elétrico, ígneo, gélido ou trovejante. Enquanto a magia durar, a arma tem um bônus de +1 nas jogadas de ataque e causa 1d4 pontos de dano adicional, do tipo escolhido, ao acertar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 5º ou 6º círculos, o bônus para as jogadas de ataque aumenta para +2 e o dano extra sobe para 2d4. Quando você usar um espaço de magia de 7º círculo, o bônus aumenta para +3 e o dano adicional para 3d4."
},
{
  "nome": "Aura de Vitalidade",
  "nivel": 3,
  "escola": "Evocação",
  "classes": ["Patrulheiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal (raio de 9m [30 ft.])",
  "componentes": "V",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Uma aura de energia curativa se irradia de você em um raio de 9 metros (30 ft.). Enquanto a magia durar, a aura, centrada em você, move-se para onde quer que você vá. Você pode usar uma ação bônus para fazer com que uma criatura dentro da aura (incluindo você) recupere 2d6 pontos de vida."
},
{
    "nome": "Bola de Fogo",
    "nivel": 3,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (uma pequena bola de guano de morcego e enxofre)",
    "duracao": "Instantânea",
    "descricao": "Um rastro brilhante lampeja do seu dedo apontado para um local à sua escolha e no alcance da magia, onde desabrocha com um estrondo grave em uma explosão de chamas. Cada criatura em uma esfera com raio de 6 metros [20-foot-radius sphere], centrada naquele ponto, deve fazer uma salvaguarda de Destreza. Se falhar, sofre 8d6 pontos de dano ígneo, ou metade do dano em caso de sucesso.\n\nO fogo se alastra, contornando os cantos. Ele incendeia objetos inflamáveis na área que não estejam sendo usados ou carregados.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Caminhar Sobre as Águas",
    "nivel": 3,
    "classes": ["Artífice", "Clérigo", "Druida", "Feiticeiro", "Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um pedaço de cortiça)",
    "duracao": "Uma hora",
    "descricao": "Esta magia concede a capacidade de deslocamento sobre qualquer superfície líquida - como água, ácido, lama, neve, areia movediça ou lava - como se fosse terra firme e inofensiva (criaturas cruzando lava derretida ainda podem sofrer dano devido ao calor). Enquanto esta magia durar, até dez criaturas voluntárias, à sua vista e no alcance da magia, ganham esta habilidade.\n\nSe você escolher uma criatura submersa como alvo, a magia carrega o alvo até a superfície do líquido a uma taxa de 18 metros [60 ft.] por rodada."
},
{
    "nome": "Celeridade",
    "nivel": 3,
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um corte de raiz de alcaçuz)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Escolha uma criatura voluntária, à sua vista e dentro do alcance da magia. Enquanto a magia durar, o alvo tem deslocamento dobrado, ganha +2 na CA, tem vantagem nas salvaguardas de Destreza e ganha uma ação adicional em cada um dos próprios turnos. Essa ação pode ser usada apenas como as ações Atacar (ataque armado, apenas), Correr, Desengajar, Esconder ou Usar um Objeto.\n\nQuando a magia termina, o alvo é dominado por uma onda de letargia e não pode se mover ou executar ações até o final do próximo turno dele."
},
{
    "nome": "Círculo Mágico",
    "nivel": 3,
    "classes": ["Bruxo", "Clérigo", "Mago", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "1 minuto",
    "alcance": "3m [10 ft.]",
    "componentes": "V S M (água benta ou prata e ferro em pó valendo no mínimo 100 PO, os quais a magia consome)",
    "duracao": "Uma hora",
    "descricao": "Você cria um cilindro de 3 metros de raio e 6 metros de altura [10-foot-radius, 20-foot-tall cylinder] feito de energia mágica, centrado em um ponto no solo à sua vista e no alcance da magia. Runas brilhantes aparecem onde quer que o cilindro toque, seja o solo ou outra superfície.\n\nEscolha um ou mais dentre os seguintes tipos de criaturas: celestiais, elementais, feéricos, ínferos ou mortos-vivos. O círculo afeta criaturas do(s) tipo(s) escolhido(s) dos seguintes modos:\n\n- A criatura não pode entrar voluntariamente no cilindro por meios não-mágicos. Caso tente usar teleporte ou viagem interplanar para fazê-lo, ela precisa primeiro ser bem-sucedida em uma salvaguarda de Carisma.\n- A criatura tem desvantagem nas jogadas de ataque contra alvos dentro do cilindro.\n- Alvos dentro do cilindro não podem ser amedrontados, enfeitiçados ou possuídos pela criatura.\n\nAo conjurar esta magia, você pode escolher que ela funcione na direção reversa, evitando que uma criatura do tipo especificado saia do cilindro, protegendo alvos fora dele.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, a duração aumenta em 1 hora para cada círculo do espaço acima do 3º."
},
{
    "nome": "Clarividência",
    "nivel": 3,
    "classes": ["Bardo", "Clérigo", "Feiticeiro", "Mago"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "10 minutos",
    "alcance": "1,5km [1 mile]",
    "componentes": "V S M (um foco no valor de pelo menos 100 PO, seja um chifre ornado com gemas e usado para escutar, ou olho de vidro usado para ver)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você cria um sensor invisível em um local que lhe seja familiar (um lugar que visitou ou que já tenha visto) ou em uma localidade óbvia, mas que não lhe seja familiar (como atrás de uma porta, contornando uma esquina ou em um bosque), ambos dentro do alcance da magia. O sensor permanece no local enquanto a magia durar, não podendo ser atacado nem ser alvo de qualquer outro tipo de interação.\n\nAo conjurar a magia, você escolhe ver ou ouvir. Você pode usar o sentido escolhido por meio do sensor como se estivesse no espaço ocupado por ele. Com uso de uma ação, você pode alternar entre ver e ouvir.\n\nUma criatura que possa ver o sensor (como aquelas que se beneficiam de Ver o Invisível ou visão verdadeira), enxerga um orbe luminoso e intangível do tamanho de um punho."
},
{
    "nome": "Conjurar Animais",
    "nivel": 3,
    "classes": ["Druida", "Patrulheiro"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você invoca espíritos feéricos que assumem a forma de feras e surgem em espaços desocupados à sua vista, no alcance da magia. Escolha o que aparece entre as opções a seguir:\n\n- Uma fera com nível de desafio 2 ou menor.\n- Duas feras com nível de desafio 1 ou menor.\n- Quatro feras com nível de desafio 1/2 ou menor.\n- Oito feras com nível de desafio 1/4 ou menor.\n\nCada fera também é considerada feérica, desaparecendo ao ficar com 0 pontos de vida ou ao término da magia.\n\nAs criaturas invocadas são amistosas com você e seus companheiros. Jogue a iniciativa para as criaturas invocadas como um grupo, que tem seu próprio turno. As criaturas invocadas obedecem a qualquer comando verbal que você lhes direcione (não requer ação sua). Caso não seja dado comando algum, elas se defendem de seres hostis, não executando nenhuma outra ação.\n\nO DM fornece as estatísticas das criaturas.\n\nEm Níveis Superiores. Ao conjurar esta magia utilizando espaços de magia de círculos superiores, escolha uma das opções de invocação apresentadas anteriormente, e mais criaturas aparecem: o dobro com um espaço de 5º círculo, o triplo com um espaço de 7º círculo e o quádruplo com um espaço de 9º círculo."
},
{
    "nome": "Conjurar Rajada",
    "nivel": 3,
    "classes": ["Patrulheiro"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (cone de 18m [60 ft.])",
    "componentes": "V S M (uma peça de munição ou uma arma de arremesso)",
    "duracao": "Instantânea",
    "descricao": "Você arremessa uma arma não-mágica, ou dispara uma munição não-mágica no ar, criando um cone de armas idênticas que disparam adiante e então desaparecem. Cada criatura dentro do cone de 18 metros [60 ft.] deve fazer uma salvaguarda de Destreza. Se falhar, sofre 3d8 pontos de dano, ou metade do dano em caso de sucesso. O tipo do dano é o mesmo da arma ou munição usada como componente."
},
{
    "nome": "Contramagia",
    "nivel": 3,
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma reação, executada quando você vir uma criatura a 18 metros [60 ft.] de você conjurar uma magia",
    "alcance": "18m [60 ft.]",
    "componentes": "S",
    "duracao": "Instantânea",
    "descricao": "Você tenta interromper uma criatura no processo de conjurar uma magia. Se ela estiver conjurando uma magia de 3º círculo ou inferior, a magia falha e não tem efeito. Se ela estiver conjurando uma magia de 4º círculo ou superior, faça um teste de atributo usando o seu atributo de conjuração. A CD é igual a 10 + o círculo da magia conjurada pela criatura. Em caso de sucesso, a magia da criatura falha e não surte efeito.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, a magia interrompida não tem efeito se o círculo dela for menor ou igual ao círculo do espaço de magia que você usou."
},
{
    "nome": "Convocar Relâmpagos",
    "nivel": 3,
    "classes": ["Druida"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Uma nuvem de tempestade aparece na forma de um cilindro de 3 metros de altura [10 ft. tall cilinder] com um raio de 18 metros [60 ft. radius], centralizado em um ponto à sua vista, dentro do alcance diretamente acima de você. A magia falha se você não puder ver um ponto no ar onde a nuvem de tempestade possa aparecer (por exemplo, se você estiver em uma sala que não possa acomodar a nuvem).\n\nAo conjurar a magia, escolha um ponto que você possa ver sob a nuvem. Um raio de eletricidade parte da nuvem até esse ponto. Cada criatura a uma distância de até 1,5 metro [5 ft.] desse ponto deve fazer uma salvaguarda de Destreza. Se falhar, sofre 3d10 pontos de dano elétrico, ou metade do dano em caso de sucesso. Em cada um de seus turnos, enquanto a magia durar, você pode usar sua ação para convocar relâmpagos dessa maneira, atingindo o mesmo ponto ou outro.\n\nSe você estiver ao ar livre e em condições tempestuosas ao conjurar esta magia, ela lhe confere o controle sobre a tempestade existente, em vez de criar uma nova. Sob essas condições, o dano da magia aumenta em 1d10.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d10 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Crescimento de Plantas",
    "nivel": 3,
    "classes": ["Bardo", "Druida", "Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação ou 8 horas",
    "alcance": "45m [150 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Esta magia canaliza vitalidade para as plantas dentro de uma área específica. Existem dois usos possíveis para a magia, garantindo tanto benefícios imediatos quanto de longa duração.\n\nSe você conjurar esta magia usando uma ação, escolha um ponto dentro do alcance. Todas as plantas normais em um raio de 30 metros [100-foot radius] centradas neste ponto tornam-se espessas e super desenvolvidas. Uma criatura se movendo através da área deve gastar 6 metros [20 ft.] de movimento para cada 1,5 metro [5 ft.] que se mover.\n\nVocê pode excluir uma ou mais áreas de qualquer tamanho dentro de área da magia a ser afetada.\n\nSe você conjurar esta magia ao longo de 8 horas, você enriquece a terra. Todas as plantas em um raio de 1 quilômetro [0,5 mile] centradas em um ponto dentro do alcance se tornam enriquecidas durante 1 ano. As plantas produzem duas vezes a quantidade normal de alimento quando colhidas."
},
{
    "nome": "Criar Comida e Água",
    "nivel": 3,
    "classes": ["Artífice", "Clérigo", "Paladino"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você cria 20 quilos [45 pounds] de comida e 120 litros [30 gallons] de água no chão ou em recipientes no alcance da magia, o suficiente para sustentar até quinze humanoides ou cinco montarias por 24 horas. A comida não é temperada, mas é nutritiva e estraga se não for ingerida dentro de 24 horas. A água é limpa e não estraga."
},
{
    "nome": "Destruição Cegante",
    "nivel": 3,
    "classes": ["Paladino"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Na próxima vez que você atingir uma criatura com uma arma de combate corpo a corpo no decorrer da duração desta magia, sua arma brilha com luz plena, e o ataque causa 3d8 pontos de dano radiante adicionais no alvo. Além disso, o alvo deve ser bem-sucedido em uma salvaguarda de Constituição ou fica cego enquanto a magia durar.\n\nUma criatura cega por esta magia faz outra salvaguarda de Constituição ao final de cada um dos próprios turnos. Em caso de sucesso, a criatura não está mais cega."
},
{
    "nome": "Dissipar Magia",
    "nivel": 3,
    "classes": ["Artífice", "Bardo", "Bruxo", "Clérigo", "Druida", "Feiticeiro", "Mago", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Escolha uma criatura, objeto ou efeito mágico no alcance da magia. Quaisquer magias de 3º círculo ou inferiores que afetam o alvo se encerram. Para cada magia de 4º círculo ou superior que esteja afetando o alvo, faça um teste de atributo usando seu atributo de conjuração. A CD é igual a 10 + o círculo desta magia. Em caso de sucesso, a magia se encerra.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, você automaticamente encerra os efeitos de uma magia que esteja afetando o alvo, se o círculo da magia for igual ou menor ao círculo do espaço de magia que você usou."
},
{
    "nome": "Erupção de Terra",
    "nivel": 3,
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S M (um pedaço de obsidiana)",
    "duracao": "Instantânea",
    "descricao": "Escolha um ponto que você possa ver no solo, dentro do alcance. Uma fonte de terra e pedras se agita e emerge num cubo de 6m [20-foot cube] centrado no ponto. Cada criatura na área deve realizar salvaguarda de Destreza. Uma criatura sofre 3d12 de dano contundente se falhar, ou metade desse dano se obtiver sucesso. Adicionalmente, o solo na área se torna terreno difícil até ser limpo. Cada porção de 1,5 metro quadrado [5-foot-square] da área requer pelo menos 1 minuto para ser limpa manualmente.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d12 para cada nível do espaço acima do 3º."
},
{
    "nome": "Falar com Mortos",
    "nivel": 3,
    "classes": ["Bardo", "Clérigo"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "3m [10 ft.]",
    "componentes": "V S M (incenso aceso)",
    "duracao": "10 minutos",
    "descricao": "Você concede um arremedo de vida e inteligência a um cadáver à sua escolha, no alcance da magia, permitindo-lhe responder às perguntas feitas a ele. O cadáver ainda deve ter uma boca e não pode ser um morto-vivo. A magia falha se ele já foi alvo desta magia nos últimos 10 dias.\n\nEnquanto a magia durar, você pode fazer até cinco perguntas. O cadáver sabe apenas o que sabia em vida, incluindo idiomas que conhecia. As respostas são normalmente curtas, enigmáticas ou repetitivas, e o cadáver não é compelido a dar uma resposta verdadeira se você for hostil ou se ele o reconhecer como um inimigo. Esta magia não devolve a alma ao corpo da criatura, apenas seu espírito animado. Assim, o cadáver não pode aprender novas informações, não compreende qualquer coisa que aconteceu desde que morreu, e não pode especular sobre eventos futuros."
},
{
    "nome": "Falar com Plantas",
    "nivel": 3,
    "classes": ["Bardo", "Druida", "Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 9m [30 ft.])",
    "componentes": "V S",
    "duracao": "10 minutos",
    "descricao": "Você é capaz de imbuir plantas a até 9 metros [30 ft.] de distância com intelecto limitado e razão, dando-lhes a habilidade de se comunicar e seguir comandos simples. Podem ser feitas perguntas a elas sobre eventos até o dia anterior, na área da magia, sendo possível receber informações sobre as criaturas que passaram, o clima e outras circunstâncias.\n\nPode-se tornar terreno difícil criado por Crescimento de Plantas (como moitas e vegetação rasteira) em terreno comum enquanto a magia durar. Ou você pode tornar um terreno comum, onde há plantas presentes, em terreno difícil, enquanto a magia durar, fazendo com que vinhas e galhos atrapalhem perseguidores, por exemplo.\n\nPlantas podem praticar outras tarefas para você, a critério do DM. A magia não possibilita que as plantas se soltem de suas raízes ou se desloquem, mas elas podem mover galhos, caules e gavinhas livremente.\n\nSe uma criatura do tipo planta está na área, você pode se comunicar com ela, como se vocês compartilhassem um idioma comum, mas isso não dá nenhuma habilidade mágica de influenciá-la.\n\nEsta magia faz com que plantas criadas pela magia Emaranhar soltem uma criatura contida."
},
{
    "nome": "Flecha Relâmpago",
    "nivel": 3,
    "classes": ["Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Enquanto esta magia durar, na próxima vez que você realizar um ataque à distância, a própria arma usada, caso seja um arma de arremesso, ou a munição dela, é transformada em um raio. Faça uma jogada de ataque normalmente. Caso acerte, ao invés do dano normal da arma, o alvo sofre 4d8 pontos de dano elétrico, ou metade do dano caso erre.\n\nQuer você tenha acertado ou não, cada criatura no alcance de 3 metros [10 ft.] do alvo deve fazer uma salvaguarda de Destreza. Cada criatura que falhar, sofre 2d8 pontos de dano elétrico, ou metade do dano em caso de sucesso.\n\nApós o ataque, a munição ou a arma utilizada, retornam, então, à sua forma original.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Flechas Flamejantes",
    "nivel": 3,
    "classes": ["Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você toca uma aljava contendo flechas ou virotes. Quando um alvo é atingido por um ataque à distância com arma usando uma munição sacada dessa aljava, ele sofre 1d6 de dano de fogo extra. A mágica da magia termina na munição quando ela atinge ou erra, e a magia termina quando doze munições forem sacadas da aljava.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, a quantidade de munições que você pode afetar com essa magia aumenta em dois cada nível do espaço acima do 3º."
},
{
    "nome": "Fome de Hadar",
    "nivel": 3,
    "classes": ["Bruxo"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (um tentáculo de polvo em conserva)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você abre um portal para a escuridão entre as estrelas, uma região infestada de horrores desconhecidos. Uma esfera de escuridão e frio intenso com raio de 6 metros [20-foot radius] surge, centrada em um ponto no alcance da magia e permanece enquanto esta durar. Este vazio é preenchido com uma cacofonia de sussurros suaves e ruídos que podem ser ouvidos a até 9 metros [30 ft.] de distância. Nenhuma luz, mágica ou não, pode iluminar a área, e criaturas que estejam totalmente dentro da área ficam cegas.\n\nO vazio cria uma dobra no tecido do espaço e a área passa a ser considerada terreno difícil. Qualquer criatura que comece o próprio turno dentro da área sofre 2d6 pontos de dano gélido. Qualquer criatura que encerre o próprio turno dentro da área deve ser bem-sucedida em uma salvaguarda de Destreza. Se falhar, sofre 2d6 pontos de dano ácido enquanto tentáculos leitosos de outro mundo a agarram."
},
{
    "nome": "Forma Gasosa",
    "nivel": 3,
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um pouco de gaze e um pouco de fumaça)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você toca uma criatura voluntária. O alvo, junto com tudo aquilo que estiver usando e carregando, é transformado em uma nuvem de neblina, enquanto a magia durar. A magia termina se os pontos de vida da criatura forem reduzidos a 0. Criaturas incorpóreas não são afetadas.\n\nEnquanto estiver nesta forma, o único método de movimento do alvo é o voo com deslocamento de 3 metros [10 ft.]. O alvo pode entrar e ocupar o espaço de outra criatura. O alvo tem resistência a danos não-mágicos e vantagem em salvaguardas de Força, Destreza e Constituição. O alvo pode passar através de pequenos orifícios, aberturas estreitas e até mesmo por meras rachaduras, embora trate líquidos como se fossem superfícies sólidas. O alvo não é afetado por queda, e continua pairando no ar mesmo quando atordoado ou incapacitado.\n\nEnquanto estiver sob a forma de nuvem, o alvo não pode falar ou manipular objetos, aqueles que estiver carregando ou segurando não podem ser descartados ou usados, e nenhuma forma de interação pode ser estabelecida com eles. O alvo não pode atacar ou conjurar magias."
},
{
    "nome": "Fortaleza do Intelecto",
    "nivel": 3,
    "classes": ["Artífice", "Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Uma hora",
    "descricao": "Durante a duração, você ou uma criatura disposta que possa ver dentro do alcance tem resistência a dano psíquico, bem como vantagem em Salvaguardas de Inteligência, Sabedoria e Carisma.\n\nEm Níveis Superiores. Ao lançar esta magia usando um espaço de magia de 4º círculo ou superior, você pode ter como alvo uma criatura adicional para cada círculo do espaço acima do 3º. As criaturas devem estar a 9 metros [30 ft.] uma da outra quando você as mira."
},
{
    "nome": "Glifo de Proteção",
    "nivel": 3,
    "classes": ["Artífice", "Bardo", "Clérigo", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma hora",
    "alcance": "Toque",
    "componentes": "V S M (incenso e pó de diamante no valor mínimo de 200 PO, os quais a magia consome)",
    "duracao": "Até ser dissipada ou disparada",
    "descricao": "Ao conjurar esta magia, você inscreve um glifo que mais tarde desencadeia um efeito mágico. Você o inscreve em uma superfície (como uma mesa, uma seção de piso ou parede) ou dentro de um objeto que possa ser fechado (como um livro, um pergaminho ou uma arca de tesouro) e onde o glifo possa ser escondido. O símbolo pode cobrir uma área de até 3 metros de diâmetro [10-foot diameter]. Se a superfície ou objeto for movido mais de 3 metros [10 ft.] de onde você conjurou esta magia, o símbolo é quebrado e a magia se encerra, sem efeito.\n\nO glifo é quase invisível, exigindo um teste de Inteligência (Investigação) contra a CD para evitar sua magia para encontrá-lo.\n\nAo conjurar esta magia, você decide o gatilho do glifo. Para os glifos que foram inscritos em uma superfície, os gatilhos mais típicos incluem tocar ou pisar no glifo, remover um objeto que o cubra, aproximar-se a uma certa distância dele ou manipular um objeto que o contenha. Para os que forem inscritos dentro de um objeto, as condições podem ser a abertura deste, aproximar-se a uma certa distância, ou ainda ver ou ler o glifo. Uma vez que um glifo seja disparado, esta magia termina.\n\nVocê pode refinar o gatilho para que a magia seja ativada apenas sob certas circunstâncias ou de acordo com as características físicas (como altura ou peso), tipo de criatura (por exemplo, a proteção poderia ser programada para afetar aberrações ou drow) ou alinhamento. Podem também ser especificadas condições para que não se dispare o glifo, como dizer uma palavra-chave, por exemplo.\n\nQuando você inscrever o glifo, escolha entre runas explosivas ou glifo arcano.\n\nRunas Explosivas. Quando acionada, a runa explode com energia mística em uma esfera de 6 metros [20 ft.] centrada no glifo. A esfera se alastra, contornando os cantos. Cada criatura na área deve fazer uma salvaguarda de Destreza. Se falhar, sofre 5d8 pontos de dano ácido, elétrico, gélido, ígneo ou trovejante (à sua escolha, ao conjurar a magia), ou metade do dano em caso de sucesso.\n\nGlifo Arcano. Você pode armazenar uma magia preparada de 3º círculo ou inferior junto ao glifo, se conjurar esta magia como parte do processo. Ela deve ter como alvo uma única criatura, ou uma área. A magia que foi conjurada não tem efeito imediato nesta modalidade. Ela se ativa quando o glifo for disparado. Se a magia tiver um alvo, quem acionou o glifo é atingido. Se a magia afetar uma área, o centro é a criatura. Se a magia invocar criaturas hostis ou criar objetos nocivos ou armadilhas, eles surgem o mais próximo possível do intruso e o atacam. Se a magia exigir concentra­ção, ela permanece até o fim de sua duração total.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano por um símbolo de runas explosivas aumenta em 1d8 para cada círculo do espaço acima do 3º. Se criar um glifo arcano, você pode armazenar qualquer magia até o mesmo círculo que o espaço que foi usado para conjurar o Glifo de Proteção."
},
{
    "nome": "Guardiões Espirituais",
    "nivel": 3,
    "classes": ["Clérigo"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (raio de 4,5m [15 ft.])",
    "componentes": "V S M (um símbolo sagrado)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você convoca espíritos para lhe proteger. Eles vagueiam ao seu redor a uma distância de até 4,5 metros [15 ft.] enquanto a magia durar. Se você for bom ou neutro, os espíritos assumem formas angelicais ou feéricas (à sua escolha). Se seu alinhamento for maligno, eles se assemelham a ínferos.\n\nAo conjurar esta magia, você pode designar qualquer número de criaturas à sua vista para não serem afetadas por ela. Uma criatura afetada por esta magia possui apenas metade do deslocamento na área. Ao entrar na área pela primeira vez ou iniciar o turno nela, a criatura deve fazer uma salvaguarda de Sabedoria. Se falhar, sofre 3d8 pontos de dano radiante (se você for bom ou neutro) ou 3d8 pontos de dano necrótico (se for mau). Em caso de sucesso, a criatura sofre metade do dano.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 3º."
},
{
  "nome": "Indetectável",
  "nivel": 3,
  "classes": ["Bardo", "Patrulheiro", "Mago"],
  "escola": "Abjuração",
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (uma pitada de pó de diamante no valor mínimo de 25 PO polvilhado sobre o alvo, que a magia consome)",
  "duracao": "8 horas",
  "descricao": "Enquanto a magia durar, você oculta um alvo que você toque de magias de adivinhação. O alvo pode ser uma criatura voluntária, um local ou um objeto que não ultrapasse 3 metros em qualquer dimensão. O alvo não pode ser afetado por qualquer magia de adivinhação ou percebido por sensores mágicos de vidência."
},
{
  "nome": "Infestar de Inimigos",
  "nivel": 3,
  "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "escola": "Encantamento",
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m 120 ft.",
  "componentes": "V S",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você alcança a mente de uma criatura que você pode ver e força-la a fazer salvaguarda de Inteligência. Uma criatura é bem sucedida automaticamente se for imune a ser amedrontada. Em falha do salvaguarda, o alvo perde a habilidade de distinguir amigos de inimigos, em relação a todas as criaturas que pode ver como inimigos até que a magia termine. Cada vez que o alvo sofre dano, ele pode repetir o salvaguarda, terminando o efeito sobre si mesmo em um sucesso. Sempre que a criatura afetada escolher outra criatura como alvo, ele deve escolher o alvo aleatoriamente entre as criaturas que pode ver dentro do alcance do ataque, magia ou outra habilidade que esteja usando. Se um inimigo provoca um ataque de oportunidade da criatura afetada, a criatura deve fazer esse ataque se for capaz de fazê-lo."
},
{
  "nome": "Invocar Demônios Menores",
  "nivel": 3,
  "classes": ["Bruxo", "Mago"],
  "escola": "Invocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "18 m (60 pés)",
  "componentes": "V, S, M (um frasco com sangue de um humanóide morto nas últimas 24 horas)",
  "duracao": "Concentração, até 1 hora",
  "descricao": "Você invoca demônios do Abismo, rolando 1d6 para determinar o número: 1-2: dois demônios (ND 1 ou menos), 3-4: quatro demônios (ND 1/2 ou menos), 5-6: oito demônios (ND 1/4 ou menos). O Mestre escolhe os demônios e você escolhe onde eles aparecem. Os demônios são hostis a todos e desaparecem ao cair a 0 PV ou quando a magia termina. Você pode desenhar um círculo com o sangue do componente para protegê-lo de ataques dos demônios. Com espaços de 6º ou 7º nível, invoca o dobro de demônios, e com 8º ou 9º nível, o triplo."
},
{
  "nome": "Invocar Feérico",
  "nivel": 3,
  "classes": ["Bruxo", "Druida", "Patrulheiro", "Mago"],
  "escola": "Invocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "27 m (90 pés)",
  "componentes": "V, S, M (uma flor dourada no valor de ao menos 300 PO)",
  "duracao": "Concentração, até 1 hora",
  "descricao": "Você convoca um espírito feérico que se manifesta em um espaço desocupado à sua vista dentro do alcance. Ele assume uma forma corpórea baseada no bloco de estatísticas do Espírito Feérico. Ao conjurar a magia, escolha um humor: Irritadiço, Jubiloso ou Brincalhão. A aparência do espírito reflete esse temperamento, que também determina traços específicos no bloco de estatísticas. A criatura desaparece ao atingir 0 pontos de vida ou quando a magia termina.\n\nA criatura é sua aliada e dos seus companheiros. Em combate, compartilha sua iniciativa, mas age imediatamente após seu turno. Ela obedece a comandos verbais (sem exigir sua ação). Caso você não diga nada, ela usará a ação de Esquiva e se afastará do perigo.\n\n**Em Níveis Superiores.** Ao conjurar esta magia com um espaço de 4º nível ou superior, utilize o nível do espaço onde quer que o nível da magia apareça no bloco de estatísticas."
},
{
  "nome": "Invocar Morto-vivo",
  "nivel": 3,
  "classes": ["Bruxo", "Mago"],
  "escola": "Necromancia",
  "tempo_conjuracao": "Uma ação",
  "alcance": "27 m (90 pés)",
  "componentes": "V, S, M (um crânio de ouro no valor de 300 PO)",
  "duracao": "Concentração, até 1 hora",
  "descricao": "Você convoca um espírito morto-vivo que se manifesta em um espaço desocupado à sua vista dentro do alcance. Ele assume uma forma corpórea baseada no bloco de estatísticas do Espírito Morto-Vivo. Ao conjurar a magia, escolha uma forma: Fantasmal, Pútrido ou Esquelético. A aparência e habilidades do espírito variam conforme essa forma. A criatura desaparece ao atingir 0 pontos de vida ou quando a magia termina.\n\nA criatura é sua aliada e dos seus companheiros. Em combate, compartilha sua iniciativa, mas age imediatamente após seu turno. Ela obedece a comandos verbais (sem exigir sua ação). Caso você não diga nada, ela usará a ação de Esquiva e se afastará do perigo.\n\n**Em Níveis Superiores.** Ao conjurar esta magia com um espaço de 4º nível ou superior, utilize o nível do espaço onde quer que o nível da magia apareça no bloco de estatísticas."
},
{
  "nome": "Invocar Prole Sombria",
  "nivel": 3,
  "classes": ["Bruxo", "Mago"],
  "escola": "Invocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "27 m (90 pés)",
  "componentes": "V, S, M (lágrimas armazenadas em uma joia no valor de ao menos 300 PO)",
  "duracao": "Concentração, até 1 hora",
  "descricao": "Você convoca um espírito sombrio que se manifesta em um espaço desocupado à sua vista dentro do alcance. Ele assume uma forma corpórea baseada no bloco de estatísticas do Espírito das Sombras. Ao conjurar a magia, escolha uma emoção: Fúria, Desespero ou Medo. A aparência e habilidades da criatura refletem a emoção escolhida. A criatura desaparece ao atingir 0 pontos de vida ou quando a magia termina.\n\nA criatura é sua aliada e dos seus companheiros. Em combate, compartilha sua iniciativa, mas age imediatamente após seu turno. Ela obedece a comandos verbais (sem exigir sua ação). Caso você não diga nada, ela usará a ação de Esquiva e se afastará do perigo.\n\n**Em Níveis Superiores.** Ao conjurar esta magia com um espaço de 4º nível ou superior, utilize o nível do espaço onde quer que o nível da magia apareça no bloco de estatísticas."
},
{
  "nome": "Lentidão",
  "nivel": 3,
  "classes": ["Feiticeiro", "Mago"],
  "escola": "Transmutação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m 120 ft.",
  "componentes": "V S M (uma gota de melaço)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você altera o tempo ao redor para até seis criaturas à sua escolha em um cubo de 12 metros 40-foot cube no alcance da magia. Cada alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria ou sofre os efeitos enquanto a magia durar.\n\nUm alvo afetado tem seu deslocamento reduzido à metade, tem uma penalidade de -2 em sua CA e salvaguardas de Destreza, e não pode usar reações. No turno dele, ele pode usar uma ação ou ação bônus, mas não ambas. A despeito dos atributos ou dos itens mágicos de uma criatura, ela não pode fazer mais do que um ataque corpo a corpo ou à distância durante o turno dela.\n\nSe a criatura tentar conjurar uma magia com um tempo de conjuração de 1 ação, jogue 1d20. Em um resultado de 11 ou mais, a magia não tem efeito até o próximo turno da criatura, e ela deve usar sua ação naquele turno para completar a magia. Se não puder, a magia é desperdiçada.\n\nUma criatura afetada por esta magia faz uma nova salvaguarda de Sabedoria no final de cada um dos turnos dela. Em um sucesso,o efeito se encerra sobre ela."
},
{
  "nome": "Línguas",
  "nivel": 3,
  "classes": ["Bardo", "Bruxo", "Clérigo", "Feiticeiro", "Mago"],
  "escola": "Adivinhação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V M (um pequeno modelo em argila de um zigurate)",
  "duracao": "Uma hora",
  "descricao": "A magia concede à uma criatura que você toque a habilidade de compreender e falar qualquer idioma que ela escute. Além disso, quando o alvo falar, qualquer criatura que conheça ao menos um idioma e conseguir ouvir o alvo, compreende o que ele diz."
},
{
  "nome": "Luz do Dia",
  "nivel": 3,
  "classes": ["Clérigo", "Druida", "Feiticeiro", "Patrulheiro", "Paladino"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m 60 ft.",
  "componentes": "V S",
  "duracao": "Uma hora",
  "descricao": "Uma esfera de luz com raio de 18 metros 60 ft. se expande a partir de um ponto à sua escolha e no alcance da magia. A esfera é de luz plena e emite meia-luz por mais 18 metros 60 ft.\n\nSe o ponto escolhido for um objeto que você está segurando ou que não esteja sendo usado ou carregado, a luz brilha a partir do objeto e move-se com ele. Cobrir completamente o objeto afetado com algo opaco, como uma tigela ou um elmo, bloqueia a luz.\n\nSe qualquer área desta magia se sobrepuser a uma área de escuridão criada por uma magia de 3º círculo ou inferior, a magia que criou a escuridão é anulada."
},
{
  "nome": "Manto do Cruzado",
  "nivel": 3,
  "classes": ["Paladino"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Poder sagrado irradia de você em uma aura com um raio de 9 metros 30 ft., despertando bravura em criaturas amigáveis. Enquanto a magia durar, a aura, centrada em você, move-se para onde quer que você vá. Enquanto estiver dentro da aura, cada criatura não hostil (incluindo você) causa 1d4 pontos de dano radiante adicionais ao acertar um ataque armado."
},
{
  "nome": "Maremoto",
  "nivel": 3,
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "escola": "Invocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m 120 ft.",
  "componentes": "V S M (uma gota de água)",
  "duracao": "Instantânea",
  "descricao": "Você conjura uma onda de água que se choca contra uma área dentro do alcance. A área pode ter até 9m 30 ft. de comprimento, 3m 10 ft. de largura e 3m 10 ft. de altura. Cada criatura na área deve realizar salvaguarda de Destreza. Se fracassar, uma criatura sofre 4d8 de dano contundente e estará caída no chão. Se obtiver sucesso, uma criatura sofre metade desse dano e não será derrubada. A água então se espalha pelo solo em todas as direções. Extinguindo chamas desprotegidas em sua área e a até 9m 30 ft. dela."
},
{
  "nome": "Medo",
  "nivel": 3,
  "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "escola": "Ilusão",
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal (raio de 9m 30 ft.)",
  "componentes": "V S M (uma pena branca ou um coração de galinha)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você projeta uma imagem fantasmagórica dos piores medos de uma criatura. Cada criatura num cone de 9 metros 30 ft. deve ser bem-sucedida numa salvaguarda de Sabedoria ou derrubará o que estiver segurando e ficará amedrontada enquanto a magia durar.\n\nEm cada um dos turnos dela, a criatura deve executar a ação Correr e distanciar-se o máximo que puder de você pela rota mais segura disponível, a menos que não haja para onde ir. Se a criatura finalizar o turno dela em um local onde não possa mais vê-lo, ela pode fazer uma salvaguarda de Sabedoria. Em caso de sucesso, a magia se encerra para ela."
},
{
  "nome": "Mesclar-se às Rochas",
  "nivel": 3,
  "classes": ["Clérigo", "Druida"],
  "escola": "Transmutação",
  "tempo_conjuracao": "Uma ação ou Ritual",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "8 horas",
  "descricao": "Você pisa em um objeto ou superfície de pedra grande o suficiente para conter o seu corpo totalmente, mesclando a si mesmo e a todo o equipamento que estiver carregando enquanto a magia durar. Usando seu movimento, você pisa na pedra, tornando sua presença totalmente invisível ou indetectável por sentidos não-mágicos.\n\nEnquanto fundido à rocha, você não pode ver o que acontece fora dela, e quaisquer testes de Sabedoria (Percepção) que você fizer para ouvir sons do lado de fora são feitos com desvantagem. Você permanece ciente da passagem do tempo e pode conjurar magias em si mesmo enquanto mesclado à pedra. Você pode usar seu movimento para sair da pedra a qual se mesclou, encerrando a magia. Exceto isso, você não pode se mover.\n\nDano físico menor causado à rocha não lhe fere, mas a destruição parcial ou mudança no formato desta (de maneira que você não caiba mais dentro dela) o expele, causando 6d6 pontos de dano contundente. A completa destruição da pedra (ou transformação dela em uma substância diferente) também o expele, causando-lhe 50 pontos de dano contundente. Se expelido, você fica caído no espaço desocupado mais próximo de onde entrou na rocha."
},
{
  "nome": "Meteoros Momentâneos de Melf",
  "nivel": 3,
  "classes": ["Feiticeiro", "Mago"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V S M (salitre, enxofre e alcatrão de pinheiro formando um cordão)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Você cria seis pequenos meteoros no seu espaço. Eles voam no ar e orbitam você pela duração da magia. Quando você conjura essa magia – e com uma ação bônus em cada um dos turnos subsequentes – você pode gastar um ou dois meteoros, enviando-os diretamente para um ponto ou pontos que você escolher, a até 36m 120 ft. de você. Quando um meteoro alcança seu destino ou atinge uma superfície sólida, ele explode. Cada criatura a até 1,5 metro 5 ft. do ponto onde o meteoro explodiu deve realizar salvaguarda de Destreza. Uma criatura sofre 2d6 de dano de fogo se falhar, ou metade desse dano se obtiver sucesso.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, a quantidade de meteoros que você cria aumenta em dois para cada nível do espaço acima do 3º."
},
{
  "nome": "Montaria Fantasmagórica",
  "nivel": 3,
  "classes": ["Mago"],
  "escola": "Ilusão",
  "tempo_conjuracao": "1 minuto ou Ritual",
  "alcance": "9m 30 ft.",
  "componentes": "V S",
  "duracao": "Uma hora",
  "descricao": "Uma criatura Grande, quase real, similar a um cavalo, aparece no solo, surgindo num espaço desocupado à sua escolha e no alcance da magia. Você decide a aparência da montaria, mas ela é equipada com sela, estribo e arreio. Qualquer equipamento criado pela magia desaparece em uma nuvem de fumaça se movido a mais de 3 metros 10 ft. de distância da mesma.\n\nEnquanto a magia durar, uma criatura à sua escolha pode fazer uso da montaria. Utilize as estatísticas de um cavalo de montaria, exceto por seu deslocamento de 30 metros 100 ft. e por poder viajar 16 quilômetros 10 miles em uma hora ou 20 quilômetros 13 miles em trote rápido. Quando a magia termina, a montaria desaparece gradualmente, dando ao cavaleiro 1 minuto para desmontar. A magia se encerra se você dispensa a montaria ou se ela sofrer qualquer dano."
},
{
  "nome": "Mortalha Espiritual",
  "nivel": 3,
  "classes": ["Bruxo", "Clérigo", "Paladino", "Mago"],
  "escola": "Necromancia",
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Pessoal",
  "componentes": "V S",
  "duracao": "Concentração, Um minuto",
  "descricao": "Você invoca espíritos dos mortos, que voam ao seu redor durante o feitiço. Os espíritos são intangíveis e invulneráveis.\n\nAté o final da magia, qualquer ataque que você fizer causa 1d8 de dano extra quando você atinge uma criatura a até 3 metros 10 ft. de você. Este dano é radiante, necrótico ou gélido (sua escolha ao lançar a magia). Qualquer criatura que receber este dano não pode recuperar pontos de vida até o início do seu próximo turno.\n\nAlém disso, qualquer criatura de sua escolha que você possa ver e que comece seu turno a até 3 metros 10 ft. de você tem sua velocidade reduzida em 3 metros 10 ft. até o início do seu próximo turno.\n\nEm Níveis Superiores. Quando você lança essa magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d8 para cada dois círculos do espaço acima do 3º."
},
{
  "nome": "Muralha de Água",
  "nivel": 3,
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m 60 ft.",
  "componentes": "V S M (uma gota de água)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Você conjura uma muralha de água no solo, num ponto que você possa ver, dentro do alcance. Você pode fazer a muralha com até 9m 30 ft. de largura, 3m 10 ft. de altura e 30 centímetros 1 foot de espessura, ou você pode fazer uma muralha em forma de anel de 6m 20 ft. de diâmetro, 6m 20 ft. de altura e 30 centímetros 1 foot de espessura. A muralha desaparece quando a magia termina. O espaço da muralha é de terreno difícil. Qualquer ataque à distância com arma que entrar no espaço da muralha tem desvantagem na jogada de ataque, e dano de fogo é reduzido à metade se o efeito de fogo passar através da muralha para alcançar seu alvo. Magias que causem dano de gelo que passem através da muralha fazem com que a área da muralha por onde passaram se congele (pelo menos, uma seção de 1,5 metro 5 ft. é congelada). Cada 1,5 metro quadrado 5-foot-square de seção congelada tem CA 5 e 15 pontos de vida. Reduzir uma seção congelada a 0 pontos de vida a destrói. Quando uma seção é destruída, a muralha de água não a preenche."
},
{
  "nome": "Muralha de Areia",
  "nivel": 3,
  "classes": ["Mago"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "27m 90 ft.",
  "componentes": "V S M (um punhado de areia)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Você conjura uma muralha de areia rodopiante no solo, num ponto que você possa ver, dentro do alcance. Você pode fazer a muralha com até 9m 30 ft. de largura, 3m 10 ft. de altura e 3m 10 ft. de espessura, e ela desaparece quando a magia termina. Ela bloqueia a linha de visão, mas não o movimento. Uma criatura fica cega enquanto estiver no espaço da muralha e deve gastar 4,5m 15 ft. de movimento para cada 1,5 metro 5 ft. que se mover nela."
},
{
  "nome": "Muralha de Vento",
  "nivel": 3,
  "classes": ["Druida", "Patrulheiro"],
  "escola": "Evocação",
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m 120 ft.",
  "componentes": "V S M (um minúsculo leque e uma pluma de origem exótica)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Uma muralha de ventos fortes surge do chão em um ponto à sua escolha, no alcance da magia e permanece enquanto a magia durar. Ela pode ter até 15 metros 50 ft. de comprimento, 4,5 metros 15 ft. de altura e 30 centímetros 1 foot de espessura. Você pode moldá-la à sua escolha, desde que ela percorra um caminho contínuo no chão.\n\nQuando a muralha surge, cada criatura dentro da área deve fazer uma salvaguarda de Força. Se falhar, sofre 3d8 pontos de dano contundente, ou metade do dano em caso de sucesso.\n\nO vento forte mantém névoa, fumaça e outros gases à distância. Objetos e criaturas voadoras Pequenas ou menores não conseguem atravessar a muralha. Materiais leves e soltos, trazidos para dentro da muralha, voam para cima. Flechas, virotes e outros projéteis comuns, disparados contra alvos atrás da muralha, são defletidos para cima e erram automaticamente (pedras arremessadas por gigantes, máquinas de sítio ou projéteis similares não são afetados). Criaturas em forma gasosa não conseguem passar através da muralha."
},
{
    "nome": "Nevasca",
    "nivel": 3,
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (uma pitada de pó e algumas gotas de água)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Enquanto a magia durar, uma chuva congelante e granizo caem sobre um cilindro de 6 metros de altura [20-foot tall] com um raio de 12 metros [40-foot radius], centralizado em um ponto à sua escolha e no alcance da magia. A área fica totalmente obscurecida e as chamas expostas (caso existam na área) são extintas.\n\nO solo da área é coberto com gelo liso, tornando-o terreno difícil. Quando uma criatura entra na área da magia pela primeira vez ou inicia o próprio turno ali, ela deve fazer uma salvaguarda de Destreza. Se falhar, ela fica caída.\n\nSe uma criatura começar o próprio turno na área da magia e estiver se concentrando em uma magia, a criatura deve ser bem-sucedida em uma salvaguarda de Constituição contra a sua CD para evitar magia ou perderá a concentração."
},
{
    "nome": "Nuvem Fétida",
    "nivel": 3,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S M (um ovo podre ou várias folhas de repolho)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você cria uma esfera com raio de 6 metros [20-foot-radius sphere], feita de um gás amarelo e nauseabundo, centrado em um ponto à sua escolha e no alcance da magia. A nuvem se alastra, contornando os cantos e a área afetada fica totalmente obscurecida. Ela persiste enquanto a magia durar.\n\nCada criatura que estiver totalmente dentro da nuvem no início do próprio turno, deve fazer uma salvaguarda de Constituição contra veneno. Se falhar, a criatura gasta uma ação naquele turno vomitando e cambaleando. Criaturas que não precisam respirar ou são imunes a veneno têm sucesso automático nesta salvaguarda.\n\nUm vento moderado (de pelo menos 15 quilômetros [10 miles] por hora) dispersa a nuvem após 4 rodadas. Um vento forte (de pelo menos 30 quilômetros [20 miles] por hora) a dispersa após 1 rodada."
},
{
    "nome": "Padrão Hipnótico",
    "nivel": 3,
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "S M (uma vareta de incenso brilhante ou um frasco de cristal cheio de material fosforescente)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você cria um padrão distorcido de cores o qual serpenteia no ar dentro de um cubo de 9 metros de lado [30-foot cube], no alcance da magia. O padrão aparece por um momento e desaparece. Cada criatura na área, e que seja capaz de ver o padrão, deve fazer uma salvaguarda de Sabedoria. Se falhar, a criatura fica enfeitiçada enquanto a magia durar. Criaturas afetadas por esta magia estão incapacitadas e tem deslocamento igual a 0.\n\nUma criatura afetada por esta magia terá os efeitos encerrados sobre si caso venha a sofrer qualquer tipo de dano ou se alguém usar uma ação para sacudi-la, removendo-a de seu estupor."
},
{
    "nome": "Palavra Curativa em Massa",
    "nivel": 3,
    "classes": ["Clérigo"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Conforme você diz palavras de restauração, até seis criaturas à sua escolha, à sua vista e no alcance da magia, recuperam uma quantidade de pontos de vida igual a 1d4 + seu modificador de atributo de conjuração. Essa magia não tem efeito sobre mortos-vivos ou constructos.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, a cura aumenta em 1d4 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Passo Trovejante",
    "nivel": 3,
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Você se teletransporta para um espaço desocupado que você pode ver dentro do alcance. Imediatamente depois de você desaparecer, um som estrondoso soa, e cada criatura a menos de 3m [10 ft.] do espaço que você deixou deve fazer salvaguarda de Constituição, sofrendo 3d10 de dano de trovão em uma falha, ou metade de dano em um sucesso. O trovão pode ser ouvido de até 90m [300 ft.] de distância. Você pode levar objetos com você, desde que seu peso não exceda o que você pode transportar. Você também pode teletransportar uma criatura disposta do seu tamanho ou menor, que esteja transportando equipamentos até sua capacidade de carga. A criatura deve estar dentro de 1,5m [5 ft.] de você quando você conjurar esta magia, e deve haver um espaço desocupado dentro de 1,5m [5 ft.] do seu espaço de destino para que a criatura apareça; de outra forma, a criatura é deixada para trás.\n\nEm Níveis Superiores. Quando você conjura esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d10 para cada nível do espaço de magia acima de 3º."
},
{
    "nome": "Pequeno Refúgio de Leomund",
    "nivel": 3,
    "classes": ["Bardo", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Pessoal (hemisfério com raio de 3m [10 ft.])",
    "componentes": "V S M (uma pequena conta de cristal)",
    "duracao": "8 horas",
    "descricao": "Um domo imóvel com 3 metros de raio [10-foot-radius dome], feito de energia, surge ao redor e acima de você, permanecendo estacionário enquanto a magia durar. A magia termina se você deixar a área do domo.\n\nAlém de você, até nove criaturas de tamanho Médio cabem dentro do domo. Se uma criatura maior ou mais do que nove criaturas encontrarem-se dentro da área da magia, ela falha. Criaturas e objetos dentro do domo no ato da conjuração podem se mover através dele livremente. Todas as outras criaturas e objetos são impedidos de atravessá-lo, o mesmo valendo para magias e outros efeitos mágicos. A atmosfera interna é confortável e seca, independentemente do clima externo.\n\nAté o fim da magia, você pode determinar se no interior reina a meia-luz ou a escuridão. Do lado de fora, o domo é de uma cor opaca, à sua escolha, mas é transparente para quem estiver dentro."
},
{
    "nome": "Pequeno Servo",
    "nivel": 3,
    "classes": ["Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "1 minuto",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "8 horas",
    "descricao": "Você toca um objeto minúsculo não mágico que não está ligado a outro objeto ou a uma superfície e não está sendo carregado por outra criatura. O alvo anima e brota pequenos braços e pernas, tornando-se uma criatura sob seu controle até a magia terminar ou a criatura cair para 0 pontos de vida. Veja o bloco de estatísticas para suas estatísticas.\n\nPequeno Servo\nConstruto minúsculo, não-alinhado\nClasse de Armadura: 15 (armadura natural)\nPontos de Vida: 10 (4d4)\nVelocidade: 9m [30 ft.], escalar 9m [30 ft.]\nFOR: 4 (-3)\nDES: 16 (+3)\nCON: 10 (+0)\nINT: 2 (-4)\nSAB: 10 (+0)\nCAR: 1 (-5)\nImunidades a Danos: veneno, psíquico\nImunidades a Condições: cego, encantado, surdo, exausto, amedrontado, paralizado, petrificado, envenenado\nSentidos: visão cega 18m [60 ft.] (cego para além desse raio), Percepção passiva 10\nLínguas: –\nAções:\nBatida. Ataque de Arma Corpo a Corpo: +5 para atingir, alcance 1,5m [5 ft.], um alvo. Acerto: 5 (1d4 + 3) de dano de contusão.\nComo uma ação bônus, você pode comandar mentalmente a criatura se estiver a menos de 36m [120 ft.] de você. (Se você controla múltiplas criaturas com esta magia, você pode comandar qualquer uma ou todas elas ao mesmo tempo, emitindo o mesmo comando a cada uma.) Você decide quais ações a criatura irá tomar e para onde ela se moverá durante seu próximo turno, ou você pode emitir um comando geral simples, de modo a buscar uma chave, ficar de guarda, ou empilhar alguns livros. Se você não emitir nenhum comando, o servo não faz nada além de se defender contra criaturas hostis. Uma vez que uma ordem é dada, o servo continua a seguir essa ordem até que sua tarefa esteja completa.\nQuando a criatura cai para 0 pontos de vida, ela retorna à sua forma original, e qualquer dano restante vaza para essa forma.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, você pode animar dois objetos adicionais para cada nível do espaço de magia acima do 3º."
},
{
    "nome": "Proteção Contra Energia",
    "nivel": 3,
    "classes": ["Artífice", "Clérigo", "Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você toca uma criatura voluntária. Enquanto a magia durar, o alvo passa a ter resistência a um tipo de dano à sua escolha: ácido, elétrico, ígneo, gélido ou trovejante."
},
{
    "nome": "Relâmpago",
    "nivel": 3,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal (linha de 30m [100 ft.])",
    "componentes": "V S M (um punhado de pelos e um cajado de âmbar, cristal ou vidro)",
    "duracao": "Instantânea",
    "descricao": "Um raio formando uma linha de 30 metros [100 ft.] de comprimento por 1,5 metro [5 ft.] de largura dispara a partir de você em uma direção à sua escolha. Cada criatura na linha deve fazer uma salvaguarda de Destreza. Se falhar, sofre 8d6 pontos de dano elétrico, ou metade do dano em caso de sucesso.\n\nO raio incendeia objetos inflamáveis na área que não estejam sendo usados ou carregados.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Remeter",
    "nivel": 3,
    "classes": ["Clérigo", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Ilimitado",
    "componentes": "V S M (um pequeno pedaço de um fio fino de cobre)",
    "duracao": "Uma rodada",
    "descricao": "Uma mensagem de vinte e cinco palavras ou menos é enviada para uma criatura conhecida. A criatura ouve a mensagem mentalmente, reconhece você como o remetente, caso lhe conheça, e pode responder da mesma maneira imediatamente. A magia permite que criaturas com o valor de Inteligência mínimo de 1 entendam o sentido da sua mensagem.\n\nA mensagem pode ser enviada a qualquer distância e até a outros planos de existência, mas se o alvo estiver em um plano diferente do seu, existe uma chance de 5% de que ela não seja entregue."
},
{
    "nome": "Remover Maldição",
    "nivel": 3,
    "classes": ["Bruxo", "Clérigo", "Mago", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Ao tocar uma criatura ou objeto, todas as maldições lançadas sobre eles se encerram. Se o objeto for um item mágico amaldiçoado, a maldição se mantém, mas a magia quebra a sintonia do dono com o objeto, de modo que ele pode ser removido ou descartado."
},
{
    "nome": "Respirar na Água",
    "nivel": 3,
    "classes": ["Artífice", "Druida", "Feiticeiro", "Patrulheiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um caniço curto ou um pedaço de palha)",
    "duracao": "24 horas",
    "descricao": "Até dez criaturas voluntárias à sua vista e no alcance da magia, ganham a habilidade de respirar embaixo d'água enquanto a magia durar. As criaturas afetadas pela magia ainda conservam sua forma natural de respiração."
},
{
    "nome": "Revivificar",
    "nivel": 3,
    "classes": ["Artífice", "Clérigo", "Paladino"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (diamantes no valor mínimo de 300 PO, que a magia consome)",
    "duracao": "Instantânea",
    "descricao": "Você toca uma criatura que faleceu há menos de um minuto. Aquela criatura volta à vida com 1 ponto de vida. A magia não pode retornar quem morreu de idade avançada, nem pode restaurar quaisquer partes perdidas do corpo."
},
{
    "nome": "Rogar Maldição",
    "nivel": 3,
    "classes": ["Bardo", "Clérigo", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Quando você toca uma criatura, ela deve ser bem-sucedida em uma salvaguarda de Sabedoria ou torna-se amaldiçoada enquanto a magia durar. Ao conjurar esta magia, você deve escolher a natureza da maldição, entre as seguintes opções:\n\nEscolha um atributo. Enquanto amaldiçoado, o alvo tem desvantagem nos testes de atributo e salvaguardas feitas com este atributo.\n\nEnquanto amaldiçoado, o alvo tem desvantagem nas jogadas de ataque contra você.\n\nEnquanto amaldiçoado, o alvo deve fazer uma salvaguarda de Sabedoria no início de cada um dos turnos dele. Se falha, desperdiça a própria ação nesse turno, ficando sem fazer nada.\n\nEnquanto o alvo está amaldiçoado, seus ataques e magias contra ele causam 1d8 pontos de dano necrótico extra.\n\nUma magia Remover Maldição encerra o efeito da magia. À escolha do DM, você pode optar por um efeito de maldição alternativo, mas ele não deve ser mais poderoso do que os descritos acima. O DM tem a palavra final sobre este efeito da maldição alternativa.\n\nEm Níveis Superiores. Se você conjurar esta magia usando um espaço de magia de 4º círculo ou superior, a duração dela será Concentração, até 10 minutos. Se você usar um espaço de magia de 5º círculo ou superior, a duração passa a ser 8 horas. Se você usar um espaço de magia de 7º círculo ou superior, a duração passa a ser 24 horas. Se você usar um espaço de magia de 9º círculo, a magia dura até ser dissipada. Usar um espaço de magia de 5º círculo ou superior concede uma duração que não requer concentração."
},
{
    "nome": "Simular Morte",
    "nivel": 3,
    "classes": ["Bardo", "Clérigo", "Druida", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Toque",
    "componentes": "V S M (uma pitada de poeira de túmulo)",
    "duracao": "Uma hora",
    "descricao": "Você toca uma criatura voluntária e a coloca em um estado cataléptico indistinguível da morte.\n\nO alvo aparenta estar morto para todas as inspeções externas e todas as magias usadas para determinar o estado dele, enquanto a magia durar, ou até você usar uma ação para tocá-lo e dispensar a magia. O alvo está cego, incapacitado, e com deslocamento reduzido para 0. Ele tem resistência a todos os tipos de dano, exceto dano psíquico.\n\nSe o alvo estiver doente ou envenenado quando você conjurar a magia, ou ficar doente ou envenenado enquanto estiver sob o efeito dela, a doença e o veneno não surtem efeito até a magia acabar."
},
{
    "nome": "Sinal de Esperança",
    "nivel": 3,
    "classes": ["Clérigo"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Esta magia concede esperança e vitalidade. Escolha qualquer número de criaturas dentro do alcance da magia. Durante a duração desta magia, cada alvo terá vantagem em salvaguardas de Sabedoria e contra a morte, além de recuperar a quantidade máxima de pontos de vida possível de qualquer fonte de cura."
},
{
    "nome": "Soneca",
    "nivel": 3,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "S M (uma pitada de areia)",
    "duracao": "10 minutos",
    "descricao": "Você faz um gesto acalmante e até três criaturas dispostas à sua escolha que você pode ver dentro do alcance caem inconscientes pela duração da magia. A magia termina em um alvo prematuramente se ele levar dano ou alguém usar uma ação para acordá-lo, sacudindo ou estapeando. Se o alvo continuar inconsciente pela duração completa, o alvo ganha os benefícios de um descanso curto e não pode ser afetado por esta magia novamente até que termine um descanso longo.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, você pode adicionar uma criatura disposta extra como alvo para cada nível do espaço acima do 3º."
},
{
    "nome": "Toque Vampírico",
    "nivel": 3,
    "classes": ["Bruxo", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "O toque de sua mão, envolta por sombra, pode retirar força vital de outros para curar as suas próprias feridas. Faça um ataque mágico corpo a corpo contra uma criatura no seu alcance. Se o ataque for bem-sucedido, o alvo sofre 3d6 pontos de dano necrótico e você recupera uma quantidade de pontos de vida igual à metade da quantidade de dano necrótico causado. Enquanto a magia durar, você pode fazer o ataque novamente em cada um de seus turnos, com uma ação.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 3º."
},
{
    "nome": "Transferência de Vida",
    "nivel": 3,
    "classes": ["Clérigo", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você sacrifica parte de sua saúde para reparar lesões de outra criatura. Você sofre 4d8 de dano necrótico e uma criatura a sua escolha que você pode ver dentro do alcance recupera uma quantidade de pontos de vida iguais ao dobro do dano necrótico que você sofre.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d8 para cada nível do espaço de magia acima do 2º."
},
{
    "nome": "Voo",
    "nivel": 3,
    "classes": ["Artífice", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (uma pena da asa de qualquer pássaro)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Você toca uma criatura voluntária. O alvo ganha um deslocamento de voo de 18 metros [60 ft.] enquanto a magia durar. Ao término da magia, caso o alvo ainda esteja no ar, ele cai, a menos que possa parar a queda.\n\nEm Níveis Superiores. Ao conjurar esta magia utilizando um espaço de magia de 4º círculo ou superior, você pode escolher uma criatura alvo adicional para cada círculo do espaço acima do 3º."
}
]