magias_nivel_2 = [
{
    "nome": "Abraço Terrestre de Maximilian",
    "nivel": 2,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma mão em miniatura esculpida em barro)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você escolhe espaço desocupado de 1,5 metro quadrado [5-foot-square] no solo que você possa ver, dentro do alcance. Uma mão Média feita de solo compacto se ergue ali e alcança uma criatura que você possa ver a até 1,5 metro [5 ft.] dela. O alvo deve realizar salvaguarda de Força. Se falhar, o alvo sofre 2d6 de dano contundente e fica impedido pela duração da magia. Com uma ação, você pode fazer com que a mão esmague o alvo impedido, que deve realizar salvaguarda de Força. Ele sofre 2d6 de dano contundente se falhar, ou metade desse dano se obtiver sucesso. Para se libertar, o alvo impedido pode realizar um teste de Força contra a CD de resistência da sua magia. Se obtiver sucesso, o alvo escapa e não estará mais impedido pela mão. Com uma ação bônus, você pode fazer a mão alcançar uma criatura diferente ou se mover para um espaço desocupado diferente, dentro do alcance. A mão solta um alvo impedido se você fizer isso."
},
{
    "nome": "Acalmar Emoções",
    "nivel": 2,
    "classes": ["Bardo", "Clérigo"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você tenta suprimir emoções fortes em um grupo de criaturas. Cada humanoide dentro de uma esfera de 6 metros de raio [20-foot-radius sphere] centrada em um ponto dentro do alcance da magia deve fazer uma salvaguarda de Carisma; uma criatura pode escolher falhar nesta salvaguarda, caso deseje. Se uma criatura falhar na salvaguarda, escolha um dos dois efeitos a seguir.\n\nVocê pode suprimir qualquer efeito que cause a um alvo as condições enfeitiçado ou amedrontado. Quando esta magia termina, qualquer efeito suprimido retorna, caso a duração não tenha expirado nesse meio-tempo.\n\nComo alternativa, você pode tornar o alvo indiferente a criaturas, à sua escolha, contra as quais o alvo era hostil. Tal indiferença termina se o alvo for atacado ou ferido por uma magia, ou se testemunhar quaisquer de seus próprios amigos sendo feridos. Quando a magia termina, a criatura torna-se hostil novamente, a menos que o DM decida de outra forma."
},
{
    "nome": "Agarrão da Terra",
    "nivel": 2,
    "classes": ["Bruxo", "Druida", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "90m [300 ft.]",
    "componentes": "V",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Escolha uma criatura que você possa ver, dentro do alcance. Laços amarelados de energia mágica rodeiam a criatura. O alvo deve ser bem sucedido em salvaguarda de Força ou seu deslocamento de voo (se possuir) será reduzido para 0m [0 ft.] pela duração da magia. Uma criatura voadora afetada por essa magia desce 18m [60 ft.] por turno até aterrissar no solo ou a magia acabar."
},
{
    "nome": "Alterar-se",
    "nivel": 2,
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você assume uma forma diferente. Quando conjurar a magia, escolha uma das opções a seguir, cujos efeitos persistem enquanto a magia durar. Dentro desse período, você pode usar uma ação para finalizar uma das opções escolhidas, e obter os benefícios de outra.\n\nAdaptação Aquática. Você adapta seu corpo para o ambiente aquático, com guelras crescendo e membranas nascendo entre seus dedos. Você pode respirar debaixo d'água e ganha deslocamento de natação com valor igual ao seu deslocamento de caminhada.\n\nMudar Aparência. Você transforma sua aparência conforme desejar, alterando sua altura, peso, características raciais, som da voz, comprimento do cabelo, cor da pele e características peculiares, se existirem. Você pode adquirir a aparência de outra raça, embora nenhuma de suas estatísticas mude. Você não pode parecer com uma criatura de tamanho diferente do seu, e sua forma básica permanece a mesma; por exemplo, se você é bípede, você não pode usar a magia para se tornar quadrúpede. A qualquer momento, enquanto a magia durar, você pode usar sua ação para trocar de aparência novamente.\n\nArmas Naturais. Crescem em seu corpo garras, presas, espinhos, chifres ou uma arma natural diferente, à sua escolha. Seu ataque desarmado causa 1d6 pontos de dano contundente, cortante ou perfurante, conforme a arma natural escolhida, e você é proficiente com seus ataques desarmados. Por fim, sua arma natural é mágica e você tem um bônus de +1 em suas jogadas de ataque e dano quando usá-la."
},
{
    "nome": "Aprimorar Atributo",
    "nivel": 2,
    "classes": ["Artífice", "Bardo", "Clérigo", "Druida", "Feiticeiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (pelo ou uma pena de uma fera)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você toca uma criatura e lança sobre ela um aperfeiçoamento mágico. Escolha um dos efeitos a seguir; o alvo ganha esse efeito enquanto a magia durar.\n\nAstúcia da Raposa. O alvo tem vantagem nos testes de Inteligência.\n\nElegância do Gato. O alvo tem vantagem nos testes de Destreza. Ele também não sofre dano por queda ao cair 6 metros [20 ft.] ou menos, caso não esteja incapacitado.\n\nEsplendor da Águia. O alvo tem vantagem nos testes de Carisma.\n\nForça do Touro. O alvo tem vantagem nos testes de Força e dobra a capacidade de carga.\n\nResistência do Urso. O alvo tem vantagem nos testes de Constituição. Ele também ganha 2d6 pontos de vida temporários que são perdidos ao término da magia.\n\nSabedoria da Coruja. O alvo tem vantagem nos testes de Sabedoria.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, você pode atingir uma criatura adicional para cada círculo do espaço acima do 2º."
},
{
    "nome": "Arma Espiritual",
    "nivel": 2,
    "classes": ["Clérigo"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "1 minuto",
    "descricao": "Você cria uma arma espectral flutuante, no alcance da magia. A arma permanece enquanto a magia durar, ou até você conjurar essa magia novamente. Ao conjurar a magia, você faz um ataque mágico corpo a corpo contra uma criatura a até 1,5 [5 ft.] da arma. Se acertar, o alvo sofre dano energético igual a 1d8 + seu modificador de atributo de conjuração.\n\nCom uma ação bônus em seu turno, você pode mover a arma até 6 metros [20 ft.] e repetir o ataque contra uma criatura a até 1,5 metro [5 ft.] dela.\n\nA arma pode tomar qualquer forma desejada. Clérigos de divindades associadas a uma arma específica (São Cuthbert é conhecido por sua maça e Thor por seu martelo) fazem o efeito desta magia se assemelhar a esta arma.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d8 para cada dois espaços de magia acima do 2º círculo."
},
{
    "nome": "Arma Mágica",
    "nivel": 2,
    "classes": ["Artífice", "Mago", "Paladino"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Toque",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você toca uma arma não-mágica. Enquanto a magia durar, essa arma se torna uma arma mágica com bônus de +1 para jogadas de ataque e dano.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o bônus aumenta para +2. Quando você usa um espaço de magia de 6º círculo ou superior, o bônus aumenta para +3."
},
{
    "nome": "Arrombar",
    "nivel": 2,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V",
    "duracao": "Instantânea",
    "descricao": "Escolha um objeto à sua vista e no alcance da magia. O objeto pode ser uma porta, uma caixa, um baú, um par de algemas, um cadeado ou outro objeto que contenha um meio mundano ou mágico que impeça o acesso.\n\nUm alvo que seja mantido fechado por uma fechadura mundana ou que esteja emperrado ou obstruído torna-se destrancado, desemperrado ou desobstruído. Se o objeto possui várias fechaduras, apenas uma delas é destrancada.\n\nSe você escolher um alvo mantido fechado com tranca arcana, os efeitos sobre ele ficam suprimidos por 10 minutos, durante os quais o alvo pode ser aberto e fechado normalmente.\n\nAo conjurar a magia, um estrondo, audível a até 90 metros [300 ft.], emana do objeto escolhido como alvo."
},
{
    "nome": "Augúrio",
    "nivel": 2,
    "classes": ["Clérigo"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "Pessoal",
    "componentes": "V S M (varetas, ossos ou símbolos semelhantes especialmente marcados, no valor de pelos menos 25 PO)",
    "duracao": "Instantânea",
    "descricao": "Ao lançar varetas incrustadas com pedras preciosas, jogar ossos de dragão, dispor cartas ornamentadas ou empregar alguma outra ferramenta de adivinhação, você recebe um presságio de uma entidade de outro mundo sobre os resultados de um determinado curso de ação que você planeja tomar dentro dos próximos 30 minutos. O DM escolhe entre os seguintes presságios possíveis:\n\nProsperidade, para bons resultados\nInfortúnio, para maus resultados\nProsperidade e Infortúnio, para resultados bons e maus\nNada, para resultados que não são especialmente bons ou maus\n\nA magia não leva em conta quaisquer circunstâncias possíveis que possam mudar o resultado futuro, como a conjuração de magias adicionais ou a perda ou ganho de um companheiro.\n\nCaso você conjure a magia duas ou mais vezes antes de concluir seu próximo descanso longo, há uma chance cumulativa de 25% para cada conjuração após a primeira de você obter uma resposta aleatória. O DM faz esta jogada em segredo."
},
{
    "nome": "Aumentar/Reduzir",
    "nivel": 2,
    "classes": ["Artífice", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma pitada de pó de ferro)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você faz com que uma criatura ou um objeto, à sua vista e dentro do alcance da magia, fique maior ou menor enquanto a magia durar. Escolha uma criatura ou um objeto que não esteja sendo usado ou carregado. Se o alvo não for voluntário, ele pode fazer uma salvaguarda de Constituição. Em caso de sucesso, a magia não surte efeito.\n\nSe o alvo for uma criatura, tudo o que estiver usando e carregando muda de tamanho junto com ela. Qualquer item descartado por uma criatura afetada por esta magia retorna, imediatamente, ao tamanho normal.\n\nAumentar. O tamanho do alvo dobra em todas as dimensões, e o peso é multiplicado por oito. O tamanho aumenta em uma categoria - de Médio para Grande, por exemplo. Se não houver espaço suficiente para o alvo dobrar o próprio tamanho, ele atinge o tamanho máximo possível no espaço disponível. Enquanto a magia durar, o alvo também tem vantagem em testes de Força e salvaguardas de Força. As armas dele também crescem para combinar com o novo tamanho. Se o alvo realizar um ataque bem-sucedido com essas armas, elas causam 1d4 pontos de dano a mais do que o normal da arma enquanto estiverem ampliadas.\n\nReduzir. O tamanho do alvo é reduzido à metade em todas as dimensões, e o peso é reduzido para um oitavo do normal. Essa redução diminui o tamanho do alvo em uma categoria - de Médio para Pequeno, por exemplo. Enquanto a magia durar, o alvo tem desvantagem em testes de Força e salvaguardas de Força. As armas dele também encolhem para combinar com o novo tamanho. Se o alvo realizar um ataque bem-sucedido com essas armas, elas causam 1d4 pontos de dano a menos que o normal da arma enquanto estiverem reduzidas (o dano mínimo é 1)."
},
{
    "nome": "Aura Mágica de Nystul",
    "nivel": 2,
    "classes": ["Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (um pequeno quadrado de seda)",
    "duracao": "24 horas",
    "descricao": "Você toca uma criatura ou objeto, criando uma ilusão sobre o alvo e fazendo com que magias de adivinhação revelem informações falsas sobre ele. O alvo pode ser uma criatura voluntária ou um objeto que não esteja sendo carregado ou usado por outra criatura.\n\nAo conjurar a magia, escolha um ou ambos os efeitos a seguir. O efeito fica ativo enquanto a magia durar. Se você conjurar esta magia na mesma criatura ou objeto todos os dias durante 30 dias, colocando o mesmo efeito toda vez, a ilusão dura até ser dissipada.\n\nFalsa Aura. Você altera a maneira como o alvo parece para magias e efeitos mágicos, como Detectar Magia, que detectam auras mágicas. Você pode fazer um objeto não mágico parecer mágico, um objeto mágico parecer não mágico ou alterar a aura mágica do objeto, de modo que ele pareça pertencer a uma escola específica de magia que você escolher. Quando usar este efeito em um objeto, você pode fazer com que a magia falsa fique aparente para qualquer criatura que manipule o item.\n\nMáscara. Você altera a maneira como o alvo parece para magias e efeitos mágicos que detectam tipos de criatura, como o Sentido Divino de um paladino ou o gatilho de uma magia Símbolo. Você escolhe um tipo de criatura e outras magias e efeitos mágicos passam a tratar o alvo como se este pertencesse ao tipo ou alinhamento da criatura escolhida."
},
{
    "nome": "Auxílio",
    "nivel": 2,
    "classes": ["Artífice", "Clérigo", "Paladino"],
    "escola": "Abjuração",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (uma pequena tira de tecido branco)",
    "duracao": "8 horas",
    "descricao": "Esta magia reforça seus aliados com tenacidade e determinação. Escolha até três criaturas dentro do alcance. Os pontos de vida máximos e os pontos de vida atuais de cada alvo aumentam em 5 enquanto a magia durar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, os pontos de vida do alvo aumentam em 5 pontos adicionais para cada círculo do espaço acima do 2º."
},
{
    "nome": "Bafo de Dragão",
    "nivel": 2,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação bônus",
    "alcance": "Toque",
    "componentes": "V S M (uma pimenta ardida)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Você toca uma criatura disposta e a imbui com o poder de cuspir energia mágica de sua boca, desde que tenha uma. Escolha ácido, frio, fogo, elétrico ou veneno. Até a magia terminar, a criatura pode usar uma ação para exalar energia do tipo escolhido em um cone de 4,5m [15-foot cone]. Cada criatura nessa área deve fazer salvaguarda de Destreza, tomando um dano de 3d6 do tipo escolhido em uma falha, ou metade de dano em um bem sucedido.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d6 para cada nível do espaço de magia acima do 2º."
},
{
    "nome": "Boca Encantada",
    "nivel": 2,
    "classes": ["Artífice", "Bardo", "Mago"],
    "escola": "Ilusão",
    "tempo_conjuracao": "1 minuto ou Ritual",
    "alcance": "9m [30 ft.]",
    "componentes": "V S M (um pequeno pedaço de favo de mel e pó de jade valendo pelo menos 10 PO, os quais são consumidos pela magia)",
    "duracao": "Até ser dissipada",
    "descricao": "Você implanta uma mensagem em um objeto que esteja no alcance da magia. Essa mensagem é revelada quando uma circunstância de disparo ocorrer. Escolha um objeto à sua vista e que não esteja sendo usado ou carregado por outra criatura. Fale, então, a mensagem, que deve ter 25 palavras ou menos, embora ela possa ser emitida ao longo de um período de até 10 minutos. Por fim, determine a circunstância de disparo para magia revelar a mensagem.\n\nQuando tal circunstância ocorrer, uma boca encantada aparece no objeto e recita a mensagem com a sua voz e no mesmo volume que você falou. Se o objeto escolhido tiver uma boca ou algo que se assemelhe (por exemplo, a boca de uma estátua), a boca encantada se sobrepõe de forma a parecer que as palavras saem da boca do próprio objeto. Ao conjurar a magia, você determina se ela se encerra após entregar a mensagem ou se permanece para repetir o conteúdo sempre que a circunstância de disparo ocorrer.\n\nA circunstância de disparo pode ser tão abrangente ou específica quanto você quiser, mas deve ser baseada em condições visuais ou auditivas que ocorram a até 9 metros [30 ft.] do objeto."
},
{
    "nome": "Cativar",
    "nivel": 2,
    "classes": ["Bardo", "Bruxo"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S",
    "duracao": "1 minuto",
    "descricao": "Você dita uma sequência de palavras dispersivas, fazendo com que criaturas à sua escolha, à sua vista, dentro do alcance da magia e que possam ouvi-lo, façam uma salvaguarda de Sabedoria. Qualquer criatura que não possa ser enfeitiçada é automaticamente bem-sucedida na salvaguarda, e se você ou seus companheiros estiverem combatendo a criatura alvo, ela tem vantagem nesse teste. Se falhar, o alvo tem desvantagem nos testes de Sabedoria (Percepção) para perceber qualquer outra criatura que não seja o conjurador, enquanto a magia durar ou até que o alvo não consiga mais ouvi-lo. A magia termina se você estiver incapacitado ou se não puder mais falar."
},
{
    "nome": "Cegueira/Surdez",
    "nivel": 2,
    "classes": ["Bardo", "Clérigo", "Feiticeiro", "Mago"],
    "escola": "Necromancia",
    "tempo_conjuracao": "Uma ação",
    "alcance": "9m [30 ft.]",
    "componentes": "V",
    "duracao": "1 minuto",
    "descricao": "Você pode cegar ou ensurdecer um inimigo. Escolha um alvo à sua vista e que esteja no alcance desta magia. Ele deve fazer uma salvaguarda de Constituição. Se falhar, fica cego ou surdo (à sua escolha) enquanto a magia durar. No final de cada um dos turnos dele, o alvo pode realizar uma salvaguarda de Constituição. Se for bem-sucedido, a magia se encerra.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, você pode atingir uma criatura adicional para cada círculo do espaço acima do 2º."
},
{
    "nome": "Chama Contínua",
    "nivel": 2,
    "classes": ["Artífice", "Clérigo", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (rubi em pó no valor mínimo de 50 PO, o qual a magia consome)",
    "duracao": "Até ser dissipada",
    "descricao": "Uma chama, brilhante como uma tocha, surge de um objeto que você toca. O efeito assemelha-se ao de uma chama comum, exceto pelo fato de não emitir calor nem consumir oxigênio. Uma chama contínua pode ser coberta ou escondida, mas não apagada ou abafada."
},
{
    "nome": "Chicote Mental de Tasha",
    "nivel": 2,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V",
    "duracao": "Uma rodada",
    "descricao": "Você ataca psiquicamente uma criatura que pode ver dentro do alcance. O alvo deve fazer uma Salvaguarda de Inteligência. Em uma falha, o alvo sofre 3d6 de dano psíquico e não pode usar sua Reação até o final de seu próximo turno. Além disso, em seu próximo turno, ele deve escolher entre se mover, realizar uma Ação ou realizar uma Ação Bônus; apenas um dos três. Em um sucesso, o alvo sofre metade do dano e nenhum dos outros efeitos da magia.\n\nEm Níveis Superiores. Quando você conjura esta magia usando um espaço de magia de 3º círculo ou superior, você pode ter como alvo uma criatura adicional para cada círculo do espaço acima do 2º. As criaturas devem estar a 9 metros [30 ft.] uma da outra quando você as mira."
},
{
    "nome": "Chuva de Bolas de Neve de Snilloc",
    "nivel": 2,
    "classes": ["Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "27m [90 ft.]",
    "componentes": "V S M (um pedaço de gelo ou uma pequena lasca de pedra branca)",
    "duracao": "Instantânea",
    "descricao": "Uma rajada de bolas de neve mágicas emerge de um ponto que você escolher, dentro do alcance. Cada criatura numa esfera de 1,5 metro de raio [5-foot-radius] centrada no ponto deve realizar salvaguarda de Destreza. Uma criatura sofre 3d6 de dano de gelo se falhar, ou metade desse dano se obtiver sucesso.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 2º."
},
{
    "nome": "Convocar Montaria",
    "nivel": 2,
    "classes": ["Paladino"],
    "escola": "Invocação",
    "tempo_conjuracao": "10 minutos",
    "alcance": "9m [30 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você invoca um espírito que assume a forma de uma montaria especialmente inteligente, forte e fiel, criando um vínculo de longa duração com ela. Aparecendo em um espaço desocupado dentro do alcance, a montaria toma uma forma à sua escolha: um alce, um camelo, um cavalo de guerra, um mastim ou um pônei (seu DM pode permitir que outros animais sejam conjurados como montarias). A montaria tem as estatísticas da forma escolhida, mas é um celestial, feérico ou ínfero (à sua escolha), em vez do tipo normal. Além disso, se a criatura tiver uma Inteligência igual ou menor que 5, esta se torna 6 e ela adquire a capacidade de entender um idioma que você possa falar, à sua escolha.\n\nEla serve como sua montaria, tanto em combate quanto fora dele, e vocês têm um elo instintivo que lhes permite lutar como uma unidade perfeita. Enquanto estiver montado na criatura, qualquer magia que você conjurar e que tenha a si mesmo como alvo, afeta também a sua montaria.\n\nQuando a criatura ficar com 0 pontos de vida, ela desaparece, não deixando corpo algum para trás. Você também pode dispensar sua montaria a qualquer momento com uma ação, fazendo-a desaparecer. Em ambos os casos, conjurar esta magia novamente invoca o mesmo animal, restaurado com pontos de vida máximos.\n\nEnquanto sua montaria estiver a até 1,5 quilômetro [1 mile] de você, é possível se comunicar telepaticamente com ela.\n\nNão é possível ter mais de uma montaria vinculada por esta magia ao mesmo tempo. Com uma ação, você pode liberar a montaria de seu vínculo a qualquer momento, fazendo-a desaparecer."
},
{
    "nome": "Corda Extradimensional",
    "nivel": 2,
    "classes": ["Artífice", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (extrato de milho em pó e um laço torcido de pergaminho)",
    "duracao": "Uma hora",
    "descricao": "Você toca um pedaço de corda de até 18 metros [60 ft.] de comprimento. Uma extremidade da corda, em seguida, sobe para o ar, até ficar perpendicular ao solo. Na extremidade superior da corda, uma entrada invisível se abre para um espaço extradimensional enquanto a magia durar.\n\nO espaço extradimensional pode ser alcançado escalando-se a corda até o topo. O espaço pode conter até oito criaturas de tamanho Médio ou menores. A corda pode ser puxada para o espaço, fazendo com que desapareça de vista para quem está de fora do espaço.\n\nAtaques e magias não podem atravessar a entrada, seja para dentro ou para fora do espaço extradimensional, mas quem está dentro pode ver do lado de fora, como se olhasse através de uma janela de 1,00 x 1,50 metro [3-foot-by-5-foot], tendo a corda como centro.\n\nQualquer coisa dentro do espaço extradimensional cai quando a magia termina."
},
{
    "nome": "Cordão de Flechas",
    "nivel": 2,
    "classes": ["Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "1,5m [5 ft.]",
    "componentes": "V S M (4 ou mais flechas ou virotes)",
    "duracao": "8 horas",
    "descricao": "Você planta quatro peças de munição não-mágica - flechas ou virotes de besta - no chão, dentro do alcance da magia, infundindo-as com magia para proteger uma área. Enquanto a magia durar, sempre que uma criatura que não seja você chegar a menos do que 9 metros [30 ft.] da munição pela primeira vez ou encerrar o próprio turno ali, uma peça da munição voa na tentativa de atingi-la. O alvo deve fazer uma salvaguarda de Destreza. Se falhar, sofre 1d6 pontos de dano perfurante, após o que, a munição é destruída. Esta magia se encerra quando não restarem mais munições.\n\nAo conjurar esta magia, ela ignora quaisquer criaturas que você designar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, a quantidade de munição que pode ser afetada aumenta em dois para cada círculo do espaço acima do 2º."
},
{
    "nome": "Coroa da Loucura",
    "nivel": 2,
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Encantamento",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Escolha um humanoide à sua vista e dentro do alcance da magia. O alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria, ou fica enfeitiçado por você enquanto a magia durar. Uma coroa de ferro retorcido e irregular surge na cabeça, e loucura brilhante irradia dos olhos do alvo enquanto a magia durar.\n\nEm cada um dos próprios turnos e antes de se movimentar, o alvo enfeitiçado deve usar uma ação para realizar um ataque corpo a corpo contra uma criatura escolhida mentalmente por você, e que não seja ele mesmo. O alvo pode agir normalmente no turno caso você não escolha uma criatura ou se nenhuma estiver no alcance dele.\n\nEm seus turnos subsequentes, você deve usar uma ação para manter controle sobre o alvo, ou a magia se encerra. Enquanto estiver enfeitiçado, o alvo deve fazer uma salvaguarda de Sabedoria no início de cada um dos turnos dele. Em caso de sucesso, a magia se encerra."
},
{
    "nome": "Crescer Espinhos",
    "nivel": 2,
    "classes": ["Druida", "Patrulheiro"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "45m [150 ft.]",
    "componentes": "V S M (sete espinhos afiados ou sete pequenos galhos, cada um deles com a ponta afiada)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "O chão, em um raio de 6 metros [20-foot radius] centrado em um ponto no alcance da magia, é revirado e dele brotam espigões e espinhos. A área se torna terreno difícil enquanto a magia durar. Quando uma criatura entrar na área ou se mover dentro dela, ela sofre 2d4 pontos de dano perfurante para cada 1,5 metro [5 ft.] que se mover.\n\nA transformação do solo é camuflada para parecer natural. Qualquer criatura que não possa ver a área no momento da conjuração da magia deve fazer um teste de Sabedoria (Percepção) contra a CD para evitar sua magia para perceber o terreno como perigoso antes de entrar nele."
},
{
    "nome": "Despedaçar",
    "nivel": 2,
    "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (uma lasca de mica)",
    "duracao": "Instantânea",
    "descricao": "Um ruído súbito e estridente, dolorosamente intenso, irrompe a partir de um ponto à sua escolha, no alcance da magia. Cada criatura em uma esfera de 3 metros de raio [10-foot-radius sphere] centrado naquele ponto deve fazer uma salvaguarda de Constituição. Se falhar, sofre 3d8 pontos de dano trovejante, ou metade do dano em caso de sucesso. Uma criatura feita de material inorgânico, como pedra, cristal ou metal tem desvantagem nesta salvaguarda.\n\nUm objeto não-mágico que não esteja sendo usado ou carregado também sofre o dano se estiver na área da magia.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d8 para cada círculo do espaço acima do 2º."
},
{
    "nome": "Detectar Pensamentos",
    "nivel": 2,
    "classes": ["Bardo", "Feiticeiro", "Mago"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Pessoal",
    "componentes": "V S M (uma peça de cobre)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Enquanto a magia durar, você pode ler os pensamentos de certas criaturas. Ao conjurar esta magia, e com uma ação em cada um de seus turnos enquanto a magia durar, você pode focar sua mente em qualquer criatura à sua vista e que esteja a até 9 metros [30 ft.] de distância de você. Se a criatura que você escolher tiver uma Inteligência igual ou menor que 3, ou não falar qualquer idioma, ela não é afetada.\n\nInicialmente, você descobre os pensamentos superficiais da criatura. Com uma ação, você pode sondar mais profundamente a mente da mesma criatura. O alvo deve fazer uma salvaguarda de Sabedoria. Se falhar, você acessa raciocínios, estado emocional e qualquer coisa importante em sua mente. Se tiver sucesso, a magia se encerra. O alvo sabe que você está sondando sua mente.\n\nVocê também pode usar esta magia para detectar a presença de criaturas pensantes em até 9 metros [30 ft.], mesmo sem vê-las, desde que não estejam protegidas por barreiras como 60 cm de pedra, 5 cm de metal ou uma folha fina de chumbo."
},
{
    "nome": "Diabo da Poeira",
    "nivel": 2,
    "classes": ["Druida", "Feiticeiro", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um punhado de pó)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Escolha um cubo de ar de 1,5 metro [5 ft.] desocupado dentro do alcance. Um elemental semelhante a um redemoinho aparece no cubo. Criaturas a até 1,5 metro [5 ft.] do redemoinho ao final de seu turno devem fazer uma salvaguarda de Força. Em caso de falha, sofrem 1d8 de dano contundente e são empurradas 3m [10 ft.]. Se passarem, sofrem metade do dano e não são empurradas.\n\nCom uma ação bônus, você pode mover o redemoinho 9m [30 ft.] em qualquer direção. Se passar por areia, poeira, terra solta ou cascalho, forma uma nuvem de 3m de raio de escuridão densa até o início do seu próximo turno.\n\nEm Níveis Superiores. O dano aumenta em 1d8 para cada nível do espaço de magia acima do 2º."
},
{
    "nome": "Encontrar Armadilhas",
    "nivel": 2,
    "classes": ["Clérigo", "Druida", "Patrulheiro"],
    "escola": "Adivinhação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "36m [120 ft.]",
    "componentes": "V S",
    "duracao": "Instantânea",
    "descricao": "Você sente a presença de qualquer armadilha em sua linha de visão e no alcance da magia. Uma armadilha, para os fins desta magia, inclui qualquer coisa que causaria um efeito repentino ou inesperado que você considera danoso ou indesejado, e que tenha sido especificamente projetada como tal por quem a criou.\n\nA magia não revela a localização exata, mas permite que você saiba a natureza geral do perigo que a armadilha representa."
},
  {
    "nome": "Escalada de Aranha",
    "nivel": 2,
    "classes": ["Artífice", "Bruxo", "Feiticeiro", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "Toque",
    "componentes": "V S M (uma gota de betume e uma aranha)",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Enquanto a magia durar, uma criatura voluntária tocada por você ganha a habilidade de se mover para cima, para baixo e ao longo de superfícies verticais e de cabeça para baixo através de tetos, mantendo suas mãos livres. O alvo também ganha um deslocamento de escalada idêntico ao próprio deslocamento de caminhada."
  },
  {
    "nome": "Escrita Celeste",
    "nivel": 2,
    "classes": ["Bardo", "Druida", "Mago"],
    "escola": "Transmutação",
    "tempo_conjuracao": "Uma ação ou Ritual",
    "alcance": "Linha de visão",
    "componentes": "V S",
    "duracao": "Concentração, Até uma hora",
    "descricao": "Você faz com que até dez palavras se formem em uma parte do céu que você possa ver. As palavras parecem ser feitas de nuvens e permanecem no local pela duração da magia. As palavras desaparecem quando a magia termina. Um vento forte pode dispersar as nuvens e terminar a magia prematuramente."
  },
  {
    "nome": "Escuridão",
    "nivel": 2,
    "classes": ["Bruxo", "Feiticeiro", "Mago"],
    "escola": "Evocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V M (pelo de morcego e uma gota de piche ou pedaço de carvão)",
    "duracao": "Concentração, Até 10 minutos",
    "descricao": "Uma esfera de escuridão mágica, com raio de 4,5 m [15-foot radius], se alastra a partir de um ponto à sua escolha, no alcance da magia e permanece enquanto a magia durar. A escuridão se alastra, contornando os cantos. Uma criatura com visão no escuro não pode ver através dessa escuridão, e uma luz não mágica não pode iluminá-la. Se o ponto estiver em um objeto que não esteja sendo usado ou carregado, a escuridão se move com ele. Cobrir a origem com um objeto opaco bloqueia a escuridão. Luz mágica de 2º círculo ou inferior é anulada pela área da escuridão."
  },
  {
    "nome": "Esfera Flamejante",
    "nivel": 2,
    "classes": ["Druida", "Mago"],
    "escola": "Invocação",
    "tempo_conjuracao": "Uma ação",
    "alcance": "18m [60 ft.]",
    "componentes": "V S M (um pouco de sebo, uma pitada de enxofre e poeira de ferro em pó)",
    "duracao": "Concentração, Até 1 minuto",
    "descricao": "Uma esfera de fogo com 1,5 metro de diâmetro [5-foot-diameter sphere] aparece em um espaço desocupado à sua escolha, dentro do alcance, e permanece enquanto a magia durar. Criaturas que terminem o turno a até 1,5 metro [5 ft.] da esfera devem fazer uma salvaguarda de Destreza, sofrendo 2d6 de dano ígneo em falha ou metade em sucesso. Com uma ação bônus, você pode mover a esfera até 9m [30 ft.]. Ela pode ultrapassar barreiras de até 1,5m de altura e fossos de até 3m de largura. Ela incendeia objetos inflamáveis não carregados e emite luz plena em 6m e meia-luz por mais 6m.\n\nEm Níveis Superiores. O dano aumenta em 1d6 para cada círculo do espaço acima do 2º."
  },
  {
  "nome": "Espinho Mental",
  "nivel": 2,
  "escola": "Adivinhação",
  "classes": ["Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m [60 ft.]",
  "componentes": "S",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Você alcança a mente de uma criatura que pode ver dentro do alcance. O alvo deve fazer uma salvaguarda de Sabedoria, sofrendo 3d8 de dano psíquico em falha, ou metade em sucesso. Em uma falha, você também conhece a localização do alvo até o fim da magia, desde que estejam no mesmo plano. O alvo não pode se esconder de você nem se beneficiar de invisibilidade contra você.\n\nEm Níveis Superiores: o dano aumenta em 1d6 por nível acima do 2º."
},
{
  "nome": "Espírito Curativo",
  "nivel": 2,
  "escola": "Invocação",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "18m [60 ft.]",
  "componentes": "V S",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você invoca um espírito em forma de besta ou fada transparente que cura 1d6 PV sempre que uma criatura entra ou começa o turno no seu espaço. Não cura mortos-vivos nem construtos. O espírito pode ser movido 9m como ação bônus.\n\nEm Níveis Superiores: a cura aumenta em 1d6 por nível acima do 2º."
},
{
  "nome": "Esquentar Metal",
  "nivel": 2,
  "escola": "Transmutação",
  "classes": ["Artífice", "Bardo", "Druida"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m [60 ft.]",
  "componentes": "V S M (um pedaço de ferro e uma chama)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você aquece um objeto metálico visível, fazendo-o brilhar em vermelho. Criaturas em contato sofrem 2d8 de dano ígneo e devem soltar o objeto (Constituição para manter). Se falhar, têm desvantagem em ataques e testes de atributo até o próximo turno do conjurador. Você pode causar o dano novamente como ação bônus.\n\nEm Níveis Superiores: o dano aumenta em 1d8 por nível acima do 2º."
},
{
  "nome": "Flecha Ácida",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "27m [90 ft.]",
  "componentes": "V S M (folhas de ruibarbo em pó e um estômago de víbora)",
  "duracao": "Instantânea",
  "descricao": "Dispara uma flecha de ácido em um alvo. Faça um ataque mágico à distância. Se acertar, causa 4d4 de dano ácido imediato e 2d4 no final do próximo turno do alvo. Em erro, causa metade do dano inicial e nenhum dano posterior.\n\nEm Níveis Superiores: o dano (inicial e posterior) aumenta em 1d4 por nível acima do 2º."
},
{
  "nome": "Força Espectral",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Bardo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um pouco de lã)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você cria uma ilusão que se enraíza na mente de uma criatura à sua vista e dentro do alcance da magia. O alvo deve fazer uma salvaguarda de Inteligência. Se falhar, você cria um objeto, criatura ou outro fenômeno fantasmagórico visível, à sua escolha, que não seja maior do que um cubo de 3 metros (10-foot cube) e que é perceptível apenas pelo alvo, enquanto a magia durar. Essa magia não tem efeito sobre mortos-vivos ou constructos.\n\nO fantasma pode incluir som, temperatura, e outros estímulos, também apenas evidentes para a criatura.\n\nO alvo pode usar uma reação para examinar o fantasma com um teste de Inteligência (Investigação) contra a CD para evitar sua magia. Se o teste for bem-sucedido, o alvo percebe que o fantasma é uma ilusão, e a magia se encerra.\n\nEnquanto a magia durar, o alvo trata o fantasma como se fosse real. O alvo racionaliza quaisquer resultados ilógicos de interações com o fantasma. Por exemplo, um alvo que esteja tentando atravessar uma ponte fantasma sobre um abismo cai assim que pisa na ponte. Caso sobreviva à queda, o alvo ainda acredita na existência da ponte, e tenta achar alguma explicação para a própria queda - foi empurrado, escorregou, ou um forte vento o derrubou.\n\nUm alvo afetado está tão convencido da veracidade do fantasma que pode até mesmo sofrer dano da ilusão. Um fantasma criado na forma de uma criatura pode atacar o alvo. Da mesma forma, um fantasma criado na forma de chamas, poça de ácido ou lava pode queimar o alvo. A cada rodada, no seu turno, o fantasma causa 1d6 pontos de dano psíquico no alvo se este estiver na área ou a até 1,5 metros (5 ft.) do fantasma, desde que a ilusão seja de uma criatura ou de um perigo que poderia causar dano de alguma forma lógica, atacando, por exemplo. O alvo percebe o dano como sendo de um tipo apropriado à ilusão."
},
{
  "nome": "Imobilizar Pessoa",
  "nivel": 2,
  "escola": "Encantamento",
  "classes": ["Bardo", "Bruxo", "Clérigo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um pedaço pequeno e reto de ferro)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Escolha um humanoide à sua vista e no alcance da magia. O alvo deve ser bem-sucedido em uma salvaguarda de Sabedoria ou fica paralisado enquanto a magia durar. No final de cada um dos turnos dele, o alvo pode fazer outra salvaguarda de Sabedoria. Em caso de sucesso, a magia se encerra sobre o alvo.\n\nEm Níveis Superiores: Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, você pode atingir um humanoide adicional para cada círculo do espaço acima do 2º. Os humanoides devem estar a até de 9 metros (30 ft.) uns dos outros quando você os atingir."
},
{
  "nome": "Invisibilidade",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Artífice", "Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (um cílio envolto em goma arábica)",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Uma criatura que você tocar torna-se invisível enquanto a magia durar. Qualquer coisa que o alvo estiver usando ou carregando torna-se invisível enquanto estiver em sua posse. A magia se encerra quando o alvo efetuar um ataque ou conjurar uma magia.\n\nEm Níveis Superiores: Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, você pode atingir uma criatura adicional para cada círculo do espaço acima do 2º."
},
{
  "nome": "Invocar Besta",
  "nivel": 2,
  "escola": "Invocação",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "27m (90 ft.)",
  "componentes": "V S M (uma pena, tufo de pelo e uma cauda de peixe dentro de uma bolota dourada no valor de pelo menos 200 PO)",
  "duracao": "Concentração, Uma hora",
  "descricao": "Você invoca um espírito bestial. Ele se manifesta em um espaço desocupado que você pode ver dentro do alcance. Esta forma corpórea usa o bloco de estatísticas de Espírito Bestial. Ao lançar a magia, escolha um ambiente: Ar, Terra ou Água. A criatura se assemelha a um animal de sua escolha, nativo do ambiente escolhido, o que determina certas características em seu bloco de estatísticas. A criatura desaparece quando cai para 0 pontos de vida ou quando a magia termina.\n\nA criatura é uma aliada para você e seus companheiros. Em combate, a criatura compartilha sua posição de iniciativa, mas realiza seu turno imediatamente após o seu. Ela obedece aos seus comandos verbais (nenhuma ação exigida de sua parte). Se você não emitir nenhum, ela executa a ação de Esquiva e usa seu deslocamento para evitar o perigo.\n\nEm Níveis Superiores: Quando você conjura esta magia usando um espaço de magia de 3º círculo ou superior, use o círculo mais alto onde quer que o círculo da magia apareça no bloco de estatísticas."
},
{
  "nome": "Lâmina de Sombras",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Pessoal",
  "componentes": "V S",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você entrelaça fios de sombra para criar uma espada de trevas sólidas em sua mão. Esta espada mágica dura até a magia terminar. Ela conta como uma arma simples de combate corpo a corpo com a qual você é proficiente. Ela provoca um dano psíquico de 2d8 em um golpe e possui propriedades sutileza, leve e arremessável (alcance 20/60). Além disso, quando você usa a espada para atacar um alvo que está em luz fraca ou na escuridão, você faz a rolagem de ataque com vantagem. Se você soltar a arma ou arremessá-la, ela se dissipa no final do turno. Posteriormente, enquanto a magia persistir, você pode usar uma ação bônus para que a espada reapareça na sua mão.\n\nEm Níveis Superiores. Quando você lança esta magia usando um espaço de magia de 3º ou 4º círculo, o dano aumenta para 3d8. Quando você o lança usando um espaço de magia de 5º ou 6º círculo, o dano aumenta para 4d8. Quando você o lança usando um espaço de magia de 7º círculo ou superior, o dano aumenta para 5d8."
},
{
  "nome": "Lâmina Flamejante",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Druida"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Pessoal",
  "componentes": "V S M (uma folha de sumagre)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Você evoca uma lâmina de fogo em sua mão livre. A lâmina é semelhante em tamanho e forma a uma cimitarra e permanece enquanto a magia durar. Se você soltar a lâmina, ela desaparece, mas você pode evocá-la novamente com uma ação bônus.\n\nA lâmina de fogo pode ser usada para fazer um ataque mágico corpo a corpo, usando uma ação. Se acertar, o alvo sofre 3d6 pontos de dano ígneo.\n\nA lâmina flamejante emite luz plena em um raio de 3 metros (10 ft.) e cria meia-luz por 3 metros adicionais.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 4º círculo ou superior, o dano aumenta em 1d6 para cada dois círculos do espaço de magia acima do 2º."
},
{
  "nome": "Levitação",
  "nivel": 2,
  "escola": "Transmutação",
  "classes": ["Artífice", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um pequeno laço de couro ou um pedaço de fio dourado dobrado na forma de uma xícara com haste longa em uma das extremidades)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Escolha uma criatura ou objeto à sua vista e no alcance da magia. O alvo sobe verticalmente a até 6 metros (20 ft.) de altura, permanecendo suspenso enquanto a magia durar. A magia pode levitar um alvo que pese até 225 quilos (500 pounds). Uma criatura involuntária que seja bem-sucedida em uma salvaguarda de Constituição não é afetada.\n\nO alvo pode se mover apenas ao empurrar ou puxar um objeto fixo ou superfície ao alcance dele (como uma parede ou teto), o que permite que ele se mova como se estivesse escalando. No seu turno, você pode mudar a altitude do alvo em até 6 metros (20 ft.) em qualquer direção. Se você for o alvo, pode mover-se para cima ou para baixo como parte do seu deslocamento. Caso contrário, você pode usar sua ação para mover o alvo, que deve permanecer no alcance da magia.\n\nQuando esta magia terminar, caso ainda esteja no ar, o alvo inicia uma descida suave, flutuando em direção ao solo."
},
{
  "nome": "Localizar Objeto",
  "nivel": 2,
  "escola": "Adivinhação",
  "classes": ["Bardo", "Clérigo", "Druida", "Patrulheiro", "Mago", "Paladino"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V S M (um galho bifurcado)",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Descreva ou nomeie um objeto que lhe seja familiar. Você sente a direção do local onde ele se encontra, caso esteja a, no máximo, 300 metros (1000 ft.) de distância. Se o objeto estiver se movendo, você sabe em que direção.\n\nA magia pode localizar um objeto específico que você conheça, desde que você já o tenha visto de perto - a até 9 metros (30 ft.) - ao menos uma vez. Se preferir, a magia pode localizar um objeto de um tipo específico, como certo tipo de traje, joia, mobília, ferramenta ou arma.\n\nEsta magia não pode localizar um objeto se qualquer espessura de chumbo, até mesmo uma folha fina, bloquear o caminho direto entre você ele."
},
{
  "nome": "Lufada de Vento",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal (linha de 18m (60 ft.))",
  "componentes": "V S M (uma semente de legume)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Uma linha de vento forte, com 18 metros (60 ft.) de comprimento e 3 metros (10 ft.) de largura, é soprada a partir de você em uma direção à sua escolha, enquanto a magia durar. Cada criatura que comece seu próprio turno na linha deve ser bem-sucedida em uma salvaguarda de Força ou é empurrada 4,5 metros (15 ft.) para longe de você, a favor da linha de vento.\n\nQualquer criatura na linha deve gastar 3 metros (10 ft.) de deslocamento para cada 1,5 metro (5 ft.) que se movimentar na sua direção.\n\nA lufada dispersa gases ou vapor e apaga velas, tochas e chamas semelhantes que estejam desprotegidas na área. Ela faz com que chamas protegidas, como as de lanternas, oscilem descontroladamente e tenham 50 por cento de chance de se extinguirem.\n\nCom uma ação bônus em cada um dos seus turnos antes do final da magia, você pode mudar a direção na qual a linha sopra a partir de você."
},
{
  "nome": "Marca da Punição",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Paladino"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Enquanto durar esta magia, na próxima vez que você atingir uma criatura com uma arma, ela brilhará com radiação astral conforme você acerta. O ataque causa 2d6 pontos de dano radiante adicionais ao alvo, que torna-se visível (caso esteja invisível), emitindo uma luz fraca, criando meia-luz num raio de 1,5 metro (5 ft.) e não podendo retornar à condição invisível enquanto a magia durar.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d6 para cada círculo do espaço acima do 2º."
},
{
  "nome": "Mensageiro Animal",
  "nivel": 2,
  "escola": "Encantamento",
  "classes": ["Bardo", "Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação ou Ritual",
  "alcance": "9m (30 ft.)",
  "componentes": "V S M (um punhado de comida)",
  "duracao": "24 horas",
  "descricao": "Por meio desta magia, você usa um animal para entregar uma mensagem. Escolha uma fera Minúscula à sua vista e no alcance da magia, como um esquilo, uma gralha azul ou um morcego. Você especifica uma localização que já tenha visitado e um destinatário que combine com uma descrição geral, tal como: 'uma mulher ou um homem vestido com o uniforme da guarda da cidade' ou 'um anão ruivo usando um chapéu pontudo'. Você também deve falar uma mensagem de até vinte e cinco palavras. Enquanto a magia durar, a fera alvo viaja em direção à localização especificada, cobrindo cerca de 80 quilômetros (50 miles) durante 24 horas para um mensageiro voador, ou 40 quilômetros (25 miles) para outros animais.\n\nQuando o mensageiro chegar, ele entrega a mensagem para a criatura que você descreveu, replicando o som da sua voz. O mensageiro fala somente com a criatura que combina com a descrição que você forneceu. Se o mensageiro não alcançar o destino antes do fim da duração da magia, a mensagem se perde e a fera refaz o caminho de volta para o lugar onde você conjurou a magia.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 3º círculo ou superior, a duração da magia aumenta em 48 horas para cada círculo do espaço acima do 2º."
},
{
  "nome": "Nuvem de Adagas",
  "nivel": 2,
  "escola": "Invocação",
  "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um caco de vidro)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Você preenche o ar com adagas rodopiantes em um cubo de 1,5 metro de lado (5-foot cube), centrado em um ponto à sua escolha e dentro do alcance da magia. Uma criatura sofre 4d4 pontos de dano cortante quando entra na área da magia pela primeira vez, ou quando inicia o próprio turno ali.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 2d4 para cada círculo do espaço acima do 2º."
},
{
  "nome": "Oração de Cura",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Clérigo"],
  "tempo_conjuracao": "10 minutos",
  "alcance": "9m (30 ft.)",
  "componentes": "V",
  "duracao": "Instantânea",
  "descricao": "Escolha até seis criaturas à sua vista e no alcance da magia. Elas recuperam uma quantidade de pontos de vida igual a 2d8 + seu modificador de atributo de conjuração. Esta magia não tem efeito sobre mortos-vivos ou constructos.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, a cura aumenta em 1d8 para cada círculo do espaço acima do 2º."
},
{
  "nome": "Passo Nebuloso",
  "nivel": 2,
  "escola": "Invocação",
  "classes": ["Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação bônus",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Instantânea",
  "descricao": "Rodeado brevemente por uma névoa prateada, você se teleporta a até 9 metros (30 ft.) para um espaço desocupado à sua vista."
},
{
  "nome": "Passo sem Rastro",
  "nivel": 2,
  "escola": "Abjuração",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V S M (cinzas de uma folha de visco queimada e um ramo de abeto)",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Um véu de sombras e silêncio irradia de você, mascarando você e seus aliados contra detecção. Enquanto a magia durar, cada criatura à sua escolha no alcance de 9 metros (30 ft.) (incluindo você) tem um bônus de +10 nos testes de Destreza (Furtividade) e não pode ser rastreada a não ser por meios mágicos. Uma criatura com este bônus não deixa rastros ou outros traços de sua passagem."
},
{
  "nome": "Pele de árvore",
  "nivel": 2,
  "escola": "Transmutação",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (um punhado de casca de carvalho)",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Você toca uma criatura voluntária. A magia transforma a pele do alvo, tornando-a áspera e com a aparência de casca de árvore. Enquanto a magia durar, o alvo tem uma CA que não pode ser menor do que 16, independente do tipo de armadura vestida."
},
{
  "nome": "Pirotecnia",
  "nivel": 2,
  "escola": "Transmutação",
  "classes": ["Bardo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S",
  "duracao": "Instantânea",
  "descricao": "Escolha uma área de chamas que você possa ver e que caiba num cubo de 1,5 metro (5-foot cube), dentro do alcance. Você pode extinguir o fogo na área e criar tanto fogos de artifício quanto fumaça.\n\nFogos de Artifício. O alvo explode em uma apresentação incrível de cores. Cada criatura a até 3m (10 ft.) do alvo deve ser bem-sucedida em salvaguarda de Constituição ou ficará cega até o final do seu próximo turno.\n\nFumaça. Uma fumaça negra e espessa se espalha do alvo num raio de 6m (20-foot radius), dobrando esquinas. A área da fumaça é de escuridão densa. A fumaça persiste por 1 minuto ou até um vento forte dispersá-la."
},
{
  "nome": "Proteção Contra Veneno",
  "nivel": 2,
  "escola": "Abjuração",
  "classes": ["Artífice", "Clérigo", "Druida", "Patrulheiro", "Paladino"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "Uma hora",
  "descricao": "Você toca uma criatura. Se ela estiver envenenada, você neutraliza o veneno. Se mais de um veneno afligir o alvo, você neutraliza o veneno que sabe estar presente, ou neutraliza um deles, ao acaso.\n\nEnquanto a magia durar, o alvo tem vantagem nas salvaguardas contra ser envenenado, e resistência a dano venenoso."
},
{
  "nome": "Queimadura de Aganazzar",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "9m (30 ft.)",
  "componentes": "V S M (uma escama de dragão vermelho)",
  "duracao": "Instantânea",
  "descricao": "Uma linha de chamas vociferantes de 9m (30 ft.) de comprimento e 1,5 metro (5 ft.) de espessura emana de você em uma direção de sua escolha. Cada criatura na linha deve realizar salvaguarda de Destreza. Uma criatura sofre 3d8 de dano de fogo se fracassar na resistência, ou metade desse dano se obtiver sucesso.\n\nEm Níveis Superiores. Quando você conjura essa magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d8 para cada nível do espaço acima do 2º."
},
{
  "nome": "Raio Ardente",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m (120 ft.)",
  "componentes": "V S",
  "duracao": "Instantânea",
  "descricao": "Você cria três raios de fogo e os dispara em alvos que estejam no alcance da magia. Você pode dispará-los contra um alvo ou vários. Faça um ataque mágico à distância para cada raio. Se acertar, o alvo sofre 2d6 pontos de dano ígneo.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, você cria um raio adicional para cada círculo do espaço acima do 2º."
},
{
  "nome": "Raio do Enfraquecimento",
  "nivel": 2,
  "escola": "Necromancia",
  "classes": ["Bruxo", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Um feixe negro de energia debilitante brota do seu dedo em direção a uma criatura no alcance da magia. Faça um ataque mágico à distância contra o alvo. Se acertar, enquanto a magia durar, o alvo passa a causar apenas metade do dano em ataques armados que usem Força.\n\nNo final de cada um dos próprios turnos, o alvo pode fazer uma salvaguarda de Constituição contra a magia. Em caso de sucesso, a magia se encerra."
},
{
  "nome": "Raio Lunar",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Druida"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "36m (120 ft.)",
  "componentes": "V S M (várias sementes de qualquer trepadeira-da-lua e um pedaço de feldspato opalescente)",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Um feixe pálido de luz prateada brilha em um cilindro de 1,5 metro de raio e 12 metros de altura [5-foot-radius, 40-foot-high cilinder], centrado em um ponto no alcance da magia. O cilindro é preenchido por meia-luz enquanto a magia durar.\n\nQuando uma criatura entra pela primeira vez ou inicia o próprio turno na área da magia, ela será engolfada em chamas fantasmagóricas que causam dor lancinante, e deve fazer uma salvaguarda de Constituição. Se falhar, sofre 2d10 pontos de dano radiante, ou metade do dano em caso de sucesso.\n\nUm metamorfo faz esta salvaguarda com desvantagem. Se falhar, ele também reverte para própria forma original, permanecendo incapaz de assumir uma forma diferente até sair da luz da magia.\n\nEm cada um de seus turnos após conjurar esta magia, você pode usar uma ação para mover o feixe a até 18 metros (60 ft.) em qualquer direção.\n\nEm Níveis Superiores. Ao conjurar esta magia usando um espaço de magia de 3º círculo ou superior, o dano aumenta em 1d10 para cada círculo do espaço acima do 2º."
},
{
  "nome": "Reflexos",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V S",
  "duracao": "1 minuto",
  "descricao": "Três duplicatas ilusórias de você aparecem no seu espaço. Enquanto a magia durar, as duplicatas se movem com você e imitam suas ações e mudanças de posição, tornando impossível distinguir qual das imagem é a verdadeira. Você pode usar uma ação para dispensar as duplicatas ilusórias.\n\nEnquanto a magia durar, cada vez que uma criatura tem você como alvo de um ataque, jogue 1d20 para determinar se ela ataca uma das suas duplicatas.\n\nCaso tenha três duplicatas, você deve tirar 6 ou mais para mudar o ataque para uma cópia. Com duas duplicatas, você deve tirar um 8 ou mais. Com uma duplicata, você deve tirar um 11 ou mais.\n\nA CA da duplicata é igual a 10 + seu modificador de Destreza. Se o ataque acertar uma duplicata, ela é destruída. Uma duplicata só pode ser destruída por um ataque que a acerte. Ela ignora todos os outros efeitos e danos. A magia termina quando as três duplicatas forem destruídas.\n\nUma criatura não é afetada por esta magia se não puder ver, se depender de outros sentidos que não a visão, como percepção às cegas, ou se ela puder perceber ilusões como falsas, com o uso de visão verdadeira."
},
{
  "nome": "Repouso Tranquilo",
  "nivel": 2,
  "escola": "Necromancia",
  "classes": ["Clérigo", "Mago"],
  "tempo_conjuracao": "Uma ação ou Ritual",
  "alcance": "Toque",
  "componentes": "V S M (uma pitada de sal e uma peça de cobre colocada sobre cada um dos olhos do cadáver, lugar no qual devem permanecer enquanto a magia durar)",
  "duracao": "10 dias",
  "descricao": "Você toca um cadáver ou outros restos mortais. Enquanto a magia durar, o alvo está protegido da decomposição e não pode se tornar um morto-vivo.\n\nA magia também estende efetivamente o tempo limite para trazer o alvo dos mortos, pois os dias passados sob a influência desta magia não contam contra o tempo limite de magias como Reviver os Mortos."
},
{
  "nome": "Restauração Menor",
  "nivel": 2,
  "escola": "Abjuração",
  "classes": ["Artífice", "Bardo", "Clérigo", "Druida", "Patrulheiro", "Paladino"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S",
  "duracao": "Instantânea",
  "descricao": "Você toca uma criatura e pode tanto curar uma doença quanto remover uma condição que a aflija. A condição pode ser cego, envenenado, paralisado ou surdo."
},
{
  "nome": "Sentido Feral",
  "nivel": 2,
  "escola": "Adivinhação",
  "classes": ["Druida", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação ou Ritual",
  "alcance": "Toque",
  "componentes": "S",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Você toca uma fera voluntária. Enquanto a magia durar, você pode usar a sua ação para ver através dos olhos da fera e ouvir o que ela ouve, e continua a fazê-lo até usar sua ação para retornar aos seus sentidos normais. Enquanto estiver percebendo através dos sentidos da fera, você se beneficia de qualquer sentido especial que ela possua, passando a estar cego e surdo ao que está ao seu redor."
},
{
  "nome": "Silêncio",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Bardo", "Clérigo", "Patrulheiro"],
  "tempo_conjuracao": "Uma ação ou Ritual",
  "alcance": "36m (120 ft.)",
  "componentes": "V S",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Enquanto a magia durar, nenhum som pode ser criado dentro ou passar através de uma esfera de 6 metros de raio, centrado em um ponto à sua escolha e no alcance da magia. Qualquer criatura ou objeto inteiramente dentro da esfera é imune a dano trovejante, e criaturas ficam surdas enquanto estiverem totalmente dentro dela. Conjurar uma magia que inclua um componente verbal é impossível dentro da área de efeito."
},
{
  "nome": "Sugestão",
  "nivel": 2,
  "escola": "Encantamento",
  "classes": ["Bardo", "Bruxo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "9m (30 ft.)",
  "componentes": "V M (uma língua de uma cobra e um pouco de favo de mel ou uma gota de óleo adocicado)",
  "duracao": "Concentração, Até 8 horas",
  "descricao": "Você sugere um curso de ação (limitado a uma sentença ou duas) e influencia magicamente uma criatura à sua vista no alcance da magia e que possa lhe ouvir e compreender. Criaturas que não podem ser enfeitiçadas são imunes a este efeito. A sugestão precisa ser dita de uma forma que faça o curso de ação parecer razoável. Pedir à criatura que se esfaqueie, jogue-se contra uma lança, imole-se ou faça algum outro ato evidentemente danoso, automaticamente cancela o efeito da magia.\n\nO alvo deve fazer uma salvaguarda de Sabedoria. Se falhar, ele segue os atos sugeridos da melhor forma possível, segundo suas habilidades. A continuidade dos atos será feita enquanto a magia durar. Se a atividade sugerida pode ser completada em um período menor, a magia se encerra quando o sujeito termina aquilo que lhe foi sugerido.\n\nTambém podem ser especificadas condições que disparam uma atividade especial enquanto estiver dentro da duração da magia. Por exemplo, pode ser sugerido que uma cavaleira dê sua montaria ao primeiro mendigo que ela encontrar. Se a condição não for preenchida antes do fim dos efeitos, a atividade não é concluída.\n\nSe você ou qualquer de seus companheiros causarem dano ao alvo, a magia se encerra."
},
{
  "nome": "Teia",
  "nivel": 2,
  "escola": "Invocação",
  "classes": ["Artífice", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S M (um pouco de teia de aranha)",
  "duracao": "Concentração, Até uma hora",
  "descricao": "Você conjura uma massa de teia espessa e pegajosa em um ponto à sua escolha e no alcance da magia. A teia preenche um cubo de 6 metros (20 ft.) a partir daquele ponto enquanto a magia durar. A teia é considerada terreno difícil e torna a área parcialmente obscurecida.\n\nSe a teia não estiver sendo sustentada por duas massas sólidas (como paredes ou árvores) ou estiver em camadas, cobrindo o chão, parede ou teto, ela colapsa sobre si mesma, e a magia se encerra no início do seu próximo turno. A cobertura de teias sobre uma superfície possui uma profundidade de 1,5 metro (5 ft.).\n\nCada criatura que entrar ou iniciar o próprio turno na teia deve fazer uma salvaguarda de Destreza. Se falhar, a criatura está contida enquanto estiver na teia ou até que consiga se soltar.\n\nUma criatura contida pela teia pode usar a própria ação para fazer uma salvaguarda de Força contra a CD para evitar sua magia. Se for bem-sucedida, ela não estará mais contida.\n\nAs teias são inflamáveis. Qualquer cubo de teia de 1,5 metro (5 ft.) que for exposto ao fogo, queima em 1 rodada e causa 2d4 pontos de dano ígneo a qualquer criatura que comece o próprio turno no fogo."
},
{
  "nome": "Tranca Arcana",
  "nivel": 2,
  "escola": "Abjuração",
  "classes": ["Artífice", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (pó de ouro no valor de pelo menos 25 PO, que é consumido pela magia)",
  "duracao": "Até ser dissipada",
  "descricao": "Você toca uma porta, janela, portão, baú, ou outro tipo de entrada que já esteja fechada, tornando-a bloqueada enquanto a magia durar. Você e as criaturas que designar ao realizar a conjuração podem abrir o objeto normalmente. Você também pode definir uma senha que, quando dita a até 1,5 metro (5 ft.) do objeto, suprima esta magia durante 1 minuto. Caso contrário, o objeto fica trancado até que seja quebrado ou a magia seja dissipada ou suprimida. Conjurar Arrombar no objeto suprime a tranca arcana por 10 minutos.\n\nEnquanto afetado por esta magia, o objeto é mais difícil de quebrar ou arrombar; a CD para quebrá-lo ou arrombar qualquer fechadura contida nele aumenta em 10."
},
{
  "nome": "Turvar",
  "nivel": 2,
  "escola": "Ilusão",
  "classes": ["Artífice", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Concentração, Até 1 minuto",
  "descricao": "Seu corpo torna-se turvo, mudando e oscilando para todos os que possam vê-lo. Ao longo da duração desta magia, qualquer criatura tem desvantagem em jogadas de ataque contra você. Um atacante é imune a este efeito se não depender da visão, como alguém com percepção às cegas, ou se puder ver através de ilusões, como alguém com visão verdadeira."
},
{
  "nome": "Vento Protetor",
  "nivel": 2,
  "escola": "Evocação",
  "classes": ["Bardo", "Druida", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V",
  "duracao": "Concentração, Até 10 minutos",
  "descricao": "Um vento forte (30 quilômetros por hora) sopra à sua volta num raio de 3m (10-foot radius) e se move com você, permanecendo centrado em você. O vento permanece pela duração da magia. O vento tem os seguintes efeitos: Ele ensurdece você e outras criaturas na área. Ele extingue chamas desprotegidas na área que tenham o tamanho de tochas ou menores. A área é de terreno difícil para outras criaturas diferentes de você. As jogadas de ataque à distância com armas têm desvantagem se passarem para dentro ou para fora do vento. Ele afasta vapor, gás e névoa que possa ser dissipado por um vento forte."
},
{
  "nome": "Ver o Invisível",
  "nivel": 2,
  "escola": "Adivinhação",
  "classes": ["Artífice", "Bardo", "Feiticeiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Pessoal",
  "componentes": "V S M (uma pitada de talco e uma pequena pitada de pó de prata)",
  "duracao": "Uma hora",
  "descricao": "Enquanto a magia durar, você vê criaturas e objetos invisíveis, como se eles fossem visíveis, além de poder ver no Plano Etéreo. Criaturas e objetos etéreos parecem fantasmagóricos e translúcidos."
},
{
  "nome": "Vínculo de Proteção",
  "nivel": 2,
  "escola": "Abjuração",
  "classes": ["Clérigo"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (um par de anéis de platina no valor mínimo de 50 PO cada, que você e o alvo devem usar enquanto a magia durar)",
  "duracao": "Uma hora",
  "descricao": "Esta magia protege uma criatura voluntária que você toca, criando uma conexão mística entre o alvo e você enquanto a magia durar. Enquanto o alvo estiver no alcance de 18 metros (60 ft.) do conjurador, ele ganha +1 de bônus na CA e em salvaguardas, e tem resistência contra todo tipo de dano. Além disso, cada vez que ele sofre dano, você sofre a mesma quantidade de dano.\n\nA magia se encerra se você cair a 0 pontos de vida ou se vocês se afastarem a mais de 18 metros (60 ft.) um do outro.\n\nEla também se encerra se for conjurada novamente em qualquer uma das criaturas conectadas. Você também pode dispensar a magia com uma ação."
},
{
  "nome": "Visão no Escuro",
  "nivel": 2,
  "escola": "Transmutação",
  "classes": ["Artífice", "Druida", "Feiticeiro", "Patrulheiro", "Mago"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "Toque",
  "componentes": "V S M (uma pitada de cenoura seca ou uma ágata)",
  "duracao": "8 horas",
  "descricao": "Ao tocar uma criatura voluntária, você lhe concede a capacidade de enxergar no escuro. O alvo ganha visão no escuro com alcance de até 18 metros (60 ft.) enquanto a magia durar."
},
{
  "nome": "Zona da Verdade",
  "nivel": 2,
  "escola": "Encantamento",
  "classes": ["Bardo", "Clérigo", "Paladino"],
  "tempo_conjuracao": "Uma ação",
  "alcance": "18m (60 ft.)",
  "componentes": "V S",
  "duracao": "10 minutos",
  "descricao": "Você cria uma zona mágica, protegendo contra enganação uma área de esfera com 4,5 metros de raio (15-foot-radius sphere) centrada em um ponto à sua escolha, no alcance da magia. Enquanto a magia durar, quando uma criatura entra pela primeira vez ou inicia o turno na área da magia, ela deve fazer uma salvaguarda de Carisma. Se falhar, a criatura não pode falar uma mentira deliberada enquanto estiver no raio da magia. Você sabe se cada criatura é bem-sucedida ou se falhou na salvaguarda.\n\nUma criatura afetada por esta magia está ciente dos efeitos dela e, portanto, pode evitar responder às perguntas que normalmente responderia com uma mentira. A criatura pode ser evasiva em suas respostas enquanto permanecer dentro dos limites da zona da verdade."
}
]